### ISSUE TITLE
React dev tools

### ISSUE THREAD

**Issue by rogchap** [kadirahq/react-storybook#102]
Firstly, Storybook is a great tool.

Secondly, is it possible use the React (Chrome) dev tools to inspect the components/iframe?

I think this can be enabled by adding (see https://github.com/facebook/react-devtools/issues/76) to the iframe:

``` javascript
if (window.parent !== window) {
  window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
}
```

**Comment by arunoda** [comment]
I think we should support. Send us a PR.

**Comment by rogchap** [comment]
Cool... I'll look into this. Official assigned! :smile:

**Comment by arunoda** [comment]
Awesome.

**Comment by wyattdanger** [comment]
I was just about to submit a PR for this yesterday. Great timing. Will submit now

**Comment by arunoda** [comment]
Merged #104 and released as `v1.11.0`

**Comment by nelsonomuto** [comment]
is this broken in v4 I am unable to inspect inside the iframe

**Comment by ndelangen** [comment]
Yeah I've added it as suggested there and was able to select it in the devtools 🍰

**Comment by ndelangen** [comment]
I'll add it in a PR I'm working on!

**Comment by nelsonomuto** [comment]
thanks @ndelangen, may you link it here when ready so we know when and where it is fixed?

**Comment by nelsonomuto** [comment]
@ndelangen  the issue I am facing is with info @storybook/react v4.0.0-alpha.12

**Comment by nickmccurdy** [comment]
This is no longer working for me in Storybook 4.0.0 and 4.0.2, despite the fix. Any ideas?

**Comment by nickmccurdy** [comment]
I made a new issue for the inspector, the actual elements panel in devtools works fine: https://github.com/storybooks/storybook/issues/4769
