### ISSUE TITLE
Code folding in logger [UX]

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#108]
We can use react-codemirror or ace editor to enable code folding in the logger so that the logged object doesn't take the whole space just like you get in the console. If you want to see it, you can open it. We can keep that in read only mode. We can also have syntax highlighting this way.

For a lightweight solution we can use [JSONView](https://github.com/yesmeck/jquery-jsonview) or [this](https://lapple.github.io/react-json-inspector/)

**Comment by arunoda** [comment]
Codemirror or ACE is too big for that. I don't like complete folding. But, something like in the chrome's console looks great. 

See:

![screen shot 2016-04-13 at 4 00 36 pm](https://cloud.githubusercontent.com/assets/50838/14490542/0786af52-0191-11e6-955b-df7db98339d2.png)

**Comment by arunoda** [comment]
This is implemented with #111 and released as `v1.13.0`.
