### ISSUE TITLE
Allow to create a production build

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#11]
Right now, we need to run storybook locally via something like `npm run storybook`. But, it'd be great, if we can build the final HTML and share it anywhere.

So it'll be something like `npm run storybook-build`.

Then it'll create a directory in your project and you can upload those HTML file to anywhere you want and share your stories.

**Comment by mnmtanish** [comment]
Almost done just need to cleanup the code a bit.

**Comment by mnmtanish** [comment]
I have a working version [here](https://github.com/kadirahq/react-storybook/pull/88). I'm not that familiar with webpack so someone should take a look.

**Comment by arunoda** [comment]
This is implemented.

**Comment by adyz** [comment]
I found this issue looking for documentation, if this is implemented, can anybody post a link to the documentation? Thank you!

**Comment by crashuniverse** [comment]
@adyz: `npm build storybook`.
Source: https://github.com/storybooks/storybook/pull/88/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R71

**Comment by crashuniverse** [comment]
@adyz https://storybook.js.org/basics/exporting-storybook/

```
{
  "scripts": {
    "storybook": "build-storybook -c .storybook -o .out"
  }
}
```
