### ISSUE TITLE
Action logger breaks stateful components

### ISSUE THREAD

**Issue by willdady** [kadirahq/react-storybook#116]
I've just started using storybook and so far it's been great. I've ran into the following issue. Basically if I have a component which maintains it's own internal state the action logger causes the component to be re-rendered when called, effectively creating the component anew.

The following breaks the component by re-rendering the component...
```
storiesOf('ColorPicker', module)
  .add('default', () => (
    <ColorPicker onChange={action('onChange')} />
  ));
```
...but the following does not.
```
storiesOf('ColorPicker', module)
  .add('default', () => (
    <ColorPicker onChange={(color) => console.log(color)} />
  ));
```

Is this the expected behaviour? Should calling action() really cause a re-render?

**Comment by arunoda** [comment]
I can see what's going on here. We should not render in that case.

**Note:**
Find out a way to stop rendering preview iframe if there's no related data change.

**Comment by necolas** [comment]
That sounds good! The re-render also causes assets like images to flash every time an action is taken as the whole story gets re-rendered.

**Comment by arunoda** [comment]
Actually, I find out a simple way to fix this.
Here's the line we need to focus: https://github.com/kadirahq/react-storybook/blob/master/src/client/ui/preview.js#L22

We can check for equality of both `selectedKind` and `selectedStory` and proceed if only at least one of them has changed.

**Comment by arunoda** [comment]
Guys, now we've a fix for this with PR #126.
Try this version: `v1.16.0`

**Comment by de-monkeyz** [comment]
I'm not sure if I'm doing anything wrong (just picked up storybook, loving it). But it seems like I still get this error if I'm passing the event object from a form submit, rather than a click. More specifically the Storage quote error. Any ideas? I'm assuming that React is sending a different event type that isn't handled.

**Comment by willdady** [comment]
This update seems to have fixed my original issue above. Thanks.

**Comment by arunoda** [comment]
@willdady great.
@de-monkeyz could you submit a new issue.

This is the reason of the event object. I assume you are not getting a standard React event.

**Comment by arunoda** [comment]
Note: @de-monkeyz mentioned issue fixed by his PR: #132

**Comment by kevinSuttle** [comment]
I came here confused as to how to exec JS in the actions call. I'd rather just call a function on the component that sends data to the action logger. 

```jsx
 <ColorPicker onChange={action('state changed', this.state.colorValue)} />
```

**Comment by iwarner** [comment]
handleEntry: () => action('entry-change')
