### ISSUE TITLE
Does this work when components depend on meteor packages?

### ISSUE THREAD

**Issue by gsabran** [kadirahq/react-storybook#117]
Hi! Project looks amazing. I've followed the read me and things fail with `Error: Cannot find module "meteor/react-meteor-data"` Is that because meteor package in not a traditional npm package?

I know I'd better not mix the UI component and the container, but they sometime happen to be in the same file

**Comment by gsabran** [comment]
Also happening with `meteor/kadira:flow-router`. It seems to be related to how meteor handles its packages

**Comment by arunoda** [comment]
We simply can't use them. One possible way to pass everything via props. 
Or use webpack's resolve.alias feature to map a mock modules for Meteor packages. 
( You can configure it with our custom webpack config )

**Comment by gsabran** [comment]
Ok I'll try the webpack config way (I'm getting started with it, might take some time!)
What do you think of mentioning this important caveat in the main readMe? It sounds like this project is not only aimed at Meteor apps, but for those it'd be very good to know about that.

**Comment by ffxsam** [comment]
@gsabran What did you wind up doing? I'm just now getting into React Storybook, and running into the same issue of it choking on meteor packages.

It also doesn't like absolute path imports, e.g.:

    import '/imports/something/file';

Any suggestions, @arunoda?

**Comment by gsabran** [comment]
I've ended up separating more clearly containers that were using `react-meteor-data` and UI components, so now I can use storybook with the UI component that have no dependency on Meteor packages. Better separation is good, but it's annoying not to be able to use Meteor packages from a Meteor app... There is also https://github.com/meteor/chromatic that seems to address a similar goal with a focus on Meteor, but I've not used it too much yet.

**Comment by ffxsam** [comment]
I can't get clear enough separation on all my components. For instance, one React component uses a component called `MeteorUser` which takes a user ID and returns various information (which of course, comes from `Meteor.user()`).

Chromatic looks promising, but development on it has lagged while MDG focuses on Apollo. I'm interested to see how it progresses though.

**Comment by arunoda** [comment]
@ffxsam you don't have seperation between the data layer and the UI layer. That's the issue. 

Meteor.user() is a data later stuff and you shouldn't access it inside a UI component. 

Instead, pass it via props. Use container pattern may be with react-komposer or similar.

**Comment by ffxsam** [comment]
But the problem is that my container I want to import into Storybook uses a component which is a container for something else. In other words:

    ComponentIWantToUseInStorybook -> SomeComponentContainer -> SomeComponent

**Comment by ffxsam** [comment]
Seems like Storybook needs some way to mock components, so when it tries to import `SomeComponentContainer` which references Meteor stuff, I can supply my own dummy stand-in component.

**Comment by arunoda** [comment]
@ffxsam Yep. I get it. For that, you need some help from the container toolkit. 
In react-komposer we have this: https://github.com/kadirahq/react-komposer#disable-functionality

**Comment by ffxsam** [comment]
Ahh. Unfortunately I'm not using komposer in my project, it's all MDG's `createContainer`. I'll have to find another workaround.

**Comment by arunoda** [comment]
It will be simple too.
We don't also import meteor packages. You may could give a mock API for the createContainer using the Webpack alias config. 

Or otherwise, use react-komposer just for that compoenet. Both do the same job.

**Comment by ffxsam** [comment]
Webpack... argh. I guess I need to finally give in, and learn it. :)

Thanks!

**Comment by ffxsam** [comment]
@arunoda Oh, one last thing: React Storybook doesn't like when it imports components of mine that use root level imports (`import X from '/some/path'`). I tried adding [babel-root-slash-import](https://www.npmjs.com/package/babel-root-slash-import) to my project but it didn't help.

**Comment by gsabran** [comment]
@arunoda would you have an example of a webpack config with `resolve.alias` that would work? I've:

```js
// /webpack.config.js

module.exports = {
  resolve: {
    alias: {
      'meteor/mongo': '/node_modules/react',
    },
  },
};

```

(I really don't care how the module is going to be resolved, I just want my file loading to work)

This doesn't prevent storybook's building to fail with `Module not found: Error: Cannot resolve module 'meteor/mongo'`.
Also, is it possible to have a config that's only for storybook?

**Comment by gsabran** [comment]
@ffxsam I'm in the process of doing the following:
- passing all the meteor packages [through context](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit/blob/master/src/TodoApp/client/layout/components/Layout.jsx#L16-L18) from the root so that no component import them directly
- using a wrapper [boilerplate](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit/blob/master/src/TodoApp/client/lib/exposeContext.jsx) to [expose](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit/blob/master/src/TodoApp/client/feed/containers/TodoItemContainer.js#L46-L48) the context to the components
- for storybook, [mocking](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit/blob/master/.storybook/FakeContext.jsx) the Meteor packages I need to pass

You can have an idea of how that would looks like in [this work in progress](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit).

**Comment by arunoda** [comment]
@gsabran I made some related comments at here - https://github.com/kadirahq/react-storybook/issues/224#issuecomment-225491154
