### ISSUE TITLE
File search shortcut

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#121]
Instead of having a search box in left, won't it be better to have a search box that pops up on hitting `cmd+P` with the fuzzy search? I think developers are more used to it.

**Comment by arunoda** [comment]
Yes. That's very cool too. Also, I'll like to have a ctrl + F to render the whole preview in the browser as well.

Related: https://github.com/kadirahq/react-storybook/issues/59

**Comment by ritz078** [comment]
I can work on these.

**Comment by arunoda** [comment]
Ah awesome.
We also discussed a bit on this. We may have to deal with some issues here.

For an example, when we are in focus inside the iframe, our keyboard shortcuts may not work. So, we may need to track short cuts on the iframe as well send them back to the admin page to do the actual effect.

**Comment by ritz078** [comment]
As far as the iframe is served from the same domain `postMessage` can be used.

**Comment by arunoda** [comment]
We don't need to use postMessage, we already have a communication channel.
See: https://github.com/kadirahq/react-storybook/blob/master/src/client/synced_store.js

It's a matter of pushing data to above synced_store.

**Comment by ritz078** [comment]
Cool. I will look into that then.

**Comment by ritz078** [comment]
Can we finalize on the key bindings for : 
* opening search box (not Cmd+P as it has a default behaviour of Print. Don't want to override expected behaviours)
* toggling action_logger
* toggling controls
* toggle full-screen preview.

**Comment by arunoda** [comment]
@ritz078 I really can't look come up with something straight. Do we need to use (CMD), how about using SHIFT?
