### ISSUE TITLE
How can I install storybook via npm?

### ISSUE THREAD

**Issue by yhjor1212** [kadirahq/react-storybook#122]
Here is the error message:

`npm i --save-dev @kadira/storybook
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/nvm/0.30.1/versions/node/v5.9.1/bin/node" "/usr/local/opt/nvm/versions/node/v5.9.1/bin/npm" "i" "--save-dev" "@kadira/storybook"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code E403

npm ERR! unregistered users are not allowed to access package @kadira/storybook : @kadira/storybook
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<user>/projects/<project>/npm-debug.log`

What doesn't this repo to be published to a better named repo, say 'react-storybook'?

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/react-storybook/blob/master/docs/known_issues.md#npm-404-error

May be you are using an NPM proxy.

**Comment by yhjor1212** [comment]
It has been fixed now. Thank you.

**Comment by arunoda** [comment]
@yhjor1212 Could you update on how you get it fixed?

**Comment by yhjor1212** [comment]
I just disabled the registry and reinstall again. After the installation I enabled it again.

**Comment by arunoda** [comment]
Ah got it.
Thanks.

**Comment by yahu577** [comment]
The solution is to set a registry for modules of specific scope. You can add the following to your project's .npmrc file
```
@kadira:registry=http://registry.npm.org
```
