### ISSUE TITLE
onSubmit stripped for Forms

### ISSUE THREAD

**Issue by winkerVSbecks** [kadirahq/react-storybook#128]
Trying to test a button that allows form submissions:

```js
import React from 'react';
import { storiesOf, action } from '@kadira/storybook';
import Button from '../button';

storiesOf('Button', module)
  .add('submit for a form', () => (
    <div className="p4 center">
      <form
        onSubmit={ () => action('form submitted') }>
        <Button type="submit">Submit</Button>
      </form>
    </div>
  ));
```

It seems that `onSubmit` gets stripped when it loads in React Storybook. I've tried different combinations: wrapping it with a div, making it the root component, using a custom `Form` component, etc. In all cases the `onSubmit` is stripped out. Any idea what I'm doing wrong? Or are forms not supported by React Storybook?

**Comment by de-monkeyz** [comment]
You need to pass in just the call to action() not a function that calls it:

`<form onSubmit={action('form submitted')}>`

This doesn't prevent the default action on the form though, so the iFrame will reload

**Comment by winkerVSbecks** [comment]
I see, thanks for explaining that.

**Comment by hmontes** [comment]
I found a better way.

```
onSubmit={ e => { e.preventDefault(); action('form submitted')(e); }}>
```

So. We need a better action with a e.preventDefault integrated.

**Comment by Hypnosphi** [comment]
@hmontes You just inlined a variable, why do you think it's better?

**Comment by hmontes** [comment]
@Hypnosphi Because if i have several buttons in a component (example. A modal with a Close button and a send form button) i can use different actions (action('Modal closed'), action('Submitted Form').

**Comment by Hypnosphi** [comment]
But you only need preventing default on form submit button

**Comment by hmontes** [comment]
Yes. Because "action" don't have a natural way to do that. (I spend hours to find a way to prevent default an event in storybook)

**Comment by Hypnosphi** [comment]
If you have several forms, you may want to create a function like this:

```
const withPreventDefault = handler => e => {
  e.preventDefault();
  handler(e);
}
```

And use it like that:
```
onSubmit={ withPreventDefault(action('form submitted')) }
```

**Comment by hmontes** [comment]
Yeah. But that function is INSIDE the component.

The solution is for the Story. If you have a presentational component and a container you want to disable the action OUTSIDE the presentational component (And in this case. In the history) because the presentational components not are classes.

**Comment by Hypnosphi** [comment]
Sorry, but I don't get what you're talking about. Please provide an examle

**Comment by plummer-flex** [comment]
It seems I'm late to the party, but this is still a problem.  

```
            <form
              onSubmit={(e) => {
                e.preventDefault();
                action('form submitted')(e);
              }}
            >
              <input type="text" />
              <Button type="submit">Submit Button</Button>
            </form>
```

We're not relegating the form submission to the `onSubmit` event on the form node, and not the `onClick` event on the Button.  If the code doesn't use `e.preventDefault()`, the iframe then forwards off to the root iframe and borks the Storybook frame.  It would be better for the `action` to prevent default.

**Comment by Hypnosphi** [comment]
@plummer-flex Feel free to add this to your codebase

```
import {action} from '@storybook/addon-actions`

export const actionWithPreventDefault = name => e => {
  e.preventDefault();
  action(name)(e);
}
```

**Comment by plummer-flex** [comment]
@Hypnosphi I get the adding another wrapper function so as to not use an inline function, but what's the case for not modifying `action` to handle this on it's own?

**Comment by Hypnosphi** [comment]
Because increasing api surface for each possible usecase is impractical

**Comment by njcaballero** [comment]
> import {action} from '@storybook/addon-actions`
> 
> export const actionWithPreventDefault = name => e => {
>   e.preventDefault();
>   action(name)(e);
> }

Now that @storybook/addon-actions is part of the essentials, I'm not able to import action anymore (even though it is installed as a dependency already). I checked the new action page here: https://storybook.js.org/docs/react/essentials/actions and looks like this is now handled differently. I was able to add an event for a button click, but still can't find how to prevent default for an onSubmit event using the new way.

Using Storybook  v6.1.5

**Comment by shilman** [comment]
@njcaballero all the 6.x changes should be backwards compatible, i.e. `action(x)(e)` should still work. if you're getting a warning about package dependencies you can just install `addon-actions` as a dev dependency to your project. it won't affect essentials.

if you want to use the "new way" of doing things where `onX` is automatically filled in via args, it would look something like this (react example)

```js
const withPreventDefault = (action) => e => {
  e.preventDefault();
  return action(e);
};

const Template = ({ onClick, ...rest }) => (
  <MyComponent onClick={withPreventDefault(onClick)} {...rest} />
)
```

**Comment by njcaballero** [comment]
@shilman That worked for me. Thanks!

**Comment by vdpdev** [comment]
@Hypnosphi I'm just wondering where have you found this solutions? I was researching docs/issues/googling and I haven't found any mentioning how to make Actions add-on and Storyshots add-on works together without breaking functionality one of them. This `action` function saved me. Thank you!

**Comment by Hypnosphi** [comment]
Here: https://github.com/storybookjs/storybook/blob/next/addons/actions/ADVANCED.md

**Comment by vdpdev** [comment]
Well, i've seen this link but never went there since it's marked as 'legacy usage'. My suspicious for docs should be increased. Thanks anyway=)

**Comment by Hypnosphi** [comment]
> it's marked as 'legacy usage'

Back in 2017 it wasn't
