### ISSUE TITLE
Documentation for static site generation 

### ISSUE THREAD

**Issue by borisyankov** [kadirahq/react-storybook#135]
It seems you guys added the static site generation functionality already. Great!
There is no documentation though, and looking through the commit history and source code does not make it clear to how to use it.

**Comment by arunoda** [comment]
It's here: https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#static-builder

May be wanna change some keywords.

**Comment by borisyankov** [comment]
Great. I would suggest linking to this document's main points from within the README.
