### ISSUE TITLE
No way to prevent .babelrc use

### ISSUE THREAD

**Issue by sethkinast** [kadirahq/react-storybook#138]
I have an isomorphic app that runs using Node (without Webpack) on the server, and bundles with Webpack for the client.

So, I turn off .babelrc in my Webpack config:

```
        {
          loader: 'babel',
          query: {
            babelrc: false,
            presets: ["es2015-webpack", "stage-1", "react"]
          }
        },
```

There doesn't seem to be a good way to hook into storybook and make it ignore the .babelrc, so it tries to run my Node-specific Babel plugins and bombs out.

**Comment by arunoda** [comment]
Okay. We load babelrc manually. May be should allow and option to prevent it.
Here's the potential place for that.
See: https://github.com/kadirahq/react-storybook/blob/master/src/server/config.js#L16

**Comment by sethkinast** [comment]
Yep, I saw the PR and issue. I may have too special of a case :)

It would be nice if I could put a `.babelrc` in the `.storybook` directory,
and you look there first. That would give me a chance to override it (and
would fix #139) at the same time.

Would you accept a PR that looked for a .babelrc in two places? (First
config, then app root)?

On Fri, Apr 22, 2016 at 3:54 AM, Arunoda Susiripala <
notifications@github.com> wrote:

> Okay. We load babelrc manually. May be should allow and option to prevent
> it.
> Here's the potential place for that.
> See:
> https://github.com/kadirahq/react-storybook/blob/master/src/server/config.js#L16
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kadirahq/react-storybook/issues/138#issuecomment-213377417>
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by arunoda** [comment]
Yes. That's a good idea.

**Comment by sethkinast** [comment]
OK, I will work on that this weekend.

My team loves using storybook for development-- building components is
effortless.

**Comment by arunoda** [comment]
Super.
