### ISSUE TITLE
Server sets NODE_ENV=production

### ISSUE THREAD

**Issue by sethkinast** [kadirahq/react-storybook#139]
In `server/index.js`, `process.env.NODE_ENV` is forcefully set to production. This causes my app to try to load production plugins from .babelrc, even though I am trying to run in development mode.

**Comment by arunoda** [comment]
On the other hand, we wanted to prevent running some of the dev only packages from here. May be we need to think about this again.

But for your case, I suggest to use two different directories for the server and client. Then I hope it can be fixed easily.

**Comment by sethkinast** [comment]
Closed by #149

**Comment by joeruello** [comment]
Would there be a way to allow things like PropTypes to work? I just developed a new app 100% in storybook and then got bombarded with a bunch of warnings when I fired it up with webpack-dev-server.

**Comment by arunoda** [comment]
@joeruello Could you submit a new issue with more information.
We are happy to discuss.
