### ISSUE TITLE
Specific Webpack Loader is Required for React?

### ISSUE THREAD

**Issue by adrianmc** [kadirahq/react-storybook#14]
I'm trying to use storybook for an existing component in my Mantra app. The `ChatInput.jsx` component has two import statements at the top for React and the PureRenderMixin. I had assumed that storybook would work out of the box with Mantra apps. Do I need to do some webpack configuration in order to load my component?

This is the error I get from the storybook GUI:
```
My First Button
ERROR in ./client/modules/chat/components/ChatInput.jsx
Module parse failed: /Users/adrianmc/dev/olis-mantra/client/modules/chat/components/ChatInput.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from 'react';
| import PureRenderMixin from 'react-addons-pure-render-mixin';
| 
 @ ./.stories/chatInput.js 9:17-75
```

This is the story file:
```jsx
import React from 'react';
import { storiesOf, action } from '@kadira/storybook';

import ChatInput from '../client/modules/chat/components/ChatInput.jsx';

storiesOf('ChatInput', module)
  .add('simple', () => (
    <ChatInput />
  ));

```

**Comment by arunoda** [comment]
Just rename you module to `ChatInput.js` and it'll work.

**Comment by adrianmc** [comment]
@arunoda Thanks! You may close this.

**Comment by arunoda** [comment]
Great.

**Comment by kevinSuttle** [comment]
Seeing the same issue locally, but not using a .jsx file extension. 

I used the guide and gist from here: https://getstorybook.io/docs/addons/writing-addons

**Comment by kevinSuttle** [comment]
There seems to be a lot of info missing from the docs, like adding babel etc, and specifying a dist folder.

https://github.com/kadirahq/storybook-addon-notes/blob/master/register.js

**Comment by kevinSuttle** [comment]
I have a working implementation here: https://cloudup.com/cwK7EtZCpaw
