### ISSUE TITLE
README: Where are the example components?

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#140]
<img width="260" alt="screen shot 2016-04-22 at 1 38 05 pm" src="https://cloud.githubusercontent.com/assets/95672/14749786/796b91e6-088f-11e6-8161-ebcd51c7471d.png">

**Comment by arunoda** [comment]
You mean this one? 
https://github.com/kadira-samples/react-storybook-demo

**Comment by kevinSuttle** [comment]
![long day](http://i2.kym-cdn.com/entries/icons/original/000/000/554/facepalm.jpg)
