### ISSUE TITLE
not working in Firefox

### ISSUE THREAD

**Issue by UYEONG** [kadirahq/react-storybook#143]
`ReferenceError: identity is not defined`

![2016-04-25 2 32 06](https://cloud.githubusercontent.com/assets/1321707/14774576/8d2c19d4-0af2-11e6-82bd-4bfcae8fbbd1.png)

Version is 45.0.2

**Comment by mnmtanish** [comment]
Hi @UYEONG 

I'm also getting the same error.

**NOTE**:
It works fine with the static build so most probably this must be an HMR issue.

<img width="1072" alt="screen shot 2016-04-25 at 11 37 35 am" src="https://cloud.githubusercontent.com/assets/136691/14775215/fac580f6-0ada-11e6-8c98-d8dac3f8187a.png">

**Comment by mnmtanish** [comment]
https://github.com/kadirahq/react-storybook/pull/144 fixes this error

**Comment by mnmtanish** [comment]
Hi @UYEONG 
Just released a new version `v1.17.2` with the fix.
Thanks for reporting

**Comment by mquandalle** [comment]
I also encountered this error and I didn’t understand it was specific to Firefox and I thought Storybook was just plain broken. This is a pretty bad first experience, do you have any plan to configure a CI tool run the tests in the different major browsers?

**Comment by mnmtanish** [comment]
Yes I agree. Thanks for checking it out again. We're going to refactor the storybook to use Mantra. We'll setup a good CI for cross browser tests as soon as it's done.

**Comment by arunoda** [comment]
Closing this since we've fixed this.
