### ISSUE TITLE
Displaying docs inside the storybook

### ISSUE THREAD

**Issue by sakulstra** [kadirahq/react-storybook#150]
At the moment the only way to display docs is the use of:
```
storiesOf('Main story', module)
  .add('some configuation, () => (
    <SomeComponent />
  )).(...)
```
This is insufficient for most our components...

In our use case it would be nice if we:
1. could add some more description (like an optional description tag for the story)
```
storiesOf('Main story', module, 'This component can be used to ... and has the following params ...')
  .add('some configuation, () => (
    <SomeComponent />
  )).(...)
```
2. or even better somehow reads the jsdocs in the js files and displays them above the component examples:
```
/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
```
I think this is somehow related to #56 but not quite the same.

Regards,
Lukas

**Comment by arunoda** [comment]
Yeah. This is great.
If we need the file system manually, that'll be bit harder and over complicated.
But, I think pushing this with the story makes sense.

We are also looking something for this with notes. Basically, with that we have another Tab on the bottom called "Notes".

**Comment by kevinSuttle** [comment]
I'd prefer a .md file in the component folder, rendered below or beside.

**Comment by kevinSuttle** [comment]
Not sure if this should be another request, but showing a snippet of the code used to implement the component would be handy.

**Comment by mnmtanish** [comment]
Fixed with this [addon](https://github.com/kadirahq/react-storybook-addon-info)

**Comment by vladanyes** [comment]
storiesOf('elements/Button', module)
  .addDecorator(withInfo)
  .addDecorator(story => (
    <div style={{ paddingLeft: 10 }}>
      <h5>Завершающие кнопки (большие) в карточках позиций и всплывающих окнах</h5>
      {story()}
    </div>
  ))
  .add('Завершающие кнопки(большие)', () => (
    <Button theme="blue" position="complete" onClick={action('onClick')}>
      Добавить продукт
    </Button>
  ));
