### ISSUE TITLE
NODE_ENV=production silences developer warnings.

### ISSUE THREAD

**Issue by joeruello** [kadirahq/react-storybook#158]
Following on from #139, developing in React Storybook has been awesome! I've been working completely inside it for a few days, when it came time to test it outside Storybook I was assaulted by a bunch of PropTypes warnings.

I'm assuming this is because NODE_ENV is force set to production. It would be nice to be able to see these warnings when developing inside Storybook.

**Comment by arunoda** [comment]
Yes true.
We are using NODE_ENV=production for a kind of hack. I think we could remove it.
Will do it.

**Comment by arunoda** [comment]
Try the latest version. (v1.24.0).
It has a fix for this.
