### ISSUE TITLE
Request: Deep link to specific stories and substories

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#159]
`http://localhost:9001/stories/Button/SubmitButton` or something

**Comment by arunoda** [comment]
Duplicate:  https://github.com/kadirahq/react-storybook/issues/6

Currently this is implemented in the `mantra` branch and we could release it today or tomorrow.

**Comment by kevinSuttle** [comment]
Nice! Thanks @arunoda!
