### ISSUE TITLE
How to add a <script> tag?

### ISSUE THREAD

**Issue by moroshko** [kadirahq/react-storybook#163]
[react-prism](https://github.com/tomchentw/react-prism#usage) recommends to add a script tag directly in the HTML:
```html
<script src="path/to/your/prism.js" ></script>
```
Is there a way to do this?

**Comment by jeef3** [comment]
Yes, there is, but I don't think there's any docs on it yet. See #77.

Basically, create a `head.html` in your `.storybook`. That will get included.

**Comment by moroshko** [comment]
Thanks!

**Comment by helloncanella** [comment]
updating the answer: add a `preview-head.html` to the folder `.storybook`.

**Comment by ericclemmons** [comment]
There doesn't seem to be a way to do this for local dependencies. What's the best way to get these into stories & the build output?


```html
<script nomodule src="/dist/my-custom-script.js"></script>
```


> Error: ENOENT: no such file or directory, stat '.../my-project/node_modules/@storybook/core/dist/public/dist/my-custom-script.js'

**Comment by rdhainaut** [comment]
You can find the doc on the official website at this address: https://storybook.js.org/docs/configurations/add-custom-head-tags/

**Comment by onderceylan** [comment]
Local dependencies can be copied over to the dist via the webpack copy plugin. This is how I loaded my local dependency;

**main.js**

```javascript
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  stories: ['../src/**/*.stories.ts'],
  webpackFinal: config => {
    config.plugins.push(
      new CopyPlugin({
        patterns: [{ from: './node_modules/@myorg/my-local-dep/dist', to: './my-local-dep-dist/' }],
      })
    );
    return config;
  },
};
```

**preview-head.html**
```html
<script async type="module" src="/my-local-dep-dist/my-script.esm.js"></script>
```

**Comment by James-Wilkinson-git** [comment]
Looking for a way to do this per story, not for all stories.
