### ISSUE TITLE
How to disable minification when running `build-storybook`?

### ISSUE THREAD

**Issue by moroshko** [kadirahq/react-storybook#164]
Is there a way not to minify the JS files when running `build-storybook`?

**Comment by arunoda** [comment]
Currently there is no way. You need to change the webpack config and remove uglifyjs plugin.
You can try this: #160

**Comment by moroshko** [comment]
@arunoda Isn't #60 allowing extending only *webpack.config.js* but not *webpack.config.prod.js*?

**Comment by arunoda** [comment]
Okay. It's the production build. So, we need to support the production build too.
@mnmtanish could you find some way to add production webpack conf support to #160 as well.

**Comment by mnmtanish** [comment]
@moroshko @arunoda both use the [config.js](https://github.com/timkindberg/react-storybook/blob/d7c8c424ff9cca200ce5a86aa0994118b3248247/src/server/build.js) file to build the config so it should work out of the box. I'll check it out.

**Comment by moroshko** [comment]
@mnmtanish As far as I can see, [custom config is hardcoded to `webpack.config.js`](https://github.com/kadirahq/react-storybook/blob/master/src/server/config.js#L63), so we never check if a custom `webpack.config.prod.js` exists.

**Comment by arunoda** [comment]
@moroshko I checked the code, yes it'll work for both alike.

**Comment by mnmtanish** [comment]
@moroshko I also though at first that having 2 files will be easy and straightforward but it can cause some issues.

So far we're using custom config from **webpack.config.js** for both the dev-server and the production builds. If we use separate files, users who need the same custom config for both will have to make a copy of the file. Let's say we try to fix it by falling back to **webpack.config.js** if **webpack.config.prod.js** does not exist, it makes the config more ambiguous and some users may not want that to happen.

We can fix this for now by adding a **configType** argument to the config function. I've opened a pull request for this https://github.com/kadirahq/react-storybook/pull/169

**Comment by moroshko** [comment]
@mnmtanish Thanks for #169. I'd just update the docs to reflect the changes.

**Comment by arunoda** [comment]
@moroshko Where did you update the docs?

**Comment by moroshko** [comment]
@arunoda I didn't. I suggested @mnmtanish to update the docs as part of #169.

**Comment by arunoda** [comment]
@moroshko Ah okay. BTW: I did it.

**Comment by moroshko** [comment]
Thanks @arunoda

**Comment by mycarrysun** [comment]
@arunoda sorry to reopen such an old thread but the docs aren't clear on what you need to do to set it to `DEVELOPMENT`

Can you show an example of how one might set that variable and return it with the config?
