### ISSUE TITLE
1.20.0 Babel issue

### ISSUE THREAD

**Issue by cjcheshire** [kadirahq/react-storybook#167]
I'm running the usual the npm storybook task setup in my package json but getting the following:

```
React Storybook started on => http://localhost:9001/

webpack built bcc7635039da3b503b29 in 502ms
Hash: bcc7635039da3b503b29
Version: webpack 1.13.0
Time: 502ms
            Asset    Size  Chunks             Chunk Names
preview.bundle.js  208 kB       0  [emitted]  preview
manager.bundle.js  621 kB       1  [emitted]  manager
chunk    {0} preview.bundle.js (preview) 73.1 kB [rendered]
    [0] multi preview 40 bytes {0} [built] [1 error]
    [1] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
    [3] ./~/ansi-html/index.js 4.02 kB {0} [built]
    [4] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [5] ./~/html-entities/index.js 231 bytes {0} [built]
    [6] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
    [7] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
    [8] (webpack)-hot-middleware/client-overlay.js 1.73 kB {0} [built]
    [9] (webpack)-hot-middleware/client.js 4.18 kB {0} [built]
   [10] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
   [11] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
   [12] (webpack)/buildin/module.js 251 bytes {0} [built]
chunk    {1} manager.bundle.js (manager) 251 kB [rendered]
    [0] multi manager 28 bytes {1} [built]
    [2] ./~/@kadira/storybook/dist/manager.js 251 kB {1} [built]

ERROR in multi preview
Module not found: Error: Cannot resolve module 'babel' in /Users/ccheshire/Development/career-profile/app-job-application
 @ multi preview

```
I'm running node 5.5.0 and npm 3.8.8.

Any thoughts?

**Comment by arunoda** [comment]
Are you using babel inside the module mentioned above? If not can we have a sample repo to debug this issue?

**Comment by MechJosh0** [comment]
@cjcheshire Do you also happen to have this in the console log?
`Uncaught Error: Cannot find module "E:\projectPath\.storybook\config.js"`

I've resolved this by installing storybook `1.1.0` and installing each version until `1.19.0`. This resolved the problem for me.

Something along the way I assume has been dropped from the dependencies but is still relying on it. Installing each version as you go will install the missing dependency, I'm unsure which one it is. I did try both `1.20.0` and `1.21.0` versions but they weren't working, even with installing each version.

@arunoda FYI, see above. This can be reproduced by installing a fresh copy of https://github.com/mantrajs/mantra-sample-blog-app and resolved by following the above steps.

The Mantra sample app was broken but resolved with the steps. Tested on both Ubuntu `{ npm: '3.8.5', node: '4.2.6'}` and Windows `{ npm: '3.8.9', node: '4.4.0'}`

**Comment by arunoda** [comment]
Guys, yep this is an issue if the project does not have some babel packages installed by default. Most of the node project have it, but projects like Meteor won't have them.

So, I fixed this with `v1.22.1`. Give it a try.

**Comment by MechJosh0** [comment]
I can confirm it's working, thanks. While I was there I figured to make a pull request for the Mantra sample app to mainly to update the Meteor version.

https://github.com/mantrajs/mantra-sample-blog-app/pull/105

**Comment by arunoda** [comment]
Okay. seems like we can close this issue.

**Comment by cjcheshire** [comment]
My severe apologies.  It's all good to close.  Thank you for you help.
