### ISSUE TITLE
build-storybook - CMD icon breaks in UI

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#168]
<img width="250" alt="screen shot 2016-05-05 at 2 18 50 pm" src="https://cloud.githubusercontent.com/assets/95672/15052607/78ecb014-12cc-11e6-9362-91be59299ebf.png">

**Comment by arunoda** [comment]
Oops. What's this OS?

**Comment by arunoda** [comment]
@thinkholic Could you add a SVG icon to this button?

**Comment by kevinSuttle** [comment]
OSX 10.4, Chrome stable. Latest.

**Comment by arunoda** [comment]
@kevinSuttle We released a new version(`v1.21.0`) with a potential fix. Could you check that?

**Comment by kevinSuttle** [comment]
Nope. Unfortunately, no fix. 

<img width="1439" alt="screen shot 2016-05-07 at 1 45 13 pm" src="https://cloud.githubusercontent.com/assets/95672/15093564/036571f2-145a-11e6-84f7-e7aafe95989c.png">

**Comment by arunoda** [comment]
@mnmtanish @thinkholic Could you guys try @kevinSuttle's suggestions. I'm kind a noob in this area.

**Comment by mnmtanish** [comment]
Hi @kevinSuttle 
I think https://github.com/kadirahq/react-storybook/issues/215 is related. Can you try `v1.28.1` I'm sure it will fix the issue.

CC: @arunoda @thinkholic

**Comment by kevinSuttle** [comment]
Woot! Seems fixed! Thanks gents!

**Comment by kevinSuttle** [comment]
<img width="382" alt="screen shot 2016-05-25 at 9 34 20 pm" src="https://cloud.githubusercontent.com/assets/95672/15561111/885773aa-22c0-11e6-8760-343840985343.png">
<img width="266" alt="screen shot 2016-05-25 at 9 34 28 pm" src="https://cloud.githubusercontent.com/assets/95672/15561112/885a7e1a-22c0-11e6-8b26-ad196e3a0f81.png">
