### ISSUE TITLE
Update url

### ISSUE THREAD

**Issue by jamieholliday** [kadirahq/react-storybook#171]
Is it possible to update the url based on the story being viewed? I thought this may have been suggesting that this was maybe an option:
https://github.com/kadirahq/react-storybook/blob/master/docs/how_storybook_works.md#routing
It would be a nice feature if not, so I could refer the designers to a url or maybe even run some sort of visual testing of each different story state

**Comment by MechJosh0** [comment]
This is working for me in `1.22.1`. When I switch to a story it's changing the URL and I'm able to use this URL to land directly on that story.

Example URL for going to **Admin Panel** module on **Page - Home** story: http://localhost:9001/?selectedKind=Admin%20Panel&selectedStory=Page%20-%20Home

**Comment by jamieholliday** [comment]
Sorry my bad. I installed this yesterday but when I checked I had version 1.1.0 somehow. Anyways updated to 1.2.1 and url works correctly
