### ISSUE TITLE
Sidebar stories overflow container

### ISSUE THREAD

**Issue by jamieholliday** [kadirahq/react-storybook#177]
I have a long list of stories which overflow the size of the stories sidebar as no scrollbar is rendered.
I tried following the instructions in the docs to override the component and fix this issue by setting a height to the stories container. https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#customizing-the-ui - but this isn't overriding. I tried finding the layout.js file referenced from that doc but the link is broken
https://raw.githubusercontent.com/kadirahq/react-storybook/master/src/client/ui/layout.js
I'm not sure which file to overing now in this case
<img width="771" alt="screen shot 2016-05-09 at 14 49 34" src="https://cloud.githubusercontent.com/assets/1197747/15115127/63e4225c-15f5-11e6-8c0f-c2c31352f33c.png">

I am running version 1.22.1

**Comment by arunoda** [comment]
Yep. This seems like a bug.
I'll work on it.

**Comment by arunoda** [comment]
Try version 1.24.0 or higher.
It comes with a fix for this.

Reopen, if that's not what you are looking for.

**Comment by jamieholliday** [comment]
This does work. As an improvement I was thinking the filter bar could be always visible at the top and just the stories scroll. I have created a PR with those changes in here:
https://github.com/kadirahq/react-storybook/pull/182
