### ISSUE TITLE
Double Scrollbar in Full Screen Mode

### ISSUE THREAD

**Issue by timkindberg** [kadirahq/react-storybook#179]
I'm getting two scrollbars in full screen mode. It's messing with my media query development, because I'm always off by ~10px.

![double_scrollbar](https://cloud.githubusercontent.com/assets/168046/15125183/8b7ca718-15f9-11e6-9e45-e78a30b5c201.png)

You can hide it by adding `overflow: hidden` to the dev containing the first iframe. See here:

![overflow_hidden](https://cloud.githubusercontent.com/assets/168046/15125240/c6b45c2c-15f9-11e6-82ab-468c6667c4d4.png)

**Comment by arunoda** [comment]
I'll add that.

**Comment by arunoda** [comment]
Try version 1.24.0 or higher.
I applied your suggestion for that.

Hope now we can close this.
