### ISSUE TITLE
Store panel visibility / full screen mode into permalink or local storage

### ISSUE THREAD

**Issue by timkindberg** [kadirahq/react-storybook#180]
I'd love if the panel visible states and the full screen mode were stored in the permalink or local storage. That way when I refresh (sometimes) I don't have to enter full screen mode again (or hide panels again).

**Comment by timkindberg** [comment]
Local storage probably makes more sense, that way if I share a url it will retain the settings on the person's computer, instead of whatever I had set to.

**Comment by arunoda** [comment]
Hmm.
I like putting them in the URL.

> if I share a url it will retain the settings on the person's computer, instead of whatever I had set to.

I'm think this in the other way around :)

**Comment by ritz078** [comment]
A complete isolated view will be great having just the component and nothing else. like full screen but no need of iframe too. This will help while profiling.

**Comment by timkindberg** [comment]
@ritz078 that already exists with Ctrl Shift F

**Comment by timkindberg** [comment]
I've picked up this story! PR coming right now.

**Comment by arunoda** [comment]
Thanks. Will be working on the PR.
