### ISSUE TITLE
Always removes one preset from users .babelrc

### ISSUE THREAD

**Issue by witnessmenow** [kadirahq/react-storybook#183]
Using 1.24.0 I am unable to run storybook, I get parsing errors.

I've looked into and it is removing the last preset from my babelrc file.
This is occurring in the function "removeReactHmre" in server/config.js it was using -1 to splice.

I'll submit a PR now

**Comment by timkindberg** [comment]
I was just about to fix this too :) it's definitely breaking things

**Comment by arunoda** [comment]
A Fix for this is landed in `v1.25.0`.
