### ISSUE TITLE
scripts/webpack.manager.conf.js doesn't run on linux without shebang

### ISSUE THREAD

**Issue by timkindberg** [kadirahq/react-storybook#186]
I'm not sure why but the line below was not running for me during prepublish:

```sh
  ./node_modules/.bin/webpack --config scripts/webpack.manager.conf.js
```

After adding `#!/bin/bash` to the top of the file it fixes it.

I'll submit a PR.

**Comment by arunoda** [comment]
A Fix for this is landed in `v1.25.0`.
