### ISSUE TITLE
Please push v1.4.0 of react-split-pane

### ISSUE THREAD

**Issue by timkindberg** [kadirahq/react-storybook#189]
You have published v1.4.0 of **react-split-pane** but you haven't pushed it to github. We have to publish vendor libs to a private npm registry so I need to clone it and publish it myself but its not up there.

I would log an issue over there but issues tab is not enabled.

**Comment by arunoda** [comment]
Okay. Will do it.
It's in my office workbox.
I'm on leave for 2 days. Anyway, I'll try to push it.

**Comment by arunoda** [comment]
@timkindberg Okay pushed.
