### ISSUE TITLE
Get some features from ClojureScript devcards

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#19]
See: https://github.com/bhauman/devcards

Clojurescript devcards is a very similar project but they have implemented some cool features which reminds me iPython notebooks.

It has a concept of card (which is similar to story in our case). Unlike in our case, we can render not only React elements, but markdown and tests as cards.
See: https://vimeo.com/97078905

Which is very useful for creating self describing documentations.

### What we can get from Devcards

It's unwise if we just clone all the features of devcards. But we can inspire from it. Here are some of the things we can do.

* Allow to add a markdown description for each story. (Technically, there can be stories with just the markdown)
* We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.
* We shouldn't write test cases inside stories, but we should run tests and watch them. If any of the test failed, we can report it inside the storybook. (May be a red alert and show logs)

**Comment by sammkj** [comment]
One of other things that I'm working on to add for my team is markdown description. Perhaps I can send another PR on that?

I don't quite understand point #2. Mind to elaborate more?

**Comment by glenjamin** [comment]
> We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.

That's a great idea!

**Comment by arunoda** [comment]
@sammkj yes please :+1: 

> We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.

Basically, with this we are just reading propTypes for a given component class and just list them. It's kind of a documentation for a component.

@glenjamin Thanks.

**Comment by chrislloyd** [comment]
> We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.

Other than a property name, there's not enough reflective data in Reacts PropTypes to extract that information. Facebook uses (and recommends) static analysis to access that data: https://github.com/facebook/react/issues/4794

**Comment by chrislloyd** [comment]
Also, why do you not recommend writing tests inside of stories?

**Comment by nicksp** [comment]
@arunoda Hi there,

Have some local groundwork for exactly these two features that I'd like to integrate in your tool :)

1. Allow to add a markdown description for each story. (Technically, there can be stories with just the markdown)
1. We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.

How shall i put a note that i started to work on it? And what do you think if i'll develop it?

**Comment by arunoda** [comment]
@nicksp awesome.

> Technically, there can be stories with just the markdown.
Yes. That's what we can start with. Something like this.

```js
import { storiesOf, markdown } from '@kadira/storybook';

storiesOf('Something')
   .add('description', markdown(`
      ## This is the a great component.
      ...
   `));
```

**Comment by nicksp** [comment]
@arunoda How shall i start? I mean do i need to create and issues and mark that i'm working on it or what?

**Comment by arunoda** [comment]
@nicksp just add a note and start working on it. May be just work on a simple task.
Once you done something, just create a PR and link to this issue. 
(PR doesn't need to be complete)

**Comment by nicksp** [comment]
@arunoda Sounds good. Will ad a note right here then, in that specific issue. But since i don't have that much free time unfortunately, it won't be fast development process... just so you know. But i'll do my best. Would really love to pimp that project.

**Comment by arunoda** [comment]
@nicksp No problem. Take your time. If we are working on that, I will let you know.

**Comment by nicksp** [comment]
Started implementation of the following tasks:

- [ ] Allow to add a markdown description for each story. (Technically, there can be stories with just the markdown)
- [ ] We can also show proptypes and what are they for a given React component. It's nice, if we can show them with a story.

**Comment by arunoda** [comment]
@nicksp We discuss a bit about this in our office. So, we thought rather than doing any changes to Storybook core, may be we can use some helper components to achieve these. See some sample code:

```js
import React from 'react';
import { storiesOf, action } from '@kadira/storybook';
import { Button } from '../button';
import { Container, Markdown, PropTable } from '@you/storybook-helpers';

storiesOf('Button', module)
  .add('with a text', () => (
    <Container>
      <Markdown>
        ## Rendering a button

        This is how you can render a button.
      </Markdown>
      <Button>Text name</Button>
      <PropTable component={Button} />
    </Container>
  ));
```

**Comment by jeef3** [comment]
The only catch with something like that, would be if you're still wanting that component resizer (#17) . That resizes the whole `iframe` I think currently?

So you would end up possibly needing another helper to wrap the component (and then only resize that?).

``` jsx
<Container>
  <Markdown>
    ## Rendering a button
    This is how you can render a button.
  </Markdown>
  <Component>
    <Button>Text name</Button>
  </Component>
  <PropTable component={Button} />
</Container>
```

**Comment by arunoda** [comment]
@jeef3 That's a good point.

**Comment by nicksp** [comment]
@arunoda Yep, sounds like a good solution. I like idea of separate components doing its stuff only. So, will implement on my account then, as a separate component which you can you later.

**Comment by arunoda** [comment]
I'm going to close this since we'll be working on some of these features as extensions to react storybook. 
See: https://github.com/kadirahq/react-storybook-story for an example.

We'll be launching an addon API soon.
