### ISSUE TITLE
Embed in existing Express app?

### ISSUE THREAD

**Issue by ericclemmons** [kadirahq/react-storybook#190]
Would this be possible by replicating some of the `server.js`, `iframe.html.js`, & build?

**Comment by arunoda** [comment]
This is a dev time tool. So having a it's own express seems fine to me.
What's the reason behind this decision?

**Comment by ericclemmons** [comment]
@arunoda Our projects have DX baked into it.  `npm start` gives you both the public interface as well as an internal component playground + docs + private tools + dashboard, etc. (If authenticated. Otherwise, you only see the public portal).

We were evaluating using this project instead of our internal playground, which means having it available under <http://localhost:3000/components>.

(We dropped Cosmos as well, because a separate tool/process means it doesn't get used).

**Comment by arunoda** [comment]
@ericclemmons Our idea with storybook is to develop without using the full app. Just the components once.
AFAIK: It works pretty well.

We are also building storybooks.io which allows to keep, comment and discuss storybooks for every commit in your app.

---

Seems like you need to find a way to display your storybook right inside your app. If that's the case, there's a much easy way. Follow this:

* Use our [static builder](https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#static-builder) to build a static version of storybook.
* Then use your express app to serve it in `/components` route.
* You can create an automatic script to build the storybook for everytime you are deploying your app.

**Comment by ericclemmons** [comment]
I think we have slightly different goals, so no fault of this project.

Thanks for the prompt responses. Beautiful project so far!

**Comment by matchu** [comment]
Ahh, I'm sorry to hear this :( I'm working on upgrading our company's custom component development workflow, too. I was hoping that, while I was at it, I could swap out our custom component preview tooling for the React Sandbox UI.

Unfortunately, while the _core_ UI is in its own reusable module, I'd seemingly have to rewrite a bunch of the React and addon support myself. I was hoping that layer of React Sandbox would be decoupled from the server workflow, too, so I could embed it in our prod site and get shareability and extensibility for free. Ah, well; looks like we're better off sticking with our custom thing.

Anyway! I know my requirements are unusual, and I'm glad y'all are focusing your efforts on the primary use case. Thanks for making a cool thing! :)

**Comment by turkus** [comment]
@matchu because I have the same issue like you, you can try to deploy storybook on the same machine as your app, then serve in nginx under specific path storybook and in the storybook create symlink to the folder containing your components. The same with sass (if you use). Then it should work :) I will let you know if it works, because I plan to do the same.
