### ISSUE TITLE
How to work with imports from meteor packages

### ISSUE THREAD

**Issue by jschlieber** [kadirahq/react-storybook#20]
I would like to write some stories for React components based on some MaterializeCSS components. I'm using the materialize:materialize meteor package. Unfortunately they rely on extending jQuery. I know it is certainly not best practice to use jQuery with React, but some MaterializeCSS components are really handy. I tried to import MaterializeCSS from npm, but failed: [Issue 1422](https://github.com/Dogfalo/materialize/issues/1422).

So, how to work with react-storybook and imports from meteor packages?

**Comment by arunoda** [comment]
Unfortunately you can't. Try to get it fixed.
Anyway, eventually you need to use everything with NPM in Meteor.

**Comment by jschlieber** [comment]
Ok, thanks nevertheless...

**Comment by arunoda** [comment]
Great.

**Comment by ickyrr** [comment]
@jschlieber - did you find a solution for this?

**Comment by jschlieber** [comment]
No, I no longer use MaterializeCSS...
