### ISSUE TITLE
Feature: Nested stories

### ISSUE THREAD

**Issue by isuvorov** [kadirahq/react-storybook#201]
I have a lot of different states of components, a good solution would be nested story directories. 
Depth ~ 3-4  
Custom Library > BaseComponent > SubComponent > SubComponent with different state

![sceen](https://4.downloader.disk.yandex.ru/disk/e5fa647fb5643299d08cf61687d07f852ccc548e71e0ee5612aa3a184a22200a/573b3374/iiDA5hNE_Yiv7XevHxWvxfrKF4DmZbQicJ1BDOYQ5WZgU2VI-jrPEmnoq_EOLK1JizIuxMV_YMGrTuR2n5ijRw%3D%3D?uid=0&filename=2016-05-17_14-58-21.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=237354&hid=da357698d5c7963503de821f8ce76b3c&media_type=image&tknv=v2&etag=fa1051925e055d927e4b3f29a1925401 "Logo Title Text 1")

**Comment by arunoda** [comment]
We are tracking this here: https://github.com/kadirahq/react-storybook/issues/151
