### ISSUE TITLE
Disable sourcemaps?

### ISSUE THREAD

**Issue by jdelStrother** [kadirahq/react-storybook#202]
Heya - I'm not a fan of debugging with sourcemaps, and in my project they grind iOS Safari to a complete standstill.   I've currently hacked Storybook's internal [webpack.config.js](https://github.com/kadirahq/react-storybook/blob/master/dist/server/webpack.config.js#L20) to disable them, but was wondering if there was a better way.  Simply exporting `{devtool: null}` from .storybook/webpack.config.js doesn't seem to do the trick.

**Comment by arunoda** [comment]
You need to use our full control mode for that.
See [here in docs](https://github.com/kadirahq/react-storybook/blob/master/docs/webpack_full_control_mode.md).

**Comment by jdelStrother** [comment]
Perfect, thanks

**Comment by arunoda** [comment]
Hope we could close this.

**Comment by felquis** [comment]
https://github.com/storybooks/storybook/issues/202#issuecomment-219979955 link was not found

**Comment by texttechne** [comment]
https://storybook.js.org/configurations/custom-webpack-config/

**Comment by Hypnosphi** [comment]
Udated the original link
