### ISSUE TITLE
Feature: Sandboxed stylesheets?

### ISSUE THREAD

**Issue by jdelStrother** [kadirahq/react-storybook#203]
Our site has 2 distinct, conflicting stylesheets.  Each is used on different pages, and we never have both on a single page.

The default `import 'app.css'` approach results in both our stylesheets getting used simultaneously in Storybook, which is causing problems.   Any suggestions on better approaches where I might be able to specify per-component styles?

**Comment by arunoda** [comment]
Currently, there's no way to isolate unless you run two storybooks instances with two config files.

**Comment by arunoda** [comment]
Currently we don't have a feature planned for this.
What I suggest it to run two storybooks.
