### ISSUE TITLE
building static site faild

### ISSUE THREAD

**Issue by azl397985856** [kadirahq/react-storybook#209]
i wanna build static site by following the steps you provided in the doc, but i got a error when i try to run it on the python simpleHTTPServer
![image](https://cloud.githubusercontent.com/assets/12479470/15498657/18279dbe-21d3-11e6-9934-2e8dd46ab89c.png)

stacktrace:
Error: Invalid regular expression: /[a-zA-Z邪-褟袗-褟]+[*]?/: Range out of order in character class
e.exports
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:101:6351
Object.v [as registerLanguage]
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:90:18724
Object.<anonymous>
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:90:26117
t
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:1:107
e.__esModule.default
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:90:10351
Object.<anonymous>
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:90:10430
t
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:1:107
Object.<anonymous>
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:90:10290
t
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:1:107
Object.<anonymous>
file:///E:/ltcrm/trunk/ltcrm-components/ltcrm-components-static/static/preview.bundle.js:43:23569
![image](https://cloud.githubusercontent.com/assets/12479470/15498546/a2d63c46-21d2-11e6-8680-826bd096e99d.png)

**Comment by mnmtanish** [comment]
Hi @azl397985856 
It looks like there's an error with the regular expression [(error)](https://regex101.com/r/hL7gY5/1)

**Comment by azl397985856** [comment]
but running successfully.


only when I try to build-static-site . something went really wrong

**Comment by azl397985856** [comment]
![image](https://cloud.githubusercontent.com/assets/12479470/15527767/d5ce0dde-226f-11e6-9aba-d48a3fbc89f3.png)
i delete part of pages, then it works.
but i get messy code。 what am i doing wrong?

**Comment by azl397985856** [comment]
ps: 
I add <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> tag

**Comment by azl397985856** [comment]
maybe i found the reason.     i shouldn't run as local file, it should be placed on the static server, the  add the tag<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
so if you'd like to add this into your html template when running the shell 'build-storybook', it may help many other people like me,  thanks

**Comment by mnmtanish** [comment]
Hi @azl397985856 
Thanks for all the info. I've just release `v1.28.1` with the charset meta tag.
This should fix this issue.
