### ISSUE TITLE
Some early reviews

### ISSUE THREAD

**Issue by antoinerey** [kadirahq/react-storybook#21]
First of all, this a very good idea ! :)

I find confusing that the story you select jumps to the top of the list. You can't rely on the order since it keeps changing every time you click on a new story. In my opinion, one solution could be to just expand the item in the list without touching the order.

Moreover, a way to empty the action logger box should be a very very good addition. It gets harder to find your informations when the box is filled.

**Comment by arunoda** [comment]
@antoinerey I agree on both. Will land a fix very early next week.

**Comment by arunoda** [comment]
These two have been fixed in version `1.2.0`.
Thanks for the feedback.
