### ISSUE TITLE
Lack of charset in builded html

### ISSUE THREAD

**Issue by i4got10** [kadirahq/react-storybook#215]
While running storybook under node, server return Content-Type header, that allow browser to show content in utf-8.

``Content-Type:text/html; charset=utf-8``

But then build static html, there is no charset specified. It leads to

![react storybook 2016-05-25 13-56-15](https://cloud.githubusercontent.com/assets/1151154/15534050/873014ae-2280-11e6-80f1-3845b9949752.png)

Problem here is that there is no way to add this header to ``<head>``. For iframe I can add ``head.html``. Please, add ``<meta charset="utf-8">`` to head of main template

**Comment by mnmtanish** [comment]
Related https://github.com/kadirahq/react-storybook/issues/209

**Comment by mnmtanish** [comment]
Hi @i4got10 
Thanks for the tip. Added the meta tag and released `v1.28.1`

**Comment by i4got10** [comment]
Thank you!
