### ISSUE TITLE
Error installing 1.28.1

### ISSUE THREAD

**Issue by gbylenok** [kadirahq/react-storybook#218]
I am trying to use the latest storybook and have run into a few issues that I wanted to run by someone here. Everything worked fine a couple of weeks ago, but then I upgraded to npm 3.x and tried to grab the latest storybook code. 

I tried to keep the package.json simple, like this:
```
@kadira/storybook": "https://github.com/kadirahq/react-storybook.git"
```
but always received errors like this upon "npm install":
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 no such package available : @kadira/storybook-core
npm ERR! 404 
npm ERR! 404  '@kadira/storybook-core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@kadira/storybook'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
So I tried to expand the list of dependencies in package.json to this:
```
"@kadira/react-split-pane": "https://github.com/kadirahq/react-split-pane.git", 
"@kadira/storybook-core": "https://github.com/kadirahq/storybook-ui.git",
 "@kadira/storybook": "https://github.com/kadirahq/react-storybook.git"
```
That allowed me to at least download the packages and start up storybook. However, upon starting, I got a further error:
```
  [323] ./~/@kadira/storybook/dist/manager.js 257 kB {1} [built]

ERROR in ./~/@kadira/storybook/dist/client/preview/init.js
Module not found: Error: Cannot resolve module '@kadira/storybook-core/dist/libs/key_events'
in /Users/foo/code/i95/web/client/node_modules/@kadira/storybook/dist/client/preview
 @ ./~/@kadira/storybook/dist/client/preview/init.js 29:18-72
```
Checking init.js, it appears to be pointing to a directory in storybook-core that doesn't really exist. Do you think this is an issue with this distribution, or am I doing something wrong? 

Thanks for any assistance. React Storybook is a great tool, and it would be great to see it working again!

**Comment by mnmtanish** [comment]
Please use storybook module from npm.

```
"@kadira/storybook": "^1.28.1",
```

We're using the `prepublish` hook to transpile ES6 code to ES5. That is why you're getting the "Module not found" error. Anyways we don't recommend using storybook from Github.

**Comment by arunoda** [comment]
@mnmthanish it should be possible to refer GitHub as the source as well. 

May be we need to publish the dist directory of split-pane and mantra-core into GitHub.

**Comment by mnmtanish** [comment]
@gbylenok @arunoda 

Published `lib`, `dist` directories in `react-split-pane` and `storybook-core` packages.
Github installations will work from now.

**Tip:**
No need to enter the complete url for Github sources, `user/repo` will also work.
https://docs.npmjs.com/files/package.json#github-urls

```
"dependencies": {
  "@kadira/storybook": "kadirahq/react-storybook",
}
```

**Comment by gbylenok** [comment]
Thank you! I have verified that the install works from github. I could never get it to work from our private npm registry, so that's why I went the github route.

**Comment by arunoda** [comment]
Great work guys.
