### ISSUE TITLE
Invalid name: "@kadira/storybook" when installing package with npm

### ISSUE THREAD

**Issue by robin-drexler** [kadirahq/react-storybook#22]
When I try to install the package with npm version 3.8.3, I get the following error:

```
Invalid name: "@kadira/storybook"
```

Have seen that before?

**Comment by themgt** [comment]
Same here:
```
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! Invalid name: "@kadira/storybook"
```

See also https://github.com/kadira-samples/react-storybook-demo/issues/3

**Comment by arunoda** [comment]
It seems like you guys are using a NPM mirror registry. See here: https://github.com/kadirahq/react-storybook/issues/15

**Comment by themgt** [comment]
gotcha, thanks!

**Comment by arunoda** [comment]
I'm gonna close this and re-open the original #15.

**Comment by nrempel** [comment]
@arunoda I think these issues are unrelated.

I am using the npm registry:

`npm c get registry`
https://registry.npmjs.org/

and I get

`Invalid name: "@kadira/storybook"`

Any ideas?

**Comment by arunoda** [comment]
@nrempel That's so weird. I'm working on to support GH based distribution. Need some work, I'll publish on the other thread.

**Comment by atfzl** [comment]
I am not sure what is the reason but it works for me if node is installed through nvm. It gives error if I use the node distribution from https://nodejs.org/en/.
