### ISSUE TITLE
Cannot resolve module 'style' when using react-flexgrid

### ISSUE THREAD

**Issue by kjetilge** [kadirahq/react-storybook#220]
I can't get react-flexgrid to work alongside storybook.
When I add this line:
```import "react-flexgrid/lib/flexgrid.css"```
to my componen.jsx I get the error:
```
ERROR in ./client/modules/cars/components/new_car.jsx
Module not found: Error: Cannot resolve module 'style' in /Users/kjetilge/Documents/Development/Tapcar-react/mantraMui2/client/modules/cars/components
 @ ./client/modules/cars/components/new_car.jsx 39:0-42
```

My ./storybook/webpack.config.js looks like this:

```
const path = require('path');
module.exports = {
  module: {
    loaders: [
      {
        test: /\.css?$/,
        loaders: [ 'style', 'raw' ],
        include: path.resolve(__dirname, '../')
      }
    ]
  },
  resolve: {
     extensions: ['', '.js', '.jsx'],
  },
};
```

**Comment by track0x1** [comment]
Did you install `style-loader` in your npm package?

**Comment by kjetilge** [comment]
I did, but it gave me new problems/warnings. Don't remember exactly. Switched to reflexbox now, though I think some things are missing in that package..

**Comment by track0x1** [comment]
Also I'd remove `include: ...` from your loader because the css file is going to be in `node_modules` which isn't included by your config.

**Comment by kjetilge** [comment]
This webpack stuff is totally new to me. Need to read up on the syntax etc. I'll try it !

**Comment by arunoda** [comment]
Our latest storybook has much support for CSS and read our docs here: https://getstorybook.io
