### ISSUE TITLE
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

### ISSUE THREAD

**Issue by shijunti19** [kadirahq/react-storybook#221]
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Comment by mnmtanish** [comment]
Hi @shijunti19 
The warning comes from [mocha](https://github.com/mochajs/mocha/issues/2200).
I'm afraid we'll have to wait for now.
