### ISSUE TITLE
Storybook Contribution Guide

### ISSUE THREAD

**Issue by jhicken** [kadirahq/react-storybook#225]
So I pulled open the code to try and add some features. And I'm super lost. I spent about an 3 hours digging through stuff and this is my conclusion

I have never used Mantra. There seems to be very little documentation on it.

It would also be nice to have some documentation on the folder structure and how to contribute to storybook.

Documentation on what all the different repos are. storybook-ui storybook-core ect...

**Comment by arunoda** [comment]
Yes. This is very very needed. This is my first priority in this week.

**Comment by arunoda** [comment]
I think we've some pretty guide now specially with addons.
See: https://getstorybook.io
