### ISSUE TITLE
can't parse class attribute

### ISSUE THREAD

**Issue by gsabran** [kadirahq/react-storybook#230]
There might be something weird with some `.babelrc` but 
```js
class Task extends Component {
  static propTypes = {
    task: PropTypes.object.isRequired,
    userId: PropTypes.string,
  };
  ...
}
```
can't be parsed when using storybook. This raises `Unexpected token` on the `=` apparently.
I'm on a meteor project with no custom  `.babelrc`

**Comment by gsabran** [comment]
fix with a standard `.babelrc` ...:
```js
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ]
}
```

**Comment by TigerC10** [comment]
#227 Fixes this issue; Pretty recent change to the project.  I'm still getting a few slight errors from needing to update the stage in kadirahq/storybook-ui#1 - need #241 to fully resolve, I think.
