### ISSUE TITLE
Access files in Meteor public folder

### ISSUE THREAD

**Issue by raedle** [kadirahq/react-storybook#232]
Just discovered storybook and it's pretty neat!

I'm using it together with a Meteor project. Also, I'm using static images in some stylesheets. The images are in the /public folder. Is it somehow possible to add this folder to the webpack configuration?

**Comment by arunoda** [comment]
Yes that's possible. See: https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#static-directory

**Comment by raedle** [comment]
Very neat! It works like a charm. Great job!
