### ISSUE TITLE
Static build doesn't work on Safari

### ISSUE THREAD

**Issue by smesko85** [kadirahq/react-storybook#234]
On Safari, static build doesn't initialize because of the source map (manager.js.map) not found (url not resolved). When source mapping comment (sourceMappingUrl) is removed from manager.js in dist folder, everything works as expected.

**Comment by mnmtanish** [comment]
Hi @smesko85 
Just released `v1.29.1` to include the source map file. Can you confirm whether it works?
Thanks for reporting the issue.

**Comment by smesko85** [comment]
Hi @mnmtanish,
It works perfectly! Thank You for quick response!
