### ISSUE TITLE
Wrong path join

### ISSUE THREAD

**Issue by avin** [kadirahq/react-storybook#239]
Hello guys, I think you should not use '\' in path.join.
```
<script src="static\manager.bundle.js"></script>
```

Firefox does not like this
```
GET 
http://localhost:9001/static%5Cmanager.bundle.js [HTTP/1.1 404 Not Found 1ms]
```

**Comment by mnmtanish** [comment]
I think I just found the issue. Just to make sure, are you using Windows?

**Comment by mnmtanish** [comment]
@avin can you try `v1.29.2`
It should work now

**Comment by avin** [comment]
@mnmtanish, yes i'm windows user and `1.29.2` works fine! Thank you very much for fast reply!

**Comment by ImanMh** [comment]
I'm using Mac and I have the same issue. I'm also using the latest version of storybook.

**Comment by freakaziod210** [comment]
I am also a Mac use and I am having this same problem. I am using version 3.1.7. @mnmtanish Any suggestions?
