### ISSUE TITLE
Add support for Webpack2

### ISSUE THREAD

**Issue by mnmtanish** [kadirahq/react-storybook#248]
I just found this interesting [commit](https://github.com/trabian/react-storybook/commit/ae6e066af014597e842e3bb5949c514df86dd93d) on a fork of this repo.

It seems storybook is not compatible with webpack 2 because of `OccurenceOrderPlugin`.
Test whether this is true and remove the plugin if necessary.

**Comment by shawnrice** [comment]
There was a typo in the plugin name in Webpack 1. They fixed it, but to keep it backwards compatible, they supported both. So, in Webpack 1 you have `OccurrenceOrder` and `OccurenceOrder`. In Webpack 2, you just have the correct spelling. So a PR that just adds an extra `r` would work for both Webpack 1 and 2.

**Comment by arunoda** [comment]
@mnmtanish could you work on this? 
And generally how to deal with webpack 2.0 if used in a project. (Do we need to change the `package.json`.

**Comment by arunoda** [comment]
Here's my suggestion to support both Webpack2 and Webpack1

* We will write storybook to work with either webpack2 or webpack1 (May be we could detect the version and do any tricks, if needed)
* We make the version for webpack like this: `"webpack": "1.x.x || 2.x.x"`
* If the source project uses webpack2, npm will use it and it's the same for webpack2.

I didn't test this, but this will work and fix issue on #253 as well. Any comments?

**Comment by kevinSuttle** [comment]
@arunoda @KentCDodds has a great Webpack course on Egghead covering version 2. 
https://egghead.io/courses/using-webpack-for-production-javascript-applications

**Comment by arunoda** [comment]
Thanks @kevinSuttle

**Comment by kevinSuttle** [comment]
Any progress to note here? I think this may be affecting this issue as well: https://github.com/kadirahq/react-storybook/issues/304#issuecomment-232155335

**Comment by sheerun** [comment]
@arunoda #397 doesn't fix this issue as custom plugins I use in my project are not compatible with webpack 1.. What would really solve this issue is setting webpack as peerDependency
