### ISSUE TITLE
How can I use CSS framework styles inside a storybook

### ISSUE THREAD

**Issue by croogie** [kadirahq/react-storybook#25]
Let's say that my application is basing on some CSS framework like Semantic UI, Bootstrap or something like that. How can I easily incorporate that styles inside a story book so that my components will display correctly?

**Comment by arunoda** [comment]
Yes it is. Read here - https://github.com/kadirahq/react-storybook/blob/master/docs/setting-up-for-css.md

I that's not what you need, just reopen this.

**Comment by andrioid** [comment]
Link is broken and I can't find it in the file in current master.

**Comment by arunoda** [comment]
Check this: https://getstorybook.io/docs/configurations/custom-webpack-config

**Comment by andrioid** [comment]
Thanks. An easier way was to add a head.html file in the ".storybook" directory with the <Link> elements for Bootstrap og Semantic UI

**Comment by fizyboy** [comment]
Thanks head.html method works perfectly!

**Comment by felipecocco** [comment]
Would head.html also be the best way to go about it if the file for you are adding is not served through a URL but is instead hosted locally? how would that work?

**Comment by kirkstrobeck** [comment]
Both links are broken.

**Comment by ndelangen** [comment]
Sorry for the broken links, this is unfortunately the result of our restructuring, The only way to find is by search. 

What are you looking for / need help with @kirkstrobeck ? This issue is quite old and closed.
If you have a specific problem we can help you with, let us know 👍 .

**Comment by sergiotapia** [comment]
I landed here trying to figure out how to integrate React Storybook into a real application where all of our styles are in scss files in `app/assets/stylesheets`

**Comment by ndelangen** [comment]
You'll need to extend our webpack config / provide your own custom webpack config.

In it you'll need to tell webpack what to do with the `.scss`-files. aka, you need to add the `sass-loader`.

Likely you already have this already setup for you app, and you can mostly copy-paste from it's webpack config?

**Comment by blairanderson** [comment]
found in documentation: https://storybook.js.org/configurations/default-config/#css-support

**Comment by adamchenwei** [comment]
@arunoda would it possible remove above two links that have confused face I marked above? save time for others who enter this page in the future. Thanks!

**Comment by kirkstrobeck** [comment]
The confused reactions are probably enough. I upvoted em’ too.

**Comment by Hypnosphi** [comment]
Just updated the comments with outdated links

**Comment by LukasMac** [comment]
Header file for story book is called `preview-head.html` Reference:
https://storybook.js.org/configurations/add-custom-head-tags/

**Comment by flavordaaave** [comment]
Within my "main" app my global styles are defined within a JS file that exports a template string containing all the global CSS rules.
Is there a way to add a template string with CSS definitions to the iframe where the stories are rendered in?

**Comment by ndelangen** [comment]
@flavordaaave I think you'll want to use just inject the styles in a style-tag from config.js

**Comment by flavordaaave** [comment]
@ndelangen So far all the possibilities of injecting global style (`import './styles.css';` or via `preview-head.html`) don't allow me to inject styles with dynamic params.

My styles look something like this:
```
/* .storybook/config.js */

import theme from './theme'

export default `
html {
  font-family: Helvetica;
  background: ${theme.canvas_ground};
  ...
}
`
```

So for now I'm using the `injectGlobal` helper from `react-styled-components` as mentioned in my *EDIT* above.
```
/* .storybook/config.js */
...
import { injectGlobal } from 'styled-components'
import styles from '../src/styles'

injectGlobal`${styles}`
...
```

**Comment by Hypnosphi** [comment]
what `injectGlobal` does is basically this:

```
// create a <style></style> DOM element
const styleElement = document.createElement('style')
// put the text from styles variable between opening and closing <style> tags
styleElement.appendChild(document.createTextNode(styles))
// place the style element inside <head>
document.head.appendChild(styleElement)
```

**Comment by bradfrost** [comment]
Hi there! 
I'm trying to link up my stylesheet to Storybook, and am striking out.

I followed [these instructions](https://storybook.js.org/configurations/default-config/#css-support) to import my CSS file (which lives in `static/style.css` in my project root) with this line: `import '../static/style.css';`. That resulted in an error with r

`Error: Can't resolve '../i/link.svg' in [path]`

I don't want to have to go through all this [rigamarole](https://github.com/postcss/postcss-import/issues/304) to reconcile every externally-referenced resource in my stylesheet, so I thought I'd try a different way.

I added a `preview-head.html` [per these docs](https://storybook.js.org/configurations/add-custom-head-tags/), linking up my stylesheet like so:

`<link rel="stylesheet" href="./static/style.css" />`

This however results in a 404 error for the resource. I _think_ it might just be a path issue, but can't seem to find which path I should be using relative to where Storybook is running. Any ideas?

**Comment by nickytonline** [comment]
If you're getting 404s because you're CSS is not on a CDN, you can pass an extra parameter to run Storybook with a static folder and reference your files as just `./some.css`. Run `storybook -p 9001 -s ./a-static-folder` and put your css in that folder.

**Comment by bradfrost** [comment]
Thanks for the suggestion, @nickytonline. Unfortunately that didn't seem to work. I have my files in `static/style.css` and I ran the command `storybook -p 9001 -s ./static`. That resulted in `storybook: command not found`. I ran npm run storybook -p 9001 -s ./static` which ran, but still resulted in a 404 error on my stylesheet.

**Comment by nickytonline** [comment]
@bradfrost, just for clarification, when you run `npm run storybook -p 9001 -s ./static`, `./static` acts like `/` in storybook, so if your file is in `static/styles.css` in your project, your link would be `<link rel="stylesheet" href="./styles.css" />` not `<link rel="stylesheet" href="./static/styles.css" />`

**Comment by bradfrost** [comment]
@nickytonline Yep, I had things linked up as `<link rel="stylesheet" href="./styles.css" /`.

**Comment by nickytonline** [comment]
@bradfrost this was bugging me that it was not working for you so I create a very basic repo using create-react-app and the storybook CLI. It shows an example of a static asset being used in storybook being referenced via a `<link />` tag. It's available here, https://github.com/nickytonline/for-brad

![image](https://user-images.githubusercontent.com/833231/38224702-39b4c9c2-36bf-11e8-8789-90758b0a80fc.png)

**Comment by bradfrost** [comment]
@nickytonline Thanks very much for the demo project! I really appreciate it.

The issue I'm still running into is reflected in [my original post](https://github.com/storybooks/storybook/issues/25#issuecomment-377046095), which is the use of `import` to get the styles into the project. That method unfortunately throws errors if assets like fonts or icons or background images don't resolve. I realize there are ways of remedying that, but I guess I'm just looking to link up a stylesheet in the head of my document the ol' fashioned way.

**Comment by nickytonline** [comment]
Sorry, my bad for not absorbing the entire content of your original post. That's quite the pickle if you want to avoid the [rigamarole](https://github.com/postcss/postcss-import/issues/304). Gonna have to think about that one a little bit.

**Comment by tysonmatanich** [comment]
@bradfrost Did you figure this out? I'm running into something similar with using injectglobal for styled components and the images and fonts referenced in CSS get requested at **localhost/** instead of **localhost:9000/** which causes them to fail.

@nickytonline Any update?

**Comment by amos80m** [comment]
What you can do is to create a 'public' folder in the root folder.
in the 'public/semantic' folder pest the content of 'node_modules/semantic-ui-css'.
in package.json => scripts => storybook => add ''-s ./public"
last thing!!! in your component .less file do @import '/semantic/semantic.min.css';
now Icon should work smoothly.

**Comment by jmarceli** [comment]
For Storybook v5 and `normalize.css` "framework" it is enough to just add `import "normalize.css";` inside `.storybook/config.js` file.

**Comment by anton-paskanny** [comment]
@jmarceli It works for me, thanks a lot!

**Comment by snyderhaus** [comment]
Is this still a viable option with v6?

> For Storybook v5 and `normalize.css` "framework" it is enough to just add `import "normalize.css";` inside `.storybook/config.js` file.

**Comment by shilman** [comment]
@snyderhaus yes, though since 5.3 `config.js` has been soft-deprecated and we suggest using `preview.js` instead. more info:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration

**Comment by scottc11** [comment]
I have come to this thread numerous times for numerous projects! So this is for my own reference as well as anybody else.

This worked for me. 

```
// storybook/config.js

import 'semantic-ui-css/semantic.min.css';
import 'bootstrap/dist/css/bootstrap.css';
import '!style-loader!css-loader!sass-loader!../client/scss/style.scss';
```

my `style.scss` is overriding the default bootstrap theme using sass variables

I was able to use storybooks default webpack config and just reference the style sheets like so, additionally using the **inline loader syntax** for my `sass` files, as shown [in the docs](https://storybook.js.org/docs/configurations/default-config/#css-support).


```
"babel-core": "6.26.0",
"babel-loader": "7.1.4",
"@storybook/react": "^5.3.14",
"sass-loader": "^8.0.2",
"css-loader": "^3.4.2",
"style-loader": "0.20.3",
"react": "^16.3.2",
```

**Comment by gkortsit** [comment]
For anyone using v6+ the solution using `config.js` will not work.

I've managed to make it work like so:
- create a file named `preview.js` in the `.storybook` folder
- import the external css. In my case they were scss files so I've imported them like this:

```js
import '!style-loader!css-loader!sass-loader!@company/framework/src/styles.sass'
import '!style-loader!css-loader!sass-loader!./cssoverrides.sass'
```

The second import was added to override some default global styles.

My folder structure:

```
.storybook
│   cssoverrides.sass
│   main.js  
│   preview.js
```

Packages used: 

```
"@storybook/react": "^6.0.0",
"react": "^16.13.1",
"@babel/core": "^7.11.1",
"@babel/preset-env": "^7.11.0",
"@babel/preset-react": "^7.10.4",
"sass-loader": "^9.0.3",
"css-loader": "^4.2.1",
"style-loader": "^1.2.1"
```

**Comment by angelikipatrinou** [comment]
What worked for me was to import bootstrap on ./storybook/preview.js

```
//I added this:
import 'bootstrap-4-grid/css/grid.min.css';

//this was already there
export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
};
```

https://storybook.js.org/docs/react/configure/styling-and-css#importing-css-files

**Comment by ArianZargaran** [comment]
In case you are injecting Bootstrap via CDN, a clean and easy solution is to populate Storybook Head Preview as mentioned in the docs: https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head

This solution worked for me:
* Create a new `.storybook/preview-head.html` file
* Include any tag you may need in your Storybook iframe preview, HTML Head. In our case we are dropping Bootstraps CDN
```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
```
* Launch your Storybook (re-build) and DONE!

**Comment by trickydisco78** [comment]
This was working when i was just importing global styles but now i've added a decorator to enable html preview the styles are no longer loaded

```
import { addDecorator } from '@storybook/html';
import { withHTMLDOC } from 'storybook-addon-html-document/html';

import '../src/css/styles.css';

addDecorator(withHTMLDOC);
```

**Comment by mleister97** [comment]
### Storybook v6.+ solution
Super simple for everyone facing issues with importing custom styles/fonts/sass/...

Create a file called `preview.js`
Import your global stylesheet e.g. 

preview.js
```
import "./../src/styles/index.scss";
```

**Comment by belloviniciusf** [comment]
> ### Storybook v6.+ solution
> Super simple for everyone facing issues with importing custom styles/fonts/sass/...
> 
> Create a file called `preview.js`
> Import your global stylesheet e.g.
> 
> preview.js
> 
> ```
> import "./../src/styles/index.scss";
> ```

Recently we updated to v6 and had issues specifically on storybook, it resolved these, thanks.

**Comment by 50l3r** [comment]
> ### Storybook v6.+ solution
> Super simple for everyone facing issues with importing custom styles/fonts/sass/...
> 
> Create a file called `preview.js`
> Import your global stylesheet e.g.
> 
> preview.js
> 
> ```
> import "./../src/styles/index.scss";
> ```

If i try to do this it load styles well but overwrite storybook styles like code:

`@import "buefy/src/scss/buefy.css"`

![](https://i.gyazo.com/b20b8d7c195d8466429f2f849d5fe469.png)

I try to encapsulate with scss like this:

style.scss
```
#root>#buefy {
	& {
		@import "buefy/src/scss/buefy.css";
	}
}
```

preview.scss

```
import './style.scss'
export const decorators = [
	(story) => {
		return {
			components: { story },
			template: '<div id="buefy"><story /></div>',
		}
	},
]
```

![](https://i.gyazo.com/93e9a17859e37d36ef5adbde122c9dd8.png)

But it ocurrs on reverse. Buttons style seems to big.

**Comment by drik98** [comment]
I am currently having the same problems as @50l3r. (Just that we are using bootstrap instead of buefy.)

It should not be possible to overwrite the styling of the `code` section, the imported css should only apply to everything inside the `.docs-story` container.

**Comment by jdubs1994** [comment]
> 

did you ever figure out how to fix it?

**Comment by jdubs1994** [comment]
> I am currently having the same problems as @50l3r. (Just that we are using bootstrap instead of buefy.)
> 
> It should not be possible to overwrite the styling of the `code` section, the imported css should only apply to everything inside the `.docs-story` container.

Did you ever figure out how to fix it?

**Comment by shilman** [comment]
@jdubs1994 you can run your stories in iframes using the `docs.iframeStories = true` parameter. however, this has performance implications

**Comment by jdubs1994** [comment]
> @jdubs1994 you can run your stories in iframes using the `docs.iframeStories = true` parameter. however, this has performance implications

`import '../src/scss/global.scss'

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  docs: {
    iframeStories: true
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}`

Running into the same result, this is what my preview.js looks like. Everything looks good besides the code snippet section of the story.
