### ISSUE TITLE
Turn [HMR] console.log off

### ISSUE THREAD

**Issue by MechJosh0** [kadirahq/react-storybook#252]
How do you turn this console.log off? I see there is an option to turn it off in the code but I'm unable to backtrack it to how it's possible from my end.

**Comment by arunoda** [comment]
We've added(again after removing) HMR logs. They are pretty important.

**Comment by jazzdragon** [comment]
You must provide some configuration to disable this behavior. It adds so much clutter, makes it hard to debug issues while developing components.

**Comment by streamich** [comment]
So, is there a way to mute logging?

**Comment by volodymyr-kushnir** [comment]
You can set `-[HMR]` in the console's filter input if we're talking about Chrome DevTools.

**Comment by ouweiya** [comment]
> -[HMR]

Useful, what does it mean? It doesn't look like RegExp
