### ISSUE TITLE
Use webpack as a peer dependency ?

### ISSUE THREAD

**Issue by FredyC** [kadirahq/react-storybook#253]
Since storybook depends on Webpack 1, it's not possible to use same Webpack 2 configuration for bundling components. This is especially problematic with loaders which I have configured for application.

For example I have some basic loaders (more will come) like this
```js
loaders: [
	{ test: /\.jsx?$/, loader: 'babel', include: srcPath },
	{ test: /\.css$/, include: srcPath, loaders: [
		'style',
		{ loader: 'css', query: { modules: true }}
	]},
],
```

Here comes first issue with babel as for Webpack 2 which recognizes ES6 modules, I have `.babelrc` file which uses preset `es2015-native-modules`. This preset is not transpiling ES6 modules which is neat for Webpack 2, but a problem for Webpack 1.

For the storybook I created my own `webpack.config.js` file like this...
```js
var pathUtils = require('path');
var baseConfig = require('../webpack.config.js');

module.exports = function(storybookConfig) {
	storybookConfig.resolve = baseConfig.resolve;
	storybookConfig.module = {
		loaders: [
			{
				test: /\.jsx?$/,
				loader: 'babel',
				include: pathUtils.resolve(process.cwd(), 'src'),
				query: {
					babelrc: false,
					presets: ['es2015', 'stage-1', 'react'],
					plugins: ['react-require']
				}
			},
		]
	};
	return storybookConfig;
};
```

I had to reconfigure babel loader here like this which is already ugly enough. However I am also losing other configured loaders this way.

Having webpack as peer dependency it would allow people to choose version more freely without need to change anything else in storybook.

**Comment by arunoda** [comment]
Yep. I can see the problem. Using it as a peer-dep for now may not work for us. But we can add support for webpack 2 in the package.json.

So, if you've installed webpack2 for your app, it'll use it. We will also move to webpack2 by default.

**Comment by arunoda** [comment]
This will be address in #248
