### ISSUE TITLE
How to export stories into new react green field application

### ISSUE THREAD

**Issue by sunnybogawat** [kadirahq/react-storybook#255]
I have used storybook to create a component based on stories. The component is plain react component where data has been supplied from container. The component has been tested properly now, I want to use this component into a separate react project where I can integrate this component as per business logic. So one way is I can directly use component jsx file into my new project but I want to know is there any other way to export these component from storybook may be using npm module or some other way?

**Comment by travi** [comment]
I've been tinkering with a side project to learn about topics around this process. Feel free to take a look at https://github.com/travi/admin.travi.org-components if it can help you make progress.

**Comment by arunoda** [comment]
We've documented some ideas here: https://getstorybook.io/docs/basics/writing-stories#managing-stories
