### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by bronson** [kadirahq/react-storybook#257]
https://news.ycombinator.com/item?id=11414392  :)

I'd really enjoy seeing one.  I suppose it could include wishlist items like #19 but I'd mostly be interested to see what's coming next.

Roadmap files are kind of a PITA to maintain.  If you've rethought this, feel free to close.

**Comment by arunoda** [comment]
I think it's better to have a ROADMAP.md.
I'll create a one in a moment.

But, I won't put dates.

**Comment by arunoda** [comment]
See: https://github.com/kadirahq/react-storybook/blob/master/ROADMAP.md

**Comment by bronson** [comment]
Nice!
