### ISSUE TITLE
Storiesof creator 

### ISSUE THREAD

**Issue by jurgob** [kadirahq/react-storybook#259]
Hi, 
I think than a common pattern using react-storybook could be like writing a bunch of stories for the same component and watch them simultaniusly while you are coding.
That's why I have created this utility:

https://gist.github.com/jurgob/a0f2e0cfc3296279fcf47ff4a697076f

let me know if this idea make sense for you and if there's a better way to do it.

**Comment by mnmtanish** [comment]
Here's an example
https://github.com/kadirahq/react-storybook-addon-info/blob/9bfca0d8219300fcb467674a4064183f1622eea1/src/index.js

**Comment by arunoda** [comment]
@jurgob great.
As @mnmtanish mentioned, write an [addon](https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md) and send a PR to [this list](https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md#available-extensions).

**Comment by jurgob** [comment]
I'll do it

**Comment by jurgob** [comment]
I did the add-on (new code here: https://gist.github.com/jurgob/f0604291619634f0e5e6204814ea2ed1).

Next days I'll do a proper repo and a pull request

**Comment by arunoda** [comment]
Since we've a way plan, I'm gonna close this.
