### ISSUE TITLE
Webpack loaders required by addons

### ISSUE THREAD

**Issue by FredyC** [kadirahq/react-storybook#260]
Related to https://github.com/kadirahq/react-storybook-addon-info/issues/12

As I said there, it would require to add json loader to a webpack config here. However is that a good solution in general? There might be surely some other addon in future that would require it. On the other hand it's better solution to include it instead of forcing consumer to add it there manually in my opinion.

**Comment by arunoda** [comment]
@FredyC. That's something buggy at the moment. There's no need for that.
Will be fixing it by today.

**Comment by arunoda** [comment]
We've fixed this and we've more discussions on this on:https://github.com/kadirahq/react-storybook-addon-info/issues/12 and #261
