### ISSUE TITLE
new proxy: propsInfo

### ISSUE THREAD

**Issue by jurgob** [kadirahq/react-storybook#264]
Basically I did a props displayer proxy, 

it is similar to yours addInfo add on, but as a proxy  it can work nicer within my story generators

here is the code
https://gist.github.com/jurgob/0ba5e7daa12b85b9e2d693c3ff9431e6

It is still very limitated, my main problem is this one:
https://discuss.reactjs.org/t/print-proptypes-definition/4228

**Comment by arunoda** [comment]
@mnmtanish @roonyh I think you guys could add something to this.

**Comment by mnmtanish** [comment]
Fixed with this [addon](https://github.com/kadirahq/react-storybook-addon-info)
