### ISSUE TITLE
Docs Issue on customising the ui

### ISSUE THREAD

**Issue by SimeonC** [kadirahq/react-storybook#265]
Currently the link and guide here https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#customizing-the-ui are incorrect. I'm trying to muddle my way through the code currently to see if I can figure it out but I'm not there yet!

*EDIT* Just found out why I can't edit the ui - your storybook-ui components are all mass bundled into the dist so I can't just go around replacing them using the ReplacementPlugin. I take it we can't actually modify the UI at present then?

**Comment by pcardune** [comment]
+1 to fixing this bug, or at least the documentation discrepency.

**Comment by arunoda** [comment]
At this moment, it'll be hard to do that.
We'll have a plugin system soon.
For now, I'll remove that section from docs.

**Comment by arunoda** [comment]
@SimeonC I suggest you to fork the storybook-ui and use your customized one, instead of our own one for now.
