### ISSUE TITLE
register with greenkeeper

### ISSUE THREAD

**Issue by travi** [kadirahq/react-storybook#267]
greenkeeper is a tool that is free for open source projects that is a big help in keeping dependencies up to date by providing PRs each time one of your dependencies publishes an update. 

it's obviously up to you how you manage your own dependencies, but for those of us that consume your package and also use the greenkeeper service, registering would be a big help. since this is a scoped package, a `postpublish` hook is needed for greenkeeper to be aware of the new versions that you publish. this is added automatically if you follow their getting-started steps.

it is [very simple to register](https://greenkeeper.io/#getting-started) a package with the service. if you would be willing to at least add the `postpublish` hook, it would be a big help to any of your consumers that happen to use greenkeeper.

**Comment by arunoda** [comment]
Thanks. I'll work on this.

**Comment by travi** [comment]
Any update with this?  Should be a quick update to get this taken care of and would be a big help for consumers. 

Unfortunately, there's not much I can contribute to help move it along since it needs to be done with organization access in order to grant the privileges to configure webhooks.

**Comment by arunoda** [comment]
Done. Had to do few eslint rule updates too.
See: https://github.com/kadirahq/react-storybook/pull/421

**Comment by travi** [comment]
Thanks!  I got a PR from greenkeeper for the latest release, so I can confirm that it is working.
