### ISSUE TITLE
Latest version not working (JSON loader issues?)

### ISSUE THREAD

**Issue by ffxsam** [kadirahq/react-storybook#273]
I could've sworn this was somewhere in the documentation, but I can't find it now.

I'm getting a bunch of these errors:

```
ERROR in ./~/entities/lib/encode.js
Module not found: Error: Cannot resolve module 'json' in /Volumes/SuperData/Sites/harris-partners/harris/node_modules/entities/lib
 @ ./~/entities/lib/encode.js 1:31-58
```

There was some setup instructions regarding a JSON loader, but I don't recall what it was. Can anyone point me in the right direction?

**Comment by ffxsam** [comment]
Never mind, got it. Will do a PR to add this to the documentation.

**Comment by arunoda** [comment]
FYI: related PR: #274
