### ISSUE TITLE
Storybook not recovering from errors "Error: _get__(...).unmountComponentAtNode is not a function"

### ISSUE THREAD

**Issue by wallslide** [kadirahq/react-storybook#275]
If an error occurs in a story, after fixing the error the story is stuck in an error state.

I'm using version 1.34.0

**Expected:**
The story will 'recover' and return to a working state after the coding/syntax error is fixed.

**Actual:**
The following error replaces the original error:

`Error: _get__(...).unmountComponentAtNode is not a function`
![image](https://cloud.githubusercontent.com/assets/917069/16294838/10c06018-395e-11e6-80e9-65a7c1aa79d2.png)

Refreshing the browser fixes the problem until the next time a coding/syntax error occurs.

**Comment by arunoda** [comment]
Is it possible to get a kind of a sample project. So, I can work on this.

**Comment by arunoda** [comment]
May be related to this: https://github.com/kadirahq/react-storybook/issues/276

**Comment by PEM--** [comment]
Got this issue too since 1.34.x. I need to it a full reload each time the red warning is displayed.

**Comment by arunoda** [comment]
Yep. Found the issue and fixed with the newest version: `v1.35.1`

**Comment by PEM--** [comment]
Thanks 👍  You nailed it.

**Comment by arunoda** [comment]
Great. Going to close this then :)

**Comment by markerikson** [comment]
@arunoda : Can you clarify what exactly the issue was?  I'm seeing the same issue in my own app, and this is the only real hit for the specific error message.

**Comment by arunoda** [comment]
@markerikson are you using the latest version of Storybook?
If that's the latest, could you open a new issue with a way to reproduce the issue.

**Comment by markerikson** [comment]
Ah... no, I'm not using Storybook at all, I'm just using `redbox-react` in my own application, and seeing this same error message.  Was curious exactly what you did to work around things.

**Comment by arunoda** [comment]
Actually, not we are using a our own error box. We don't use react-redbox anymore.
