### ISSUE TITLE
Do a full reload if needed

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#276]
Find out whether we need to do a full reload or not. If a full reload is needed, do it.

**Comment by orta** [comment]
Would love some kind of choice in the API here ( sometimes we have work happening on `init()` that doesn't get changed when switching between stories of the same component) would love to be able to declare that this should get a fresh virtual DOM.

**Comment by arunoda** [comment]
@orta you mean something like this? https://github.com/kadirahq/react-storybook/pull/285

**Comment by orta** [comment]
I think so, I'm still quite fresh to all these pieces

**Comment by arunoda** [comment]
We are doing this now with the latest version of Storybook. (2.14.0+)
