### ISSUE TITLE
Programmatically access defined stories

### ISSUE THREAD

**Issue by joscha** [kadirahq/react-storybook#277]
Is there a way to programmatically access defined stories? I am trying to run https://github.com/marmelab/gremlins.js against each of the stories defined, but in order to hit the right one in the iframe (#266) I need the story name. I tried exporting storiesOf(..).add(...) but there is no way to read them from that object.

**Comment by arunoda** [comment]
Try out extensions API: https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md

**Comment by joscha** [comment]
Thanks @arunoda. Adding an extension would work, but it basically would be something like:
```
setAddon({
  add1(storyName, storyFn) {
    this.stories = this.stories || [];
    this.stories.push(storyName);
    this.add(storyName, storyFn);
  },
});
```
which seems a bit silly, given that the information about defined stories must be kept inside the main object already. I think an `introspect(storObj)` with a method `.getAddedStories()` would be saner in the longterm.

**Comment by mnmtanish** [comment]
For reference: React Storybook has a `getStorybook` function which can be used to get all stories.
[source](https://github.com/kadirahq/react-storybook/blob/82cace8df34f9cb7f7908245d3c564088e8094b0/src/client/index.js#L7)
