### ISSUE TITLE
repeat

### ISSUE THREAD

**Issue by Maxhodges** [kadirahq/react-storybook#280]
often I want to repeat an element. Like if I have a complex `ui card` and I want several on the screen, is there a way to write an extension or something so I could have my `ui card` element repeat a few times?

```
storiesOf('Mailbox', module)
  .add('card view', () => (
    <div className="page header">
      <div className="ui container">
        <div className="ui cards">
          <div repeat="3" className="ui card">
...
```

**Comment by roonyh** [comment]
You can put javascript expressions inside JSX. So using [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to get an array of `ui card` elements works.

```
 storiesOf('Mailbox', module)
  .add('card view', () => (
    <div className="page header">
      <div className="ui container">
        <div className="ui cards">
          {[1,2,3].map(i => (<div className="ui card">stuff</div>))}
        </div>
```

**Comment by arunoda** [comment]
I think @roonyh answered this.
