### ISSUE TITLE
how to goto another story

### ISSUE THREAD

**Issue by Maxhodges** [kadirahq/react-storybook#281]
can we only create button based links?
```
storiesOf('Button', module)
  .add('with a text', () => (
    <button onClick={action('click the button')}>My First Button</button>
  ));
```

I'm using Semantic-UI, and we can have icons or menu items. Is there some way to hookup a click on an icon? or only buttons?

```
<onClick={action(linkTo('Mailbox', 'list view'))} className="list layout icon"></i>
```
I get result in the action logger
```
{
  args: [
    "[SyntheticEvent]",
    null,
    "[SyntheticEvent]"
  ]
}
```
but how do I actually make it jump to another story?

**Comment by arunoda** [comment]
You can simply use linkTo on any prop accept a callback function.

```js
<icon onClick={linkTo('Mailbox', 'list view')} className="list layout icon">...</icon>
```

**Comment by Maxhodges** [comment]
OK I see I had it in on the wrong element.
Cheers!

**Comment by flieks** [comment]
what if you want to navigate to the same storie after a value update ?
linkTo('module', handler) isn't working
thanks
