### ISSUE TITLE
issue with links in stories (iframe)

### ISSUE THREAD

**Issue by Maxhodges** [kadirahq/react-storybook#283]
I'd like to have links in my stories to docs and github files, but I get errors due to iframe. Any solutions?

![image](https://cloud.githubusercontent.com/assets/957271/16415027/19228882-3d76-11e6-9c66-1e2af3b9f983.png)

`Refused to display 'https://github.com/white-rabbit-japan/Semantic-UI-React-Storybook' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

**Comment by mnmtanish** [comment]
The web browser is refusing to load the Github page inside an iframe. This is a security feature and it protects users from some types of attacks. Try adding a `target` attribute to your links to open them in parent tab/window or a new tab/window.

**Comment by mnmtanish** [comment]
Try these

```html
<a href="https://github.com" target="_top">click here</a>
<a href="https://github.com" target="_blank">click here</a>
```

For more information:
https://developer.mozilla.org/en/docs/Web/HTML/Element/a
