### ISSUE TITLE
addDecorator in .storybook/config.js applied multiple times

### ISSUE THREAD

**Issue by Maxhodges** [kadirahq/react-storybook#284]
each time I save my story, the decorator is applied again i.e. while editing my story, if I save in my editor five times, it reloads the story in the browser, but the decorate is applied five times. Refreshing the browser will clear it.

![image](https://cloud.githubusercontent.com/assets/957271/16415297/86d5afc0-3d77-11e6-9610-160eab960e95.png)

**Comment by arunoda** [comment]
Yep. This is a good call.
We need to stop applying decorators, if it's a HMR change.

**Comment by Maxhodges** [comment]
for context, the decorator we used was in .storybook/config.js not directly in the story

https://github.com/white-rabbit-japan/Semantic-UI-React-Storybook/blob/master/.storybook/config.js#L5-L9

**Comment by mnmtanish** [comment]
@Maxhodges thanks for that info. It helped narrow down the issue.

**Comment by pcardune** [comment]
+1 for fixing this issue

**Comment by reauv** [comment]
Is there any progress on this? I've tried to create a workaround but no luck yet & I don't understand the code of storybook enough to create a pull request.

**Comment by mnmtanish** [comment]
Released `v1.40.0` with a fix

**Comment by michael-martin** [comment]
Can confirm 1.4.0 is working great for us, thanks @mnmtanish :)

**Comment by ritz078** [comment]
@mnmtanish can be closed.

**Comment by mnmtanish** [comment]
Yeah, thanks

**Comment by macrozone** [comment]
I got still the same error on react-native. any idea?
