### ISSUE TITLE
CLI option to specify Storybook configuration

### ISSUE THREAD

**Issue by kevin-wolf** [kadirahq/react-storybook#29]
Hello!

I've started using _react-storybook_ on a component library I am authoring and so far I like it. The only thing I haven't found on the docs and I think it can be better is the ability to specify the `config.js` path.

Maybe an option like `--config` on the cli?

**Comment by arunoda** [comment]
Okay. That's a good idea. May be it's the config dir.

**Comment by finneganh** [comment]
I'd second this. The config file is an important part of the overall codebase and it's hidden inside a dot-directory.

**Comment by kevin-wolf** [comment]
@arunoda I think it would be better to specify filepath rather than directory. On that way I can name the file whoever I want.

**Comment by arunoda** [comment]
@kevin-wolf We will have a few config files over the time. (Currently we've two)
So, it's better to have a directory.
