### ISSUE TITLE
full screen mode should persist on page refresh

### ISSUE THREAD

**Issue by jurgob** [kadirahq/react-storybook#291]
I thing a param like "&fullscreen=true" should be added on fullscreen mode, so it can persist on the occasionally page refresh

**Comment by jurgob** [comment]
yes it is working now, thanks

**Comment by arunoda** [comment]
Yep it is. Thanks @ritz078 for pointing this out.

**Comment by janwidmer** [comment]
same experience here, issue has been closed due to inactivity: https://github.com/storybooks/storybook/issues/3890

**Comment by maxharris9** [comment]
This is still broken for me in v4.1.12. Please reopen this!
