### ISSUE TITLE
Search both package.json and .babelrc for babel config

### ISSUE THREAD

**Issue by cesarandreu** [kadirahq/react-storybook#293]
Babel can be configured by adding a `babel` field to your `package.json`. Right now react-storybook only searches for `.babelrc`, but babel lets you use both.

**Comment by arunoda** [comment]
I'd like to have a PR for this :)

**Comment by arunoda** [comment]
Since now everyone is using `.babelrc` we won't go searching the package.json.
Having a single method is pretty great.
