### ISSUE TITLE
.storybook folder is a dotfile and ignored by default by eslint

### ISSUE THREAD

**Issue by joscha** [kadirahq/react-storybook#295]
currently `config.js` and `webpack.config.js` under `./.storybook` is ignored by default by eslint. As the dotfiles option of eslint (https://github.com/eslint/eslint/blob/fca067938fcd54c98945356b41c8c9a7dc404c04/tests/lib/ignored-paths.js#L91) can't be disabled on the command line, these files never get linted.

**Comment by arunoda** [comment]
Yep. May be you should change the config directory.
Check this: https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#configuration-directory

**Comment by arunoda** [comment]
I'm closing this in favour of above. If you are looking for something else, reopen with more info.

**Comment by huchenme** [comment]
can we reopen this issue? the above link does not work any more

**Comment by Hypnosphi** [comment]
You can pass config directory as a [CLI option](https://storybook.js.org/configurations/cli-options/#for-start-storybook):
```
start-storybook -c my-storybook-dir
```

Alternatively, you can put this line to your `.eslintignore` file:
```
!.storybook
```

**Comment by bsgreenb** [comment]
And don't forget to add the same line to `.prettierignore` if you're using that!

**Comment by LeandrodeLimaC** [comment]
If you are using a monorepo, chances are that you have to add a .eslintignore file at the root of the repository with the following content:

```
!.storybook
```

In my case, it was also necessary to add this file inside my storybook package.
