### ISSUE TITLE
Add base html tag to the iframe when building

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#296]
Most of the time, we host our storybooks in a subpath of the domain. So resources started with `/` doesn't work properly. 

So, we need add a `<base>` tag with a proper subdomain (and the path) to the iframe. This needs to be done, when building the storybook.

**Comment by roonyh** [comment]
This should go in the head tag right? Adding custom head content is already possible with the [head.html](https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#load-custom-html-head-content)

**Comment by arunoda** [comment]
Yeah. That's a good idea as well.
But, I need to make this pretty simple by providing an argument when we are building the storybook.

**Comment by roonyh** [comment]
Got it. I will work on this.

**Comment by arunoda** [comment]
We don't need now.
See: https://getstorybook.io/docs/configurations/serving-static-files#absolute-versus-relative-paths
