### ISSUE TITLE
How to test higher order components?

### ISSUE THREAD

**Issue by ffxsam** [kadirahq/react-storybook#297]
I'm trying to use Storybook to quickly test a [package of mine](https://github.com/ffxsam/formous), which is a higher-order component:

```js
storiesOf('Formous', module)
  .addDecorator(story => {
    return <MuiThemeProvider muiTheme={getMuiTheme()}>
      <div style={styles.root}>
        {Formous()(story())}
      </div>
    </MuiThemeProvider>
  })
  .add('normal', () => {
    //console.log(this.props);
   //...
```

That's not going so well :) Two questions:

1. How do I use Storybook to test higher-order components?
2. How do I access the props passed into the story component by Formous?

**Comment by arunoda** [comment]
Here `story()` returns a react element. So, you need to wrap it as a class  like this.

```
const Wrapper = () => (story());
{Formous()(Wrapper)}
```

**Comment by ffxsam** [comment]
Great, thanks! I'll give that a try.

**Comment by arunoda** [comment]
I am closing this now. But feel free to reopen.

**Comment by ffxsam** [comment]
This is what wound up working for me:

```js
storiesOf('Formous', module)
  .addDecorator(story => {
    const Wrapper = () => story();
    const Form = Formous(options)(Wrapper);

    return <Form />
  })
  .add('basic', () => (
    <div>
      <form>
        <input type="text" />
      </form>
    </div>
  ));
```

**Comment by ffxsam** [comment]
So in the example above, in the "basic" story, how would I access props passed in by `Formous`?
