### ISSUE TITLE
Unclear how to refresh state

### ISSUE THREAD

**Issue by schrepfler** [kadirahq/react-storybook#299]
I haven't seen an example in the documentation how to do a store.subscribe(render) if the render function is not really part of the story setup?
Ex. like this one https://github.com/schrepfler/storybook-counter

**Comment by arunoda** [comment]
Basically, storybook is for pure React Components which accepts data over props.
I saw that, you are passing a redux store to a component. That's not how to use React Storybook.

Just create a component, which accepts data via props. Connect redux store in another layer of components.

**Comment by arunoda** [comment]
There's a related PR in the progress as well: https://github.com/kadirahq/react-storybook/pull/285

**Comment by schrepfler** [comment]
Still, is this documented anywhere? For a complete beginner an example ow to "Connect redux store in another layer of components" would be very much appreciated. Feel free to take my code base as an example if you like and demo how it should be done.
