### ISSUE TITLE
Add proper windows support. 

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#300]
Seems like we use some bash features. See: #145 
We need to add some proper support for windows. 

cc @mnmtanish

**Comment by mnmtanish** [comment]
I think we can use [shelljs](https://www.npmjs.com/package/shelljs) to write scripts so it'll work on all platforms. Eg. `prepublish.js` instead of `prepublish.sh`.

I'm working on integrating Appetize.io to react-native-storybook these days. I'll get back to react-storybook as soon as it's ready.

**Comment by arunoda** [comment]
@mnmtanish sounds like a good plan.

**Comment by szopenkrk** [comment]
Its possible to fix that soon ?

**Comment by wallslide** [comment]
It's working for me on Windows now. Thanks!

**Comment by mnmtanish** [comment]
Fixed with #308
