### ISSUE TITLE
Support for GraphQL Mocks

### ISSUE THREAD

**Issue by raedle** [kadirahq/react-storybook#302]
Any suggestions on how to use Storybook together with GraphQL mocks? I think this could be really handy.

**Comment by kevinSuttle** [comment]
I wonder if looking through the Graphiql editor source could help. cc: @leeb 
https://github.com/graphql/graphiql

**Comment by arunoda** [comment]
@raedle could you tell me more about GraphQL mocks. Not sure, what exactly we can do with GraphQL.

**Comment by orta** [comment]
So, my example is in React-Native, but I don't think this should make too much of a difference. However, we are using relay, which _does_ matter.

I wanted to [write stories like this](https://github.com/artsy/emission/blob/f43068bf73914220bcc5b133cc706d0a80aa8ed9/stories/artist_articles_story.js#L28-L45):

```js 
  .add('Multiple Items', () => {
    const props = {
      articles: [{
        thumbnail_title : 'Example Article',
        href: '/artist/glenn-brown',
        id: '2',
        author : { name: 'Made by Orta' },
        thumbnail_image: { url: "" }
      }, {
      ...
    }]
    };
    return <StubContainer Component={ArtistArticles} props={props}/>;
```

So I created a component that emulates the work of really against a graphQL implementation:

```js
/* @flow */
'use strict';

import React from 'react';

// Emulates a Relay-compatible container, passing the data in directly.
// It's hard to know how well this can work for complicated examples. However,
// it's worked well enough so far - ./

export default class StubbedContainer extends React.Component {
  // Provide a stubbed context for child componentes
  getChildContext() {
    return {
      relay: {
        forceFetch: () => {},
        getFragmentResolver: () => {},
        getStoreData: () => {},
        primeCache: () => {}
      },
    route: { name: 'string' , params:{}, useMockData: true, queries: {}}
    };
  }

  // Directly render the child, and add the data
  render() {
    return <this.props.Component {...this.props.props} />;
  }

  // Needed to pass the isRelayContainer validation step
  getFragmentNames() {}
  getFragment() {}
  hasFragment() {}
  hasVariable() {}
}

// Expose dummy relay and a fake route
StubbedContainer.childContextTypes = {
  relay: React.PropTypes.object,
  route: React.PropTypes.object
};
```

In the end it means that our stories and either use relay, or use a stubbed relay to work with our GraphQL API. Note this is my first jump into react/react native, so it might not be 100%.

For full discussion on some of the trade-offs, see this PR: https://github.com/artsy/emission/pull/215

**Comment by arunoda** [comment]
@orta Great. This is awesome. Is it possible for you to wrap this component into a NPM package and add it to [here](https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md#available-extensions).

**Comment by arunoda** [comment]
I hope we've a fix here.

**Comment by pardesiaka08** [comment]
Hi, I am facing an issue on integrating storybook with gatsby.As my gatsby site consists of components which uses graphql queries which are giving an error.Is there any solution to create storybook for such components.

**FooterSocialIcons component**
import React from 'react'
import { StaticQuery, graphql,Link } from "gatsby"
const FooterSocialIcons = (props)=>(
    <StaticQuery
    query={graphql`
    query{
        fbLogo: file(relativePath: { eq: "icon-green-fb.svg" }) {
          publicURL
        }
        twLogo: file(relativePath: { eq: "icon-green-tw.svg" }) {
          publicURL
        }
        ytLogo: file(relativePath: { eq: "icon-green-yt.svg" }) {
          publicURL
        }
        pinLogo: file(relativePath: { eq: "icon-green-pin.svg" }) {
          publicURL
        }
      }
    `}
    // render={data => { return <img src={data.fbLogo.publicURL} />}}
      render={data => { 
                return (
                    <div className="social-icons-div">
                        <div className="social">
                         <div>
                            <Link to="https://www.facebook.com/KeeblerElves/" aria-label="Redirects to Kelloggs 
                              FacebookPage"><img src={data.fbLogo.publicURL} alt="fb" /></Link>
                         </div>
                         <div>
                             <Link to="https://twitter.com/keeblerelves" aria-label="Redirects to Kelloggs 
                               TwitterPage"><img src={data.twLogo.publicURL} alt="tw"/></Link>
                         </div>
                         <div>
                             <Link to="https://www.youtube.com/channel/UChH5SIf95NpjRbIgRJzDDPQ"aria- 
                              label="Redirects to Kelloggs youtubePage"><img src={data.ytLogo.publicURL}alt="yt" 
                           /></Link>
                         </div>
                         <div>
                             <Link to="https://www.pinterest.com/keebler/" aria-label="Redirects to Kelloggs 
                           PinterestPage"><img src={data.pinLogo.publicURL} alt="pin" /></Link>
                         </div>
                         </div>
                        
                    </div>
                    
                )
            }
        }
    />
)
export default FooterSocialIcons


**Storybook for FooterSocialIcons Component**
import React from "react";
import { storiesOf } from "@storybook/react";
import FooterSocialIcons from './footerSocialIcons';


storiesOf("FooterSocialIcons", module).add(
  "with diffent SocialIcons",
  () => (
      <FooterSocialIcons></FooterSocialIcons>
    
   
  ),
  { info: "It should show social icons with links" }
);


**Error while creating the storybook for this component**
It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away,. Unfortunately, something went wrong and the query was left in the compiled code. .Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.
    Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away,. Unfortunately, something went wrong and the query was left in the compiled code.

.Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.

Any solution please let me know

**Comment by pardesiaka08** [comment]
Hi, I am facing an issue on integrating storybook with gatsby.As my gatsby site consists of components which uses graphql queries which are giving an error.Is there any solution to create storybook for such components.

**footerSocialIcons Component**

import React from 'react'
import { StaticQuery, graphql,Link } from "gatsby"
const FooterSocialIcons = (props)=>(
    <StaticQuery
    query={graphql`
    query{
        fbLogo: file(relativePath: { eq: "icon-green-fb.svg" }) {
          publicURL
        }
        twLogo: file(relativePath: { eq: "icon-green-tw.svg" }) {
          publicURL
        }
        ytLogo: file(relativePath: { eq: "icon-green-yt.svg" }) {
          publicURL
        }
        pinLogo: file(relativePath: { eq: "icon-green-pin.svg" }) {
          publicURL
        }
      }
    `}
      render={data => { 
                return (
                    <div className="social-icons-div">
                        <div className="social">
                         <div>
                            <Link to="https://www.facebook.com/KeeblerElves/" aria-label="Redirects to Kelloggs FacebookPage"><img src={data.fbLogo.publicURL} alt="fb" /></Link>
                         </div>
                         <div>
                             <Link to="https://twitter.com/keeblerelves" aria-label="Redirects to Kelloggs TwitterPage"><img src={data.twLogo.publicURL} alt="tw"/></Link>
                         </div>
                         <div>
                             <Link to="https://www.youtube.com/channel/UChH5SIf95NpjRbIgRJzDDPQ"aria-label="Redirects to Kelloggs youtubePage"><img src={data.ytLogo.publicURL}alt="yt" /></Link>
                         </div>
                         <div>
                             <Link to="https://www.pinterest.com/keebler/" aria-label="Redirects to Kelloggs PinterestPage"><img src={data.pinLogo.publicURL} alt="pin" /></Link>
                         </div>
                         </div>
                        
                    </div>
                    
                )
            }
        }
    />
)
export default FooterSocialIcons


**Storybook for FooterSocialIcons Component**

import React from "react";
import { storiesOf } from "@storybook/react";
import FooterSocialIcons from './footerSocialIcons';


storiesOf("FooterSocialIcons", module).add(
  "with diffent SocialIcons",
  () => (
      <FooterSocialIcons></FooterSocialIcons>
    
   
  ),
  { info: "It should shows social icons with links" }
);

**Error while creating the storybook for this component**

It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away,. Unfortunately, something went wrong and the query was left in the compiled code. .Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.
    Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away,. Unfortunately, something went wrong and the query was left in the compiled code.

.Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.

Any solutions?
