### ISSUE TITLE
1.37.0 - Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client'

### ISSUE THREAD

**Issue by PEM--** [kadirahq/react-storybook#306]
Specific to 1.37.0:
```
ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/PEM/Projects/panoply/app
 @ multi preview

ERROR in ./.storybook/config.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory  "/Users/PEM/Projects/panoply/app/.storybook"
    at /Users/PEM/Projects/panoply/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
...
```

Node version: v6.3.0
NPM version: 3.10.5

After reverting to react-storybook 1.36.0, everything went fine again.

**Comment by necolas** [comment]
I'm having this issue too. Many modules can't be resolved. Including 'redux', which isn't a dependency of this repo :/

**Comment by danderu** [comment]
@PEM-- I was having the same issue, thanks for reporting and saying the solution! (revert to 1.36.0).

**Comment by arunoda** [comment]
I just released a new version of `v1.37.1` by replacing `v1.37.0`.
It just contains the pre-published code of `v1.36.0`.

It will work on a proper fix.

**Comment by Moezalez** [comment]
Make also sure you run NPM3.

**Comment by PEM--** [comment]
Works like a charm. Thanks 👏

**Comment by arunoda** [comment]
See: #305 for more info.
