### ISSUE TITLE
Remove dist folder from github

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#309]
Anyways `dist` is never supposed to be on github. Its preferable to build files before `publish`

Reasons:

* unnecessary clutter in PR
* irritating conflicts in dist

**Comment by roonyh** [comment]
Having dist folder in source control allows storybook to be installed from github in addition to npm. See #218.

I think its fine if you just submit src changes in your PRs if you like (thanks for those PRs btw :), since we do a new commit for each new version with dist changes.

**Comment by arunoda** [comment]
@ritz078 It's the case a @roonyh mentioned.
I am gonna close this. 
Just reopen this, if we have a much better solution.

**Comment by ritz078** [comment]
Are we recommending to use it from github directly ? In #218 too he tried npm but couldn't get it to work. So we can build the dist just before publishing and remove it after publishing if we are concerned about npm.

**Comment by arunoda** [comment]
It's not like that. He (or someone) want to use GitHub URL as the source for the package. So, that's why we need to put dist on the GitHub.

**Comment by ritz078** [comment]
cool then :)
