### ISSUE TITLE
Svg images do not have the correct MIME type on storybooks.io

### ISSUE THREAD

**Issue by k88hudson** [kadirahq/react-storybook#310]
Hi there!

I noticed while using storybooks.io that svgs are being served by your proxy as `text/plain`. This makes them not show up in our UI 😢 

I am using the `-s` param for the `build-storybook` to serve static images.

Example:
![screenshot of devtools](https://k88hudson-screenshots.s3.amazonaws.com/screen-shots/Screen_Shot_2016-07-13_at_5.35.26_PM.png)

**Comment by roonyh** [comment]
@k88hudson Thanks for reporting this and sorry about the issue. We just did a new release and this should be fixed now. Could you please verify?

**Comment by k88hudson** [comment]
Awesome, thanks so much! Verified fixed 💃

**Comment by arunoda** [comment]
cool.
