### ISSUE TITLE
More declarative way of adding stories?

### ISSUE THREAD

**Issue by xyc** [kadirahq/react-storybook#312]
Say we have an `addStories` method:
```js
const addStories = (stories) => {
  Object.keys(stories).forEach(key => {
    let story = storiesOf(key, module)
    stories[key].forEach(args => {
      story = story.add.apply(null, args)
    })
  })
}
```

then we can reduce some boilerplates and be more declarative:
```js
const stories = {
   'Button': [
        ['with text', () => (<button onClick={action('clicked')}>My First Button</button>)],
        ['with no text', () => (<button></button>)],
    ],
}

addStories(stories)
```

**Comment by mnmtanish** [comment]
Hi @xyc . It can be done with an [addon](https://github.com/kadirahq/react-storybook/blob/master/docs/extensions.md#addons). @jurgob wrote something similar [here](https://github.com/jurgob/react-storybook-addon-add-stories-group).

**Comment by arunoda** [comment]
Hope we can close this.
