### ISSUE TITLE
How add mock props

### ISSUE THREAD

**Issue by szopenkrk** [kadirahq/react-storybook#316]
HI guys i have isssue.
I'm use this.props.something and cant specyfy in storybook that value like 
```
 static defaultProps = {
  fields: [
      {
        id: 'email',
        constraints: [
          { validator: (val) => /.@./.test(val) },
        ],
        isValid: true,
      }
} 
```
To use that like 

```
  <form action={this.props.action}
                          method={this.props.method}
```

Where i should add that for element line stories/MainSection.js ?

**Comment by arunoda** [comment]
We don't have a built in way to mock props. But you can use any JS module for that inside your Storybook.

Also we've added props editing support: https://github.com/kadirahq/storybook-addon-knobs
