### ISSUE TITLE
How to import jQuery into global namespace (for Semantic UI)

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/react-storybook#327]
Hi. I'm trying to use Semantic UI and I'm fading all css from it. The problem is that Semantic UI expects jQuery in the global namespace. I tried following to import it, but I still get 'jQuery' is not defined.

```js
//file: config.js

import jquery from 'jquery';

global.$ = jquery;
global.jQuery = jquery;

import './semanticui'
```

Any idea how can this be achieved ?

**Comment by tomitrescak** [comment]
Ok, this seemed to do a trick, when I put this code into my main `.stories/index` file.

```js
import jquery from 'jquery';
global.$ = jquery;
global.jQuery = jquery;
require('./semanticui');
```

**Comment by purplecones** [comment]
Thanks for this @tomitrescak 

I decided to `npm install semantic-ui-css --save-dev` package and import the files directly from it like so
```javascript
// config.js
import jquery from 'jquery';
global.$ = jquery;
global.jQuery =  jquery;
require('semantic-ui-css/semantic.css');
require('semantic-ui-css/semantic.js');
```

**Comment by darekkay** [comment]
I've had issues integrating **jQueryUI**, so here's how I did it. It uses the [jquery-ui](https://www.npmjs.com/package/jquery-ui) module.

```js
// config.js
import jquery from 'jquery';
import jQueryAutocomplete from "jquery-ui/ui/widgets/autocomplete";
import jQueryDatepicker from "jquery-ui/ui/widgets/datepicker";

jquery.autocomplete = jQueryAutocomplete;
jquery.datepicker = jQueryDatepicker;
global.$ = jquery;
global.jQuery =  jquery;
```
