### ISSUE TITLE
Add TypeScript Definition

### ISSUE THREAD

**Issue by Gi972** [kadirahq/react-storybook#33]
Hello,

Good Tool, can you add a TypeScript Definition for use with *.tsx files.

Thanks

Gi

**Comment by tomitrescak** [comment]
Is this what you are after? @arunoda you can maybe add it? Or do you want a PR?

```
declare var module: any;

declare module "@kadira/storybook" {
  interface Story {
      add (storyName: string, callback: Function): Story;
  }

  export function storiesOf(name: string, module: any): Story;
  export function action(name: string): void;
}
```

**Comment by tomitrescak** [comment]
You also need to extend your definition of webpack.config.js to following. @arunoda, resolving jsx should be supported by default in my opinion. 

```
const path = require('path');
module.exports = {
  module: {
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        query: { presets: ['react', 'es2015', 'stage-2'] },
        exclude: [path.resolve('./node_modules'), path.resolve(__dirname, 'node_modules')],
        include: [path.resolve('./'), __dirname],
      },
      {
        test: /\.css?$/,
        loaders: [ 'style', 'raw' ],
        include: path.resolve(__dirname, '../')
      }
    ]
  }
};
```

**Comment by tomitrescak** [comment]
Hmm, resolving does not seem to work .. not sure why .. the jsx files are not resolved ;(

**Comment by arunoda** [comment]
@tomitrescak I am not good with TS, yes send me a PR. 
Also add .configure() method as a definition. 

BTW, how TS and .jsx extentions are related?

**Comment by tomitrescak** [comment]
tsx are compiled into jsx in some configurations (e.g. mine). I am not using typescript loaders or typescript compiler in Meteor, but am compiling TS files into JS. This is faster and more controllable.

**Comment by arunoda** [comment]
Okay. got it.
I took the jsx PR and now in master. 
Will do a release in few hours.

**Comment by arunoda** [comment]
BTW: could you work on the TS definition file. Not sure where to add it.

**Comment by Gi972** [comment]
Thanks guys!

The best place for typescript definition  is on the definitelytyped site.
http://definitelytyped.org/

it's a catalogue for typescript definition.

**Comment by tomitrescak** [comment]
@Gi972 I submitted a pull request, yet they need to include a test file with it as well. And I have noo idea what to put in those tests. Have you done a PR there before? 

I also have a full d.t.s definition for Mantra ready, which I'm using personally and I can share it .. yet again .. no idea what tests should be there.

**Comment by tomitrescak** [comment]
Another problem is that storybook does not have a npmjs page, therefore it is not recognised by the DT CI workflow.

**Comment by arunoda** [comment]
We have a NPM page. 
See: https://www.npmjs.com/package/@kadira/storybook/

**Comment by tomitrescak** [comment]
Yea, I know, but the silly CI scrip only check for high level npmjs addresses such as https://www.npmjs.com/package/storybook/

**Comment by Gi972** [comment]
hello Tomitrescak , I never make PR before, I don't know how it works.
For the test , I think you have already tcheck it : http://definitelytyped.org/guides/contributing.html#tests

It's right, I never saw the npm module name like @username/module-npm-Name  I think it's not very conventional.
Does you think rename it  like it:   https://www.npmjs/package/storybook after @arunoda ?   
It will better for the future not for only this case.

**Comment by arunoda** [comment]
@Gi972 yes it not. That's something NPM introduce recently. This is very important because of the recent NPM related issues.

If that user have used a scoped package, there may not such an issue.

**Comment by dgsunesen** [comment]
How far are you with supporting .tsx files?

In my `.storybook/webpack.config.js` I have the following configured for typescript files:

```
const path = require('path')

module.exports = {
  module: {
    loaders: [
      { test: /\.(ts|tsx)$/, loader: 'ts-loader' }
    ]
  }
}
```

However, it does not seem to work. Sad panda.

**Comment by camwest** [comment]
Definitely Typed is deprecated in favour of https://github.com/typings/typings. It's much easier to add to.

**Comment by tomitrescak** [comment]
Great catch! I'll add it as soon as I'll have a bit of time.

**Comment by tomitrescak** [comment]
@camwest I simply do not have the time. Yet, @arunoda, if you make the typings part of your package (above), it can be easily added to the typings repository.

**Comment by arunoda** [comment]
@tomitrescak You mean, use typescript?

**Comment by tomitrescak** [comment]
No, making the typescript definition as a part of the package and including it in package.json:

```
// file typings.d.ts
declare var module: any;

declare module "@kadira/storybook" {
  interface Story {
      add (storyName: string, callback: Function): Story;
  }

  export function storiesOf(name: string, module: any): Story;
  export function action(name: string): void;
}
```

and in package.json

```
"typings": "./lib/foo.d.ts"
```

More info ... http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

Do you want a PR for this?

**Comment by arunoda** [comment]
Why not. Send me a PR.

**Comment by arunoda** [comment]
@tomitrescak This is merged and released with `v1.20.0`. What else do we need to have to do?

**Comment by tomitrescak** [comment]
All you need to do is enjoy the smiles of Typescript developers that will love you for this;) and occasionally update the typing when API changes. If you'll need help, just ping me. Thanks!

**Comment by tomitrescak** [comment]
And you can close this now. Thanks!

**Comment by arunoda** [comment]
Thanks @tomitrescak. 
I think I can update the def file with API changes :)

**Comment by Gi972** [comment]
@tomitrescak @arunoda 
Guys thanks a lot for your time

;-)

**Comment by BoizZ** [comment]
@tomitrescak 
```
Module not found: Error: Cannot resolve 'file' or 'directory' ../stories
```
