### ISSUE TITLE
React version

### ISSUE THREAD

**Issue by alanzanattadev** [kadirahq/react-storybook#336]
Hi,

Some react bugs are not fixed because it still use React@15.0.0 instead of React@15.2.1, can we update it and push the update to npm please ?

Thank you :)

**Comment by arunoda** [comment]
Yes sure. @mnmtanish do this when we are updating a new version.

**Comment by arunoda** [comment]
Anyway, React version is only relevant for our UI code only. For your component's it'll use your app's version.

**Comment by arunoda** [comment]
This is fixed in a recent version.
Anyway this is not a bug.
