### ISSUE TITLE
Question: Passing 'module' everywhere - what for?

### ISSUE THREAD

**Issue by raveclassic** [kadirahq/react-storybook#338]
Hi!

Could you please explain why do you need to pass `module` to `ConfigApi#configure` and to `ClientApi#storiesOf`. Does this somehow mean usage of different `module` apis? If so, could you please provide an example.
Otherwise it seems unnecessary to require passing `module` and it can be omitted.

**Comment by arunoda** [comment]
That's for hot module replacement. We use HMR api attached to the module.
It's necessary.

**Comment by raveclassic** [comment]
Ah I see now, thanks. 
Sorry about writing to closed issue but have you tried this approach for enabling HMR for React components? https://github.com/gaearon/react-hot-loader
It seems more user-friendly to developers allowing them not to pass `module` by hand.

**Comment by arunoda** [comment]
@raveclassic yes I have.
It's for another reason. Our use case is different and how we use it.

**Comment by raveclassic** [comment]
@arunoda Ok thanks for explanation anyway
