### ISSUE TITLE
Add support for publicPath. 

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#344]
When deploying to production sites, it's better to provide a public URL. We can use webpack's publicPath field for that. 

We can provide a cli argument for this. React Create App looks for the homepage field of the package.json for this.

**Comment by arunoda** [comment]
We don't use this and we don't need this.
You can deploy to any domain without any issues.

But for images, you need to do something. Check this: https://getstorybook.io/docs/configurations/serving-static-files#absolute-versus-relative-paths

**Comment by ccutch** [comment]
Link is broken

**Comment by Hypnosphi** [comment]
@ccutch thanks, updated that
