### ISSUE TITLE
JSX files not resolved

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/react-storybook#35]
I'm creating a spearate issue following on #33 when it is not possible to use typescript with storybook as jsx files are not resolved and storybook is concerned only with js files. Here is what I attempted yet it does not work:

```
const path = require('path');
module.exports = {
  module: {
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        query: { presets: ['react', 'es2015', 'stage-2'] },
        exclude: [path.resolve('./node_modules'), path.resolve(__dirname, 'node_modules')],
        include: [path.resolve('./'), __dirname],
      },
      {
        test: /\.css?$/,
        loaders: [ 'style', 'raw' ],
        include: path.resolve(__dirname, '../')
      }
    ]
  }
};
```

**Comment by arunoda** [comment]
There is a PR for JSX and I will take it as soon week started.

So, what about the type script, I didn't get it.

**Comment by tomitrescak** [comment]
Not much, just adding a .d.ts definition will help typescript developers write typescript rich stories.

**Comment by tomitrescak** [comment]
If the PR will work we can close this.

**Comment by arunoda** [comment]
So you mean you got it configured for type script properly?

**Comment by tomitrescak** [comment]
No, it does not resolve jsx files currently .. will wait for your PR.

**Comment by arunoda** [comment]
Will do it ASAP, I get to the office.
