### ISSUE TITLE
Can't use storybook ^2.0.0 when babel-loader is defined in preLoaders

### ISSUE THREAD

**Issue by PTihomir** [kadirahq/react-storybook#352]
Hi!

My webpack configuration is something like this:
``` javascript
{
  entry: {...},
  output: {...},
  module: {
    noParse: [/moment.js/],
    loaders: [
      { test: /\.json$/, loaders: ['json'] },
      { test: /\.scss$/, loaders: [ 'style', 'css', 'postcss', 'sass' ] },
      { test: /\.css$/, loaders: [ 'style', 'css?-minimize', 'postcss' ] },
      { test: /\.(ttf|eot|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loaders: [ 'file?name=[name].[ext]' ] },
      { test: /\.svg$/, loaders: [ 'file?name=[name].[ext]', 'svg-process' ] },
    ],
    preLoaders: [
      {
        test: /\.js$/,
        loader: 'rebem-layers',
        exclude: /node_modules/,
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          cacheDirectory: true,
          env: {
            development: {
              presets: [ 'react-hmre' ],
            },
          },
        },
      },
      {
        test: /\.js$/,
        loader: 'eslint-loader',
        exclude: /node_modules/,
      },
    ],
  },
```

The problem is as I see is, that storybook 2.0.0 defines the new default webpack config. There a default babel-loader is probably defined, and my configuration is not overriding that. I am assuming this also from the fact, that running storybook is now very slow and it shows that babel is trying to transpile everything from node_modules (which is excluded in my configuration).

Reverting to storybook 1.41.0 version was my temporary solution.

**Comment by arunoda** [comment]
Could you try to use the latest of 2.x. Once you use a custom webpack setup, it'll stop using the default config.

Anyway, is it possible for you to send me a small repo with your bug. So, I can work on it quickly.

**Comment by PTihomir** [comment]
Here is the sample project: https://github.com/PTihomir/storybook-test-project

One note. This is a simplified project. When I cleaned it up, I installed storybook with the command
`npm install @kadira/storybook`.

Then by running `npm run storybook` I got some errors in the browsers console log.

Uninstalling and installing version 1.41.0 with `npm install @kadira/storybook@1.41.0` worked, storybook was running without errors. Then unistalling and installing 2.1.1 `npm install @kadira/storybook@2.1.1` provided another type of error, the same one I described in the inital comment. It prints in bash some messages which seems to imply that my webpack config is ignored.

**Comment by arunoda** [comment]
@PTihomir thanks for the repo. I'll have a look at this.

**Comment by arunoda** [comment]
@PTihomir yeah that's hugely slow.
Try using `v2.2.0`. It'll fix this issue.

BTW: I had to add following changes to get your app working:

```patch
diff --git a/.npmrc b/.npmrc
deleted file mode 100644
index 9966be3..0000000
--- a/.npmrc
+++ /dev/null
@@ -1,2 +0,0 @@
-progress=false
-;registry=http://0.0.0.0:8888/
diff --git a/.storybook/config.js b/.storybook/config.js
index 2d46a61..899733c 100644
--- a/.storybook/config.js
+++ b/.storybook/config.js
@@ -1,6 +1,6 @@
 import { configure } from '@kadira/storybook';
 
-const requireContext = require.context('../stories/', true, /((?!index).)*\.js$/);
+const requireContext = require.context('../storiess/', true, /((?!index).)*\.js$/);
 
 function loadStories() {
   requireContext.keys().forEach(requireContext);
diff --git a/.storybook/webpack.config.js b/.storybook/webpack.config.js
index beb11d7..41bb760 100644
--- a/.storybook/webpack.config.js
+++ b/.storybook/webpack.config.js
@@ -1,5 +1,5 @@
 /* eslint no-var: 0, vars-on-top: 0 */
 // require('babel/register');
 require('babel-register');
-var webpackConfig = require('../build/webpack-environments/development.js');
+var webpackConfig = require('../build/webpack-environments/common.js');
 module.exports = webpackConfig.default;
diff --git a/package.json b/package.json
index bd78a03..ecb292d 100644
--- a/package.json
+++ b/package.json
@@ -43,7 +43,7 @@
     "unist-util-visit": "^1.1.0"
   },
   "devDependencies": {
-    "@kadira/storybook": "^2.1.1",
+    "@kadira/storybook": "^2.2.0",
     "babel-cli": "^6.11.4",
     "babel-eslint": "6.1.x",
     "babel-loader": "6.2.x",

```

**Comment by PTihomir** [comment]
Sorry about the wrong path :) I was checking if some of the stories affect the whole picture, and after that I forgot to revert.

I will try the newer version on our full project.

**Comment by PTihomir** [comment]
I can confirm that v2.2.0 fixes my issue and now everything works as expected.

**Comment by arunoda** [comment]
Great. Awesome.
