### ISSUE TITLE
Uncaught TypeError: $export is not a function

### ISSUE THREAD

**Issue by Nickman87** [kadirahq/react-storybook#358]
I've just updated to the latest react-storybook 2.1.1 and with our old configuration I'm now getting the following error:

```
Uncaught TypeError: $export is not a function @	es6.object.define-property.js?6967:2
```

which relates to this piece of code
```
var $export = require('./_export');
// 19.1.2.4 / 15.2.3.6 Object.defineProperty(O, P, Attributes)
$export($export.S + $export.F * !require('./_descriptors'), 'Object', {defineProperty: require('./_object-dp').f});


/** WEBPACK FOOTER **
 ** node_modules/core-js/library/modules/es6.object.define-property.js
 **/
```

By adding `exclude: /node_modules/,` to the webpack config, the error goes away and everything seems to work fine.

Is there a reason you do not exclude the node modules, or do you need more information to debug this?
We have a custom css setup in an extra webpack.config file, not sure if this has any impact on the javascript compilation?

**Comment by arunoda** [comment]
@Nickman87 we just released `v2.2.0`. Could you try that?
I hope it'll fix this issue.

**Comment by Nickman87** [comment]
Hi @arunoda, this has indeed solved the issue for me, awesome :).
It also fixes https://github.com/kadirahq/react-storybook/issues/289 for me, so maybe that issue can be closed now?

**Comment by arunoda** [comment]
Awesome.
