### ISSUE TITLE
Modules and NPM2

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#360]
@mnmtanish I just implemented NPM2 support for storybooks.
See: #356 

It'll work with current modules.
But I want to know about how it will work with custom modules (user supplied modules.)

Could you possible to do some review on this.

> If there's an issue, we could alias core module repos with `require.resolve`

**Comment by mnmtanish** [comment]
We can try a few open source repos with customised storybook and see whether it works with npm2. We can try repos with custom `.babelrc` files and webpack config files. If you know any, I can check them out.

**Comment by arunoda** [comment]
I think this is working pretty greatly.
