### ISSUE TITLE
How to make changes to components after render?

### ISSUE THREAD

**Issue by lorensr** [kadirahq/react-storybook#364]
I have:

```js
storiesOf('BankForm', module)
.addWithInfo('blank', () => {
  return (
    <StoryWrapper>
      <BankForm
        onSubmit={action('onSubmit')}
      />
    </StoryWrapper>
  )
})
```

I would like to add another story that has some form fields filled in with certain values, but I don't want to add to the `BankForm` API/proplist. What's the best way to do this?

**Comment by arunoda** [comment]
Hey, didn't get this. 
Could you give more info?

Are you looking to render another story inside another one. 
Or jump to another story or something else?

**Comment by lorensr** [comment]
Hi! Sure, sorry. My `<BankForm>` has a few input fields. In the above story, the fields are blank. I would like to have a story where some of the fields are filled in, eg with "Loren Sands" and "000222094". Like `$('form > input').val('Loren Sands')`. Where's the best place to put that code (or something similar)?

**Comment by arunoda** [comment]
Hmm. Seems like you need to prefill some data. So, using jquery is not good.

Best way is to provide some props where you can send defaults for user inputs. Then you can create a helper function to stop writinng defaults in every story.

**Comment by lorensr** [comment]
Is there a way to do it without adding to the component's API / proplist?

On Mon, Aug 8, 2016 at 1:09 AM, Arunoda Susiripala <notifications@github.com

**Comment by arunoda** [comment]
Then it's not storybook related stuff, but it's more generic one. You can get the DOM of the children from the `StoryWrapper` component and then manipulate it.

But i don't recommend it.

Other way is to expose some instance function and call it by getting the react ref. 
I think you could get more help from posting to StackOverflow.
