### ISSUE TITLE
getstorybook -f overwrites existing stories

### ISSUE THREAD

**Issue by michaelryancaputo** [kadirahq/react-storybook#365]
Use case:
Creating react components that will be used in a private npm registry. To init the storybook app to view/make changes, it needs to be reinitialized. The only way to do this seems to be to run `getstorybook -f` which seems to overwrite any changes to the `/stories` folder.

A user should be able to pull a repo containing a storybook component and initialize a storybook app that does not overwrite work.

**Comment by arunoda** [comment]
Could you give me more info on this.
For that, I don't think you need to `getstorybook -f`.

Just invoking `npm install` is sufficient I guess.
Tell me more, I'll try to think more.

**Comment by michaelryancaputo** [comment]
Thanks,
running `npm i` does install the packages, but it doesn't include the storybook configurations. When I pull my repo, after running an npm install, I get the following error: `Error: => Create a storybook config file in "./.storybook/config.js".` - I guess this file isn't included in the repository i'm committing, which can be remedied, but I'm guessing others may have this problem as well and it could be improved.
Thank you for responding so quickly.

**Comment by arunoda** [comment]
@michaelryancaputo The thing is you need to commit the files created by `getstorybook` after you've done any changes.

I hope that's the issue here. Or could you give me a sample repo or some other way we could re-produce this locally. Then I can dive more.

**Comment by michaelryancaputo** [comment]
Ok, it seems like there is a `.gitignore` somewhere stopping me from being able to add the config file without forcing it. I don't see it anywhere in my path.

I guess that is the only way to do this. Thank you for your prompt reply.

Please close this if you are satisfied with this answer.

Thanks again.

**Comment by arunoda** [comment]
great.
