### ISSUE TITLE
v2.x is incompatible with webpack v2.x projects

### ISSUE THREAD

**Issue by mattkime** [kadirahq/react-storybook#367]
storybook v2.x has `extract-text-webpack-plugin@1.0.1` as a dependency. `extract-text-webpack-plugin@1.0.1` has webpack ^1.9.11 as a peer dependency.

This means you'll get an 'unmet peer dependency' WARNing on `npm install`. This is fine if you're playing npm version roulette but if you're locking down your dependency revisions with `npm shrinkwrap` it'll refuse to write the `npm-shrinkwrap.json` file. This is reasonable as you have an incompatible set of dependencies.

The simple solution is to downgrade storybook to v1.x which lacks the `extract-text-webpack-plugin@1.0.1`dependency. The better solution would be to completely separate the dependency concerns of storybook and your app. I'm not sure how this is best achieved but suspect it would entail having a separate project for your storybook setup while providing some way for it to locate your app code.

I think the simple solution would be to add this to the known issues. (unless the dependency could be trimmed? i might be overlooking that) Past that, it would be worthwhile to document how storyboard-separate-from-your-app would work.

**Comment by arunoda** [comment]
I think for now, we could remove the `extract-text-webpack-plugin`. We are not using it yet. Could you send me a PR for that?

**Comment by mattkime** [comment]
thanks @arunoda  - just curious if you could publich v2.2.2 to npm

**Comment by arunoda** [comment]
oops. Just did it.
