### ISSUE TITLE
Addon channel not being called for changing stories

### ISSUE THREAD

**Issue by kesne** [kadirahq/react-storybook#370]
I've been playing with the new panel addon api, and so far it's great! One thing I noticed was missing was that the `selectStory` event is not called when one of the story links in the left pane was clicked. This would be useful so that you can change the bottom panel content based on the currently selected story.

**Comment by arunoda** [comment]
For that you can listen one of our other API. (Which is not documented yet.) But I can show you a sample.

See this [onStory api](https://github.com/kadirahq/getstorybook.io/blob/master/.storybook/notes_addon.js#L42). With that, you can listen for the story changes.

**Comment by arunoda** [comment]
I think we have solution for this.
