### ISSUE TITLE
The webpack watch dosn't rebuild when I perform npm run storybook 

### ISSUE THREAD

**Issue by qiangege** [kadirahq/react-storybook#371]
> this is my demo
here:https://github.com/qiangege/react-storybook-demo.git

first
 I perform `npm run storybook `
 now, I  change content of the files in node_modules,the webpack can rebuild

then
I open  another  service, don't  close `npm run storybook`, I perform `npm install range-input-react`  or  `npm install`. now , I  change content of the files in node_modules,the webpack dosn't  rebuild,

this question is very  strange.
What should I do to solve this problem

**Comment by arunoda** [comment]
You mean, when you install new NPM modules, storybook webpack cannot determine that. Is it?

**Comment by qiangege** [comment]
step  npm run storybook  > npm install a modules > change a file 
it's not rebuild the project   webpack watch it's not working .
you can try it.

**Comment by arunoda** [comment]
Okay. Got it. I know how to fix this.
Note: Use CRA's [WatchMissingNodeModulesPlugin](https://github.com/facebookincubator/create-react-app/blob/master/scripts/utils/WatchMissingNodeModulesPlugin.js).

**Comment by abnerCrack** [comment]
@arunoda  
The first, thinks for your project.it's very great
About this problem I have a suggestion
 see that:
https://www.npmjs.com/package/npm-install-webpack-plugin
npm-install-webpack-plugin

**Comment by arunoda** [comment]
@abnerCrack This plugin does too much.
We don't want to save NPM packages and others. We just need to detect changes.
The plugin I mentioned above would work fine for this usecase.

PRs welcome :)

**Comment by abnerCrack** [comment]
@arunoda  TOT.ok~~~~

**Comment by arunoda** [comment]
We've fix this (original issue by @qiangege) with the latest Storybook.
Reopen if that doesn't fix your issue.
