### ISSUE TITLE
build-storybook chunk hash assets

### ISSUE THREAD

**Issue by stipsan** [kadirahq/react-storybook#372]
Hey guys,

If you look at the source of [uikit-react.io](https://uikit-react.io) (built using standard `storybook-to-ghpages`) this is how the script is loaded:

```
<script src="static/manager.bundle.js"></script>
```

Is it possible to configure it to use the chunkhash feature of webpack?
To generate something like this:

```
<script src="static/manager.bundle.14hhgd29if.js"></script>
```

That way the long term caching setup on the domain (using Cloudflare CDN) is automatically busted when we deploy. Otherwise we have to turn off caching all together or people won't see stories we add as we publish new versions of `uikit-react`.

Thank you for any help :)

**Comment by arunoda** [comment]
Yep. This is good feature we need to work on.

**Comment by arunoda** [comment]
Now we've this feature.
We are not using webpack's feature. But it does the work done.
See: https://github.com/kadirahq/react-storybook/pull/578

**Comment by stipsan** [comment]
that's awesome, thanks! 👍
