### ISSUE TITLE
How to require all stories?

### ISSUE THREAD

**Issue by lnmunhoz** [kadirahq/react-storybook#373]
It is possible to require all stories using like [node-glob](https://github.com/isaacs/node-glob) in the `config.js` file?

I tried but there something wrong happening when `glob` tries to access my `src` path. Maybe I am doing something wrong, but I would like to see this working.

```js
glob('../src/components/**/stories.js', (err, files) => {
  files.forEach(file => require(file))
})
```

Someone has a workaround?

**Comment by sean-clayton** [comment]
```js
const req = require.context('../src/components/', true, /stories\.js$/)

function loadStories() {
  req.keys().forEach(req)
}

configure(loadStories, module)
```

That should work 😃

**Comment by lnmunhoz** [comment]
Worked like a charm! Thank you @sean-clayton!
