### ISSUE TITLE
Addon and decorator not working.

### ISSUE THREAD

**Issue by dhansiddh** [kadirahq/react-storybook#375]
I am a issue while using addons and global decorators in the react-storybook. Here is what my config file looks like 
```
import { addDecorator, configure, setAddon } from '@kadira/storybook';
import stories from '../src/components/stories';
import infoAddon from '@kadira/react-storybook-addon-info';

addDecorator((story) => (
  <div style={{textAlign: 'center'}}>
      {story()}
  </div>
));

setAddon(infoAddon);
function loadStories() {
   stories
}
configure(loadStories, module);
```

And when i am trying to use the `infoAddon` method in the component story file i am getting error that the function is not find. Below is my component.story  file 

```
import { storiesOf, action } from '@kadira/storybook';

storiesOf('Component', module)
  .addWithInfo('default view', () => {
     <div>
         <span>Content</span>
     </div>
  });
```
 This is the error i am getting 
```Uncaught TypeError: (0 , _storybook.storiesOf)(...).addWithInfo is not a function```

Also the decorator are not working too.

I am not using any custom webpack config. Can you please help me in rectifying what's going wrong here. I went through the Readme and followed every step and was able to setup the initial version successfully without having any addons and decorators.

**Comment by arunoda** [comment]
@roonyh could you have a look at this?

**Comment by roonyh** [comment]
@dhansiddh Remove the line, `import stories from '../src/components/stories';`. This line is called before `setAddon` is called so it gives that error.

And change the `loadStories` function to,
```js
function loadStories() {
  require('../src/components/stories');
}
```

**Comment by dhansiddh** [comment]
Thanks @roonyh this seems to fix the issue 👍
