### ISSUE TITLE
Silence Webpack Output

### ISSUE THREAD

**Issue by chibicode** [kadirahq/react-storybook#376]
Just FYI for people having the same question - if you would like to suppress webpack output, try this:

```js
// On your custom webpack config
module.exports = {
  ...
  devServer: {
    stats: 'errors-only'
  }
}
```

This works because `react-storybook` uses webpack dev middleware, which supports the above option. See: https://github.com/webpack/webpack/issues/1191#issuecomment-197359079

### Before

![image](https://cloud.githubusercontent.com/assets/992008/17613451/390285f8-6012-11e6-8a08-77bd58b4f14d.png)

### After

![image](https://cloud.githubusercontent.com/assets/992008/17613444/29a66b10-6012-11e6-860f-080c0f5160f5.png)

**Comment by nikfrank** [comment]
this isn't working for me.

I tried all of

devServer: { stats: 'none' | 'errors-only' | { chunks: false } }

in my webpack config

every time I restart the storybook, nothing happens - 

SO I solved it by editing the
./node_modules/@kadira/storybook/dist/server/middleware.js

with

  var devMiddlewareOptions = {
    noInfo: true,
    stats: 'errors-only',
    publicPath: config.output.publicPath,
    watchOptions: config.watchOptions || {}
  };


wherein I saw the problem.

The devMiddleware was not using any of the custom config!

however, I don't like this solution.
