### ISSUE TITLE
Default Webpack configuration seems to minify everything by default and doesn't catch prop types

### ISSUE THREAD

**Issue by FarhadG** [kadirahq/react-storybook#379]
By the way, I must say that I absolutely love this project. It's been very easy getting up-and-running. A few things I've noticed:

- Default Webpack build minifies everything or the component names are preserved, which makes it difficult for the documentation aspect (using `addWithInfo`).
- Either due to the minification or the fact that `propTypes` cannot be read when exported components are wrapped in higher order functions, I cannot get the `propTables` to pick up the `propTypes`

Here's a quick example:

```jsx
Story Source
<e progress={10} radius={120} strokeWidth={10} />
Prop Types
"" ComponentNo propTypes defined!
"e" ComponentNo propTypes defined!
```

As you can see above, the component has been renamed to `e` (assuming it's just minified) and no `propTypes` are found when I enable them with `{ propTables: [SampleComponent] }` when using `addWithInfo`. `SampleComponent` is wrapped with two higher order functions and then exported.

Thanks for your insights...

**Comment by arunoda** [comment]
Try to define a displayName for your component. It'll fix this.
Minification is something we must do.

Check this: https://github.com/kadirahq/react-storybook-addon-info/issues/43

**Comment by arunoda** [comment]
If this is something else, try to create an issue on the addon-info repo.
