### ISSUE TITLE
Show all stories from one component on the same page

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/react-storybook#38]
Hi, it would be great if I could view all stories from the same component on the same page. This would help me a lot to see the general design. for example, I am working on a upload component and I would like to preview all states at the same time. Low prority though. Loving it so far!

**Comment by arunoda** [comment]
In order to do this, we need to configure our data later to work with multiple preview iframes. We discuss some of that here.
See: https://github.com/kadirahq/react-storybook/issues/12

Will work on once we get there.

**Comment by mnmtanish** [comment]
This can be done with this [addon](https://github.com/jurgob/react-storybook-addon-add-stories-group).
