### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by alikhani** [kadirahq/react-storybook#381]
I added react-storybook to a project with [react-boilerplate](https://github.com/mxstbr/react-boilerplate). When I try to run tests I get this error

`Uncaught Error: dataId is not supplied via queryString
  at webpack:///~/@kadira/storybook/dist/client/preview/index.js:64:0 <- test-bundler.js:54610`

Has anyone experienced this issue or know what it belongs to?

**Comment by arunoda** [comment]
Is there anyway we could re-produce these errors?

**Comment by alikhani** [comment]
@arunoda I will create an example soon when I have time

**Comment by joaomilho** [comment]
+1, I get this in the UI

**Comment by joaomilho** [comment]
And all I have is this:

```jsx
import { configure } from '@kadira/storybook'

function loadStories() {
  require('../Link/story')
}

configure(loadStories, module)
```

```jsx
import React from 'react'
import { storiesOf } from '@kadira/storybook'

storiesOf('Link', module)
  .add('with text', () => (
    <a>My First Button</a>
  ))
```

**Comment by joaomilho** [comment]
Mmm, solved by removing some plugins I had in the webpack config. I just copied and pasted the real one...

**Comment by mnmtanish** [comment]
Hi @joaomilho 
Which plugins were causing this error?

**Comment by arunoda** [comment]
Gonna close this since the original issue has been fixed.
