### ISSUE TITLE
GitHub pages build doesn't load images

### ISSUE THREAD

**Issue by FarhadG** [kadirahq/react-storybook#382]
I have the following `npm` script:

```json
    "deploy-storybook": "storybook-to-ghpages",
```

which works flawlessly, where it builds and deploys to github pages, however, none of the images are loading (asset paths are incorrect). This works just fine in storybook's development cycle, however, when I build and deploy to github pages, the assets don't load.

Any ideas?

**Comment by arunoda** [comment]
Yes. That's an issue with paths. We are going to fix this in upcoming days. 
For now for your images, try to use relative paths if possible.

**Comment by FarhadG** [comment]
Thank you! Looking forward to this release :)

**Comment by arunoda** [comment]
We did a fix for this with `v2.4.2`.
Give it a try.
It should fix your issues. (Only if you are using require(or import) to load images).
If you are using static directories, (via -s option) you must use relative URLs.

**Comment by arunoda** [comment]
Reopen if this doesn't work for you.
