### ISSUE TITLE
Storybook and webpack-dashboard

### ISSUE THREAD

**Issue by PTihomir** [kadirahq/react-storybook#385]
I am trying to add to my project the webpack-dashboard plugin, which makes a nicer output from webpacks default build output. But with storybook it fails, because I can't figure out how to make storybook be quiet when it has some errors in build process.

Here is a sample project, with intentional error:
https://github.com/PTihomir/storybook-test-project

`npm run storybook` will start the build, but at the end the listing will override the dashboard.

By removing the error and running `npm run dev`, the desired output will be presented.

I am not sure that the issue is with storybook, but I assume storybook just prints errors from webpack, even if in webpack.config the quiet parameter is set to true.

**Comment by mnmtanish** [comment]
Looks like we should forward the `devServer` field as options for the **webpack-dev-middleware**. This is what the **webpack-dev-server** seems to be doing (check [this link](https://github.com/webpack/webpack-dev-server/blob/2f02d0c169c0681e85c2b12dae6774ab0ee7a115/bin/webpack-dev-server.js#L137) and [this link](https://github.com/webpack/webpack-dev-server/blob/2f02d0c169c0681e85c2b12dae6774ab0ee7a115/lib/Server.js#L53)). Storybook creates the middleware config [here](https://github.com/kadirahq/react-storybook/blob/584d3a174557f94fa2167776988ea65b6c2b26ff/src/server/middleware.js#L23).

@PTihomir If you can send a pull-request for this I can merge it to react-storybook and do a release. Let me know if you need any help.

**Comment by arunoda** [comment]
I'm gonna close this since we've a clear set of actions.
@PTihomir feel free to ask more questions or re-open if you need.

**Comment by PTihomir** [comment]
Ok, thanks. I will make the modifications and create the PR.

**Comment by arunoda** [comment]
@PTihomir awesome.

**Comment by arunoda** [comment]
Closing since we are open to accept a PR.

**Comment by Florian-R** [comment]
@PTihomir Did you filled a PR for this? Can't find any track of it. I'd be happy to take a look if not.
