### ISSUE TITLE
An API to set options

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#389]
Currently options can't be passed to storybook-ui through react-storybook. This will need discussion regarding the API. storybook-ui [already accepts some options](https://github.com/kadirahq/storybook-ui/pull/20) but there's not a way to pass them while using react-storybook. Once this is implemented we can add more optional parameters. Even changing UI colors. It will be great if someone looks into this and API architecture is finalised.

**Comment by roonyh** [comment]
The method `setOptions` is open to addons. So this can be done by an addon. Maybe we can just create an addon for these customizations.

**Comment by ritz078** [comment]
So do you mean as the options keep increasing, we will create as many addons ? If this is it, that won't be a scalable solution. This isn't an additional feature. `setOptions` is already present in storybook-ui. So the option to set it should be inbuilt ?

**Comment by roonyh** [comment]
I meant one addon for all the options named 'customizer' or something. But I realized it would just be five lines :) So no point of maintaining separately. So I agree this should be inbuilt.

**Comment by ritz078** [comment]
Yes that's what I was concerned about. A build in API will be great. Once this is done, the following can be configured:

- [x]  title and link 
- [ ] theme colours
- [ ] show non enumerables in action logger.

**Comment by kevinSuttle** [comment]
Is it possible to set these options in the config file? Like, never showing the actions panel?

**Comment by arunoda** [comment]
@kevinSuttle you found the correct issue.
@roonyh Could you work on something like this. Expose this API to the storybook and allow to pass some default queries.

**Comment by roonyh** [comment]
@arunoda OK. So this should be called from `.storybook/config.js` right? I'll be working on this.

**Comment by arunoda** [comment]
@roonyh yep. We need to export the same setOption API provided by the `storybook-ui`

**Comment by roonyh** [comment]
@arunoda I gave this a try. My idea was that a `setOptions` method exported from `@kadira/storybook` is called by the story writer on `.storybook/config.js`. But then it gets bundled with the preview. So these options are sent through the channel to manager. Which makes it a little delayed to set. Check: https://roonyh.github.io/react-button

How to get this bundle with the manager instead? Is it fine if we add another file like addons.js called options.js or something? Or is the above good enough?

**Comment by arunoda** [comment]
@roonyh Adding a new file is not a good idea.
Anyway, can we do this via an addon? If so, we can just document this with a good example.
(I think that's viable)

If so, share me an example. I'll add the docs.

**Comment by ritz078** [comment]
As far as the addon comes built in with storybook, its fine. but if the user has to manually include it I think it won't be a nice idea.

**Comment by mnmtanish** [comment]
Published the addon but there's not much we can configure right now. I'll try to add more options soon. As soon as the option fields are stable enough we can add this addon by default on React Storybook and expose a function.

**Comment by kevinSuttle** [comment]
@mnmtanish Can you configure which panels are open and included without having to use URL params?

**Comment by mnmtanish** [comment]
Not yet. (ia) I'll try to do it tomorrow. At the moment we can only set the heading on top of the list and its link.

**Comment by mnmtanish** [comment]
Which panels are visible initially can be configured from Storybook `v2.19.0`. See the options addon [repo readme](https://github.com/kadirahq/storybook-addon-options) for an example.

**Comment by arunoda** [comment]
@mnmtanish Add this addon to our addon Galary

**Comment by mnmtanish** [comment]
Done

**Comment by arunoda** [comment]
I think we can close this now :)
