### ISSUE TITLE
Can't run the example in my project. Babel problem

### ISSUE THREAD

**Issue by namKolo** [kadirahq/react-storybook#39]
I just created the example and moved it to my project.
When i start, it throws error
```
`Error in multi admin
Module not found: Error cannot resolve module 'stack-source-map/register' 

Module build failed: Error Cound't find preset "stage-2" relative to directory <my project path>`
```
Please help me.
Anyway, your project is so cool =D I really want to try to apply to my project soon. Love your concept and idea :+1:

**Comment by arunoda** [comment]
Use NPM3. See: https://github.com/kadirahq/react-storybook/blob/master/docs/known_issues.md#potential-issues-with-npm-2

**Comment by arunoda** [comment]
Please reopen if that's solve your issue.
