### ISSUE TITLE
Provide global switches for RTL, fonts, locales, themes

### ISSUE THREAD

**Issue by soneymathew** [kadirahq/react-storybook#393]
Provide options to 
1) Switch between rtl and ltr for all the displayed stories at runtime
     To see how my stories get affected based on the direction
2) Switch between multiple configured fonts for all stories at runtime
     To see how my stories look with different fonts
3) Switch between multiple configured locales for all stories at runtime.
   saw this one https://github.com/Tarabyte/react-storybook-addon-intl/blob/master/example/Button-story.js
   But I meant a way for stories to react based on locales switched
4) Switch between themes configured at runtime example dark and light theme
   Define a way to switch between themes.

**Comment by necolas** [comment]
Have you looking into doing this in user-land with the new addons API?

**Comment by arunoda** [comment]
I think we've given more ways to extend with the new addon API(s).
