### ISSUE TITLE
Module not found - Meteor Issues

### ISSUE THREAD

**Issue by PolGuixe** [kadirahq/react-storybook#394]
I have started using Storybook and I have some issues with the Meteor packages. 

Yes, I use some Meteor packages inside components, such as: 
-std:accounts-ui. 
-kadira:flowrouter-ssr --> to obtain urls, etc.

Any idea how to solve this issues with modules not being found?

**Comment by arunoda** [comment]
Unfortunately there's no way to do that. That's the intendant behaviour. 

You need to write your UI component without those modules. Then use a container to do use those modules and inject.

**Comment by PolGuixe** [comment]
Let's say that if I want the `href` prop for several links I'll have to generate those in the container using e.g.FlowRouter. Ok got it, altought it can become very cumbersome in many cases. 

But if I used React-Router, because it is an npm package, I won't have this issue. Correct?

This issue is mainly related to using meteor packages in ui-components.
