### ISSUE TITLE
Storybook doesn't run when `--dont-track` flag is included

### ISSUE THREAD

**Issue by necolas** [kadirahq/react-storybook#395]
We added `--dont-track` to our storybook script:

```
start-storybook --dont-track -p 9001 -c /path-to/storybook-dir
```

Result:

```
Storybook starting...
Storybook would not send anonymous usage stats anymore.
```

And the process exits.

**Comment by necolas** [comment]
Looking through the tracking patch, it looks like this is the intended behaviour. Really confusing decision IMO.

**Comment by arunoda** [comment]
Actually, you need to do this only once. After that, there's no need to use dont track command. 

May be we can just print a log to run storybook command again or simply ignore sending data when there's the flag.

**Comment by necolas** [comment]
Oh I see. So you'd expect storybook to be installed globally in that case? In my case we have a tool like create-react-app that bundles storybook and wraps commands. So the storybook script now runs 2 start-storybook commands. No problem

**Comment by arunoda** [comment]
@necolas ah nope. It's the same command you install in your project. Anyway, this is confusing.
I'll change it as you expected it to work.
That makes sense.

**Comment by necolas** [comment]
Thanks!
