### ISSUE TITLE
why do we use separate webpack configurations?

### ISSUE THREAD

**Issue by flosse** [kadirahq/react-storybook#40]
Most setups already use a webpack configuration and I wonder why do we use a separate one? Of course I could just symlink my config but that doesn't work because the server just uses the module loaders and plugins but ignores everything else. E.g. if I want to use stylus with the nib plugin there is a stylus option within the webpack configuration:
```js
stylus: {
  use: [require('nib')()],
  import: ['~nib/lib/nib/index.styl']
}
```
Because that option is ignored I can't use the storybook for components that are using nib :(

Can't we go the other way around? Load the main webpack configuration an add/modify it for the server?

**Comment by arunoda** [comment]
That's because, Storybook uses it's own server with it's own set of configurations (files) to setup it. 
But there's one thing that you can do.

You can import your existing configuration into storybooks file and pick whatever the parts you need.

**Comment by timkindberg** [comment]
#160 is probably relevant here.

**Comment by arunoda** [comment]
I think #160 is the best we can have.
Closing this in favour of that.
