### ISSUE TITLE
Cross browser testing

### ISSUE THREAD

**Issue by jimmiebtlr** [kadirahq/react-storybook#406]
Thoughts on an integration with browser stack, to quickly see what browsers break and/or don't degrade gracefully?

Seems like the storybook concept would work great for something along those lines.

**Comment by tommoor** [comment]
I'm not sure why any integration would be needed on storybook's side to achieve this? What did you have in mind?

**Comment by arunoda** [comment]
@jimmiebtlr Have a look at this issue: https://github.com/kadirahq/react-storybook/issues/266
