### ISSUE TITLE
Namespace Storybook Styling

### ISSUE THREAD

**Issue by NathanielScottStevens** [kadirahq/react-storybook#408]
I'm having an issue where the styling used for the preview screen is cascading into my story previews. I'm happy to work on fixing it, I'm just unclear on where the css is getting declared at.

**Comment by arunoda** [comment]
It's pretty weird. Storybook does not add any styles into the preview. (It's rendered inside an iframe).

Check CSS you've imported into your stories. Places to check:

* storybook config file
* story files
* component files.
