### ISSUE TITLE
missing module after error with create-react-app

### ISSUE THREAD

**Issue by sylvainbannier** [kadirahq/react-storybook#409]
I added storybook to my app generated with `react create app` using those steps : 
https://voice.kadira.io/react-storybooks-meets-create-react-app-ac8a3f32cc79#.gzg8s4e1c

I had to manually add babel-runtime 6.11.6 to prevent errors with missing babel runtime modules at build time (using node 4)

I can now use the storybook which updates correctly after files changes except when I accidentally insert an error in my components.

After any error in my component (like a missing component for instance) I get this error : 
```
Cannot find module "../App.js"
Error: Cannot find module "../App.js"
...
```

which wouldn't disapear even if I fix the original error.

- if I refresh the page the missing module error disappear
- using only create react app's `npm start`, without storybook, I don't have this bug and webpack reloads the module after my fix to the broken component

**Comment by arunoda** [comment]
I'm seeing some issues.
For now, try to use NPM@3.

**Comment by arunoda** [comment]
Update `@kadira/storybook` to the latest. We've just fixed it.

**Comment by sylvainbannier** [comment]
Confirmed : bug fixed. (tested on a new "blank" create react app project). Thanks.

**Comment by arunoda** [comment]
Awesome.

**Comment by sylvainbannier** [comment]
I responded too fast : this solved this issue with the missing babel runtime module but not the one with the  missing `App` module after an error.

I investigated further and it appeard that the issue only happen if I import CSS in the component using webpack loader
```
import './app.css';
```
By removing the line above the problem is solved for `App.js`. But I'd rather like to keep CSS loading with webpack because : 

- it is the defaut way of working with CSS in `create-react-app`
- it handles auto-prefixer transformations using postcss (which I believe inline styles don't do)

**Comment by arunoda** [comment]
@sylvainbannier This should be work fine. Can I have a sample repo?

**Comment by sylvainbannier** [comment]
here's a repo
https://github.com/sylvainbannier/cra-storybook

this is just a create-react-app where I add react-storybook.

this commit is the only think I changed :
https://github.com/sylvainbannier/cra-storybook/commit/bc135a6b0282b600681f75122fd2f6e20e9b72c9

To see the bug uncomment this line :
https://github.com/sylvainbannier/cra-storybook/blob/master/src/App.js#L10

you'll see something like this :

![image](https://cloud.githubusercontent.com/assets/452941/18201509/e3fcd680-710a-11e6-8145-ec807104173f.png)

then comment it again : 
![image](https://cloud.githubusercontent.com/assets/452941/18201541/13b3066a-710b-11e6-8bca-13ab155f2ba9.png)

**Comment by arunoda** [comment]
Hey could you try this with the latest version of Storybook. We did a fix for this.

**Comment by arunoda** [comment]
Reopen this if it doesn't fix your issue.

**Comment by sylvainbannier** [comment]
It's fixed. Thanks !
