### ISSUE TITLE
[Feature] Integrate `stphdenis/meteor-client-packages-meteor`

### ISSUE THREAD

**Issue by nadeemja** [kadirahq/react-storybook#411]
This might be useful to have as an option in react-storybook.

_Use Meteor's client Packages in a non Meteor project_
https://github.com/stphdenis/meteor-client-packages-meteor

**Comment by mnmtanish** [comment]
React Storybook supports custom webpack config files so It can be used to setup modules like this one. Check [this page](https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#custom-webpack-configurations) for more info.

**Comment by PolGuixe** [comment]
@mnmtanish the link you have provided redirects to a 404.

**Comment by PolGuixe** [comment]
Does anyone has a webpack config files which is able to include certain meteor packages?

**Comment by ffxsam** [comment]
Yeah, as someone who finds webpack quite puzzling, it would be great if someone could add an example to the Storybook docs on how to mock meteor packages.
