### ISSUE TITLE
Component have ref, storybook will have error

### ISSUE THREAD

**Issue by renminghao** [kadirahq/react-storybook#414]
my component render function has return many input with ref, when I run `npm run storybook`,  the error will throw 
```
Uncaught Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
what should I do?

**Comment by arunoda** [comment]
This is usually means two versions of React running here. Could you send us a sample repo?

**Comment by renminghao** [comment]
my project React version just one with 15.3.1, and if I remove the ref from input, the error will gone，but I can not do this, because I can't  guarantee other component render function have ref.  I try to `npm uninstall react react-dom`, `npm install react react-dom`,the problem have not solve.

**Comment by renminghao** [comment]
and I run `npm ls | grep react` the result is ![https://img.alicdn.com/tps/TB17tJgNXXXXXboaXXXXXXXXXXX-1055-530.png](https://img.alicdn.com/tps/TB17tJgNXXXXXboaXXXXXXXXXXX-1055-530.png)

**Comment by renminghao** [comment]
I run the `find ./ -name react -type -d` in my node_modules folder, just output one `react`

**Comment by renminghao** [comment]
The probelm is gone, the reason is I used webpack bundle file in the stories, and the webpack bundle file has used react. anyway, thx so much.
