### ISSUE TITLE
dataId is not supplied via queryString

### ISSUE THREAD

**Issue by HBCharles** [kadirahq/react-storybook#423]
I'm having this issue in the browser console when launching my meteor app after doing a getstorybook command : 

> index.js:64 Uncaught Error: dataId is not supplied via queryStringmeteorInstall.node_modules.@kadira.storybook.dist.client.preview.index.js @ index.js:64fileEvaluate @ install.js:153require @ install.js:82meteorInstall.node_modules.@kadira.storybook.dist.client.index.js @ index.js:26fileEvaluate @ install.js:153require @ install.js:82meteorInstall.stories.index.js @ index.js:2fileEvaluate @ install.js:153require @ install.js:82(anonymous function) @ app.js?hash=67a0e95…:711

The app was working before, i have a blank page instead. 

Any idea how solve to issue ?

**Comment by arunoda** [comment]
Can  we get a sample repo or help us to get this reproduced. May be tell us Meteor version and the package you are using?

**Comment by HBCharles** [comment]
You can find [the repo](https://github.com/HBCharles/corona_storybook). I took the repo from [cheersjosh](https://github.com/cheersjosh/corona) and have performed the getstorybook command;

You can also have the issue by doing the getstorybook command on a newly created project.

**Comment by arunoda** [comment]
Yep. We had an issue related to Meteor.
We fixed it with the latest version of getstorybook.

The issue was:

* We created directory called `stories` inside the main app. So, it's going to load as well in Meteor.
* So we renamed that to `.stories`.

**Comment by arunoda** [comment]
I assume this is fixed now and close this issue.
But, reopen this if this is not what you are looking at.
