### ISSUE TITLE
Can I modify the page style or structure of main page of React Storybook ?? 

### ISSUE THREAD

**Issue by qiangege** [kadirahq/react-storybook#424]
My questions ：
1.   I want to change the style or structure of main page ，can be achieved?
2.   The search box on the page can search components by keywords in package.json of  components package?

I can not found information about them from the document。
I need help , thank you！

**Comment by arunoda** [comment]
Currently, there's is no way to customize the UI. But you can hack is via some Webpack alias stuff. But we don't have docs for that.

Now sure about the search box question? Could you clarify it a bit more.

**Comment by qiangege** [comment]
@arunoda 
Thank you for your answer, it is a great help to me.

About the search box，
when i install a component npm package,there are some keywords in its package.json  file.
The search box can search through these keywords??
I want to know whether it can. 
Thank you.

**Comment by arunoda** [comment]
Ah nope. You can't search like this. This is just for search stories. 

We will have more docs on cusomizing the UI soon.

**Comment by qiangege** [comment]
Okay, I understand。
Thanks for your help。😊
