### ISSUE TITLE
Accept resolve alias in custom webpack config

### ISSUE THREAD

**Issue by ivivona** [kadirahq/react-storybook#44]
React native web project requires aliasing it to react-native to keep it like React native.

**Comment by arunoda** [comment]
Now we've enabled this. Use version `1.5.0`.
See: #64 for more information.

**Comment by hliyan** [comment]
@arunoda , 
I'm having some trouble resolving an alias. storybook version: 1.28.1

./storybook/webpack.config.js resolve block:

```
  resolve: {
    alias: {
      foo: path.resolve(__dirname, 'bar.js')
    },
    extensions: ['', '.js']
  }
```

`import foo from 'foo';` just doesn't seem to get resolved (undefined). I've verified the file path gets resolved. What am I doing wrong?

**Comment by arunoda** [comment]
@dziamid We had a bug in the latest storybook release. We patched and released a new version. Could you try the latest version (v2.15.1)

**Comment by notgiorgi** [comment]
I'm using react-native-web and I want to share stories between web and native, so I have 2 separate configurations for storybook but 1 stories folder.

In stories I need to import `storiesOf` but import it from either `@storybook/react` or `@storybook/react-native`

So I came up with this:

```
const defaultConfig = require('@storybook/react-native/dist/server/config/webpack.config')
  .default

module.exports = Object.assign(defaultConfig, {
  resolve: Object.assign(defaultConfig.resolve || {}, {
    alias: Object.assign(
      (defaultConfig.resolve && defaultConfig.resolve.alias) || {},
      {
        '@storybook/react': '@storybook/react-native',
      },
    ),
  }),
})
```

and I'm using `import { storiesOf } from '@storybook/react'` 

But it still outputs the error, `Can't find variable: document` which means alias is not working
