### ISSUE TITLE
The shortcuts doesnot works in windows

### ISSUE THREAD

**Issue by cisen** [kadirahq/react-storybook#441]
Can anyone tell me (⌃ ⇧ P) match (shift + 6, shift, P ) is Correct？Why does it not works？

**Comment by mnmtanish** [comment]
The `⌃` is used for `CTRL`. So the shortcut will be `CTRL + SHIFT + P`

@arunoda it really is a bit confusing if you're not familiar with mac os

**Comment by cisen** [comment]
Oh, I see.Thank you!

**Comment by arunoda** [comment]
@mnmtanish May be we can provide the correct shortcut help UI based on the OS.
