### ISSUE TITLE
Static version of Storybook doesn't like Safari

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#443]
This is only the static build. Here's how to reproduce:

```sh
create-react-app demo
cd demo
getstorybook -f
npm run build-storybook
cd storybook-static
python -m SimpleHTTPServer 8010
```

Then visit http://localhost:8010 on safari and you'll see this:

![screen shot 2016-09-09 at 2 21 38 pm](https://cloud.githubusercontent.com/assets/50838/18381207/c27aa4fe-7698-11e6-9afa-3fe499991f1b.png)

Could you guys have a look at this?
cc @mnmtanish @roonyh

**Comment by arunoda** [comment]
Let's close this with a PR to this repo.
Anyway, do we need to update any package.json values?

**Comment by mnmtanish** [comment]
It's a patch release and It should work fine on fresh npm installs. Anyways, opened a pull-request here https://github.com/kadirahq/react-storybook/pull/444 which updates the package.json file.

**Comment by arunoda** [comment]
Deployed a release.
