### ISSUE TITLE
Configure a custom proxy using webpack.config.js

### ISSUE THREAD

**Issue by mstn** [kadirahq/react-storybook#445]
Thanks for the great work. I have a question about how to set a custom proxy for remote requests. As far I understand from #208, you suggest to implement a custom express server. I was wondering if it is possible to pass a proxy configuration to the webpack.config.js file defined in .storybook directory [in this way](https://webpack.github.io/docs/webpack-dev-server.html#proxy). I tried without success, but I am not a webpack expert.

**Comment by arunoda** [comment]
We don't recommend that method as we are not documented that.
Suggest way is build a storybook into a static app and deploy it anywhere you want.
(You can setup some basic auth basic auth setup pretty easily)
