### ISSUE TITLE
Meteor fontawesome

### ISSUE THREAD

**Issue by nmaro** [kadirahq/react-storybook#453]
I use the meteor package fortawesome:fontawesome
but the icons don't show up when running the components in react-storybook.

**Comment by arunoda** [comment]
We don't support Meteor packages. You need to load font-awesome manually.
One way is to add it manually into the head: https://getstorybook.io/docs/configurations/add-custom-head-tags

Or you can import the fontawesome CSS directly from NPM.

**Comment by protoEvangelion** [comment]
Link is now: https://storybook.js.org/configurations/add-custom-head-tags/
