### ISSUE TITLE
Adding Dash Docset

### ISSUE THREAD

**Issue by shreyansqt** [kadirahq/react-storybook#456]
Hello,

We are using this package in our Frontend app at [Sloppy](http://sloppy.io). Kudos on the new and updated documentation!

I was wondering if anyone has thought of adding the documentation to [Dash](https://kapeli.com/dash). Its a wonderful app to store documentations offline. 

If not, I am willing to contribute and create a docset using https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

I have created this issue just to verify that no one else is working on the same.

This is going to be my first open source contribution. So, any help and guidelines are hugely appreciated!

Thanks!
Shreyans

**Comment by arunoda** [comment]
Yep. Go for it.

**Comment by arunoda** [comment]
Closing this since this don't need any further support from us.
