### ISSUE TITLE
Get some cool features from Create React App

### ISSUE THREAD

**Issue by arunoda** [kadirahq/react-storybook#468]
* [x] NODE_PATH Support: https://github.com/facebookincubator/create-react-app/pull/476 [PR528](https://github.com/kadirahq/react-storybook/pull/528)
* [x] Add audio support in url loader: https://github.com/facebookincubator/create-react-app/pull/665 [PR527](https://github.com/kadirahq/react-storybook/pull/527)
* [x] Public URL support: https://github.com/facebookincubator/create-react-app/pull/703 - [PR529](https://github.com/kadirahq/react-storybook/pull/529)
* [x] Use: `babel-preset-react-app` as the default preset. [PR526](https://github.com/kadirahq/react-storybook/pull/526)
* [x] Use: ` babel-transform-react-jsx-source` both in dev and prod. (This is already used in babel-preset-react-app) - We'll think about prod usage later on.

**Comment by tonyxiao** [comment]
@arunoda on a related note could we try to integrate react-storybook directly into create-react-app itself? And make it really easy for people to create storybooks for their components?

**Comment by tonyxiao** [comment]
Nvm just saw this
https://github.com/facebookincubator/create-react-app/issues/297
https://github.com/kadirahq/getstorybook
Sick! Insane work @arunoda . Looking forward to seeing storybook in notes.

**Comment by gaearon** [comment]
>Use: babel-transform-react-jsx-source both in dev and prod.

I think it should be dev-only, should it not? Is Storybook use case different?

**Comment by arunoda** [comment]
@gaearon Storybook is mostly a devtool even we have a way to export into a static app. I think it's pretty useful in that case.

**Comment by arunoda** [comment]
I just released `@kadira/storybook@2.21.0` with all these features.
