### ISSUE TITLE
Providing a static file directory breaks React Storybook

### ISSUE THREAD

**Issue by submitteddenied** [kadirahq/react-storybook#47]
If you use the `-s` flag to provide a static file directory, the express routing appears to break and the app fails to load.

**Comment by arunoda** [comment]
what was the error you got? please provide the stack trace

**Comment by submitteddenied** [comment]
No errors in the console (the express app works), but the browser console shows:

```
http://localhost:9001/screen.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9001/index.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9001/screen.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

This is because the static files middleware is taking precedence over the webpack middlewares and failing to load the built files.

**Comment by arunoda** [comment]
Hmm. I can't reproduce this issue. 
Could you send some way, I can reproduce this error.

**Comment by submitteddenied** [comment]
Ah found the problem, my static file directory had an index.html which was being served by the static middleware. Renaming this file (to something other than `index.html`) resolved the problem.
