### ISSUE TITLE
addon-db.json not found when building the static website

### ISSUE THREAD

**Issue by tleunen** [kadirahq/react-storybook#470]
Using these 2 packages:
```
"@kadira/react-storybook-addon-info": "^3.2.1",
"@kadira/storybook": "^2.13.0",
```

I'm having a 404 on addon-db.json when running the static website built with `build-storybook -o _docs`

**Comment by arunoda** [comment]
Could you update the storybook to the latest. We did a fix recently for this.

**Comment by mnmtanish** [comment]
@arunoda we fixed the bug but a 404 error still shows up on the console when it tries to get the DB file. But storybook should still work as expected. I'll try to see if there's a way to get rid of it without big changes.

**Comment by arunoda** [comment]
@mnmtanish okay.

**Comment by mnmtanish** [comment]
Opened PR #472 to fix this

**Comment by mnmtanish** [comment]
Released `v2.16.1` with a fix

**Comment by tleunen** [comment]
Thanks, I'll retest this :)

**Comment by tleunen** [comment]
Confirmed it's fixed. Thanks @mnmtanish
