### ISSUE TITLE
Storybook config environment variables are sent to the client

### ISSUE THREAD

**Issue by mnmtanish** [kadirahq/react-storybook#471]
Storybook config variables also have the `STORYBOOK_` prefix so they'll be sent to the client. Sources:
 - [dev-server](https://github.com/kadirahq/react-storybook/blob/d518941d3260db579fabac1566280a90a04b9d16/src/server/index.js#L28,L34)
 - [static-build](https://github.com/kadirahq/react-storybook/blob/d518941d3260db579fabac1566280a90a04b9d16/src/server/build.js#L31,L35)

**Comment by arunoda** [comment]
Currently this is not so bad.
But we need to find a another prefix for above commands.

**Comment by mnmtanish** [comment]
Fixed with #481
