### ISSUE TITLE
Navigation order breaks during hot reload

### ISSUE THREAD

**Issue by jzaefferer** [kadirahq/react-storybook#482]
To reproduce: Start with 3 stories, A, B, C. By default, they're alphabetically ordered. Now edit story A. After a hot reload, observe the navigation order.

Expected: A, B, C
Actual: B, C, A

It seems like the hot reloaded story gets stuck to the end of the list. After a hard reload of the page, its back where its supposed to be.

Tested with 2.18.0.

PS: The "Known Issues" link in https://github.com/kadirahq/react-storybook/blob/master/CONTRIBUTING.md#issues is dead

**Comment by arunoda** [comment]
Yep. This is a bug.

**Comment by arunoda** [comment]
@mnmtanish This is suppose to work earlier. Seems like HMR dispose is not working properly. Isn't it?

**Comment by mnmtanish** [comment]
@jzaefferer when calling `storiesOf`, are you giving `module` as the second argument? HMR dispose will work only if it's done. Example:

```js
storiesOf('MyComponent', module)
```

**Comment by jzaefferer** [comment]
Yes, just verified that all our `storiesOf` calls pass `module` as the 2nd argument.

As far as I can tell, we're not doing anything out of the ordinary. Here's our config, webpack config and a sample story: https://gist.github.com/jzaefferer/e4c3152d60dd7e6537a1b72a6f6116dd

**Comment by mnmtanish** [comment]
Thanks for the info. I'll check it out.

**Comment by mnmtanish** [comment]
@arunoda this issue was there from the beginning. The order is lost, when the module gets disposed and re-added. And when it's added again, it's added as a new component (kind) and so it goes to the end of the list.

Opened a PR for this issue:
https://github.com/kadirahq/react-storybook/pull/499

**Comment by mnmtanish** [comment]
Fixed with #499

**Comment by jzaefferer** [comment]
Nice, thank you!
