### ISSUE TITLE
How to extend default webpack.config.js ?

### ISSUE THREAD

**Issue by achtan** [kadirahq/react-storybook#487]
Hi, i want to have default webpack config + add SCSS and Less loader, is it possible?

**Comment by arunoda** [comment]
Yes. That's doable try this to adding to your custom webpack config.

```js
var useDefaultConfig = require('@kadira/storybook/dist/server/config/webpack.config.js');

return function (config, env) {
   const defaultConfig = useDefaultConfig(config, env);
   // customize as you want

   return defaultConfig;
}
```

I didn't try this but this should work.

**Comment by arunoda** [comment]
Let me know how this goes, if so we could include in the docs.

**Comment by arunoda** [comment]
My above suggestion works and here's the link in the docs: https://getstorybook.io/docs/configurations/custom-webpack-config#extending-the-default-config
