### ISSUE TITLE
Set body font-size for rem units

### ISSUE THREAD

**Issue by casesandberg** [kadirahq/react-storybook#488]
I use rem units for font-sizes, is there a way to set `font-size:62.5%;` on the body so that they will display properly?

**Comment by arunoda** [comment]
You could set custom HTML tags to the <head>.
See: https://getstorybook.io/docs/configurations/add-custom-head-tags

**Comment by kevbost** [comment]
Hi from the future everyone! 👋

The updated doc link is here:
https://storybook.js.org/docs/configurations/add-custom-head-tags/
