### ISSUE TITLE
trouble rendering pure/stateless components

### ISSUE THREAD

**Issue by travi** [kadirahq/react-storybook#49]
As briefly mentioned in #16, I'm having trouble getting a pure component to render in a [simple reference application](https://github.com/travi/travi.org-admin/tree/react-storybook). I receive the error `Error: inst.render is not a function` when attempting to render [this component](https://github.com/travi/travi.org-admin/blob/react-storybook/lib/shared/views/theme/primary-nav.jsx).

I plan to keep digging deeper to try to confirm my suspicions, but thought you may be able to confirm more quickly or guide me in another direction.

**Comment by arunoda** [comment]
Seems everything okay for me at a quick glance. Give it a try to find the problem. If not, ping me.
I'll try to debug.

**Comment by travi** [comment]
I did sort it out. I forgot that this component was wrapped in a factory function. Once I sorted that out, it worked correctly. 

Sorry for the noise.

**Comment by arunoda** [comment]
Okay. Great.

**Comment by nobleach** [comment]
I'm actually having the same problem. Any component created by `class MyComponent extends React.Component` works just fine. But if they include any pure components, I get 

```
No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.
```

**Comment by IthacaDream** [comment]
I am experiencing this one too. any solutions?

**Comment by fredabrahamson** [comment]
+1

**Comment by alastairanderson** [comment]
> I am experiencing this one too. any solutions?

I feel like I'm 2 years too late to this one, but I'm getting this issue at present with this code:
`
import React from 'react';
const HeaderBar = () => {
    return (<div>Some nav stuff</div>);
}
export default HeaderBar;`

React version 16.5.2, Storybook version 4.0.0-alpha.23

I do not have the issue if I switch to this code:
`import React from 'react';
export class HeaderBar extends React.Component {
    render() {
        return (<div>Som nav stuff</div>);
    }
}`
