### ISSUE TITLE
One big storybook or split by package?

### ISSUE THREAD

**Issue by nmaro** [kadirahq/react-storybook#492]
First of all thanks for this great package! Thanks to it I was able to modularize my code and create my first external npm package - a collection of components used by my project.
This is a question about best practices: if you split your application in many npm packages, do you keep a separate storybook in each package, or do you create one big one in the main app, or both? And if the answer is both: do you import the stories from the external packages?

**Comment by arunoda** [comment]
The idea is always to keep stories closer to their components. In that case, I think having them inside the NPM module is ideal.

But you may want to keep a Storybook in the main project to see how they great together. Kind of integration with multiple components.

**Comment by nmaro** [comment]
I ended up doing exactly that - creating the stories in the packages and importing them in the main project.

**Comment by arunoda** [comment]
Hope we can close this.
Feel free to ask more :)

**Comment by jakehelme** [comment]
This is an old thread, but I would really like to find out more about how to implement the suggested solution. We build our components in their own NPM modules containing their stories within and would like to have a storybook implementation that references the stories from these NPM modules dynamically ... could you perhaps share a bit on how you implemented it @nmaro? Or perhaps @arunoda can explain a little on how the stories are packed and referenced by storybook.

**Comment by rashigupta163** [comment]
I would also like to know what @jakehelme asked. @nmaro could you enlighten us with it?

**Comment by rashigupta163** [comment]
I would also like to know what @jakehelme asked. @nmaro could you enlighten us with it?
