### ISSUE TITLE
accessibility: please use link to open a story

### ISSUE THREAD

**Issue by jmfrancois** [kadirahq/react-storybook#505]
At the moment they are div which is not the best for accessibility.
I'm used to navigate with my keyboard and this is not possible on storybook.

I can make PR only if you show me where the code of that left navigation bar is (can't find it in the code)

<img width="507" alt="screen shot 2016-09-28 at 12 12 36" src="https://cloud.githubusercontent.com/assets/19857479/18909700/e0e4c416-8574-11e6-92e7-614b5cb668af.png">

**Comment by mnmtanish** [comment]
Most of the UI code is available here:
https://github.com/kadirahq/storybook-ui

The storybook component is in this directory:
https://github.com/kadirahq/storybook-ui/tree/528e00b6952c1926f0ef2fb4ab49a0dbdbcc7e8a/src/modules/ui/components/left_panel

**Comment by frassinier** [comment]
Usually, we should prefer `<ul>` or `<ol>` to display a list too

**Comment by acateland** [comment]
PR time guys !

**Comment by jmfrancois** [comment]
PR done ! Could you @mnmtanish please review it ?

**Comment by mnmtanish** [comment]
@jmfrancois with pleasure :)
