### ISSUE TITLE
Show some transition while new action trigger is logged

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#51]
Whenever I trigger a new action that is same as the previous action, it's hard to tell the difference seeing the logger . If there can be a small transition in the newest logged action for a moment when it's added , the difference will be more visible.

Open to sending a PR.

**Comment by arunoda** [comment]
Yeah! That's would be awesome.

**Comment by arunoda** [comment]
Released in `v1.9.0`.
