### ISSUE TITLE
Abstract docs for registering addons

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#521]
Right now, there is a link to a gist that's specific to one addon. It would be handy to have this API abstracted for general reuse. 

https://getstorybook.io/docs/addons/writing-addons

**Comment by kevinSuttle** [comment]
Actually, I see this: https://getstorybook.io/docs/addons/api

**Comment by arunoda** [comment]
Okay. That's a good idea.

**Comment by arunoda** [comment]
Added a section.

**Comment by kevinSuttle** [comment]
Thanks, @arunoda. Next one's on me. 👍
