### ISSUE TITLE
Should not depend on index.css

### ISSUE THREAD

**Issue by glenarama** [kadirahq/react-storybook#523]
The create-react-app config loads the default ../src/index.css file
This is the first thing i remove on my create-react-app based projects and storybook breaks.

Suggest not depending on this.

**Comment by arunoda** [comment]
Yep. We don't need that.
Need to clear that, this is going to be on our `getstorybook` utility.

**Comment by arunoda** [comment]
Published a new `getstorybook` version by removing this.
