### ISSUE TITLE
Style bug (paddingLeft)

### ISSUE THREAD

**Issue by ffxsam** [kadirahq/react-storybook#524]
I just upgraded Storybook to 2.20.1, and now I'm getting the following warning:

```
Warning: Unsupported style property padding-left. Did you mean paddingLeft? Check the render method of `Stories`
```

**Comment by PEM--** [comment]
Fixed with https://github.com/kadirahq/storybook-ui/pull/52

**Comment by arunoda** [comment]
This should be fixed by now.
Delete storybook-ui and install it again.

```sh
rm -rf node_modules/@kadira/storybook-ui
npm i
```

**Comment by arunoda** [comment]
I think we could close this now.
