### ISSUE TITLE
storybook-loader for webpack

### ISSUE THREAD

**Issue by Idered** [kadirahq/react-storybook#525]
I have a project in which, each component directory contains a story:

![](http://i.imgur.com/xn6Tfc4.png)

With current react-storybook I have to require each .story.js file:

![](http://i.imgur.com/UWWVwjD.png)

Is it possible to load all files ending with .story.js as stories using webpack:

```js
loaders: [
  {
    test: /\.story.js/,
    include: require.resolve('src'),
    loader: 'storybook-loader',
  }
]
```

storybook-loader is just an idea.

**Comment by arunoda** [comment]
I hope you found this: https://getstorybook.io/docs/basics/writing-stories#loading-stories-dynamically
