### ISSUE TITLE
Left menu goes blank when switching items

### ISSUE THREAD

**Issue by tutturen** [kadirahq/react-storybook#53]
When switching from one item to another in the storybook, the entire left menu disappears. When clicking "clear", it shows up again.

After some investigation, I found out that i only occurs when a scrollbar is present in the left menu.

This is tested in Chrome 48 on OS X.
I could not reproduce the same bug in Safari.

![Screen recording](http://g.recordit.co/ZnlBGLUocz.gif)

**Comment by arunoda** [comment]
Thanks. I've seen that too in some places. Will see how it can fixed. 
Let me know, if you find anything on this.

**Comment by arunoda** [comment]
Hi, @tutturen, 

We've changed the sidebar with #64 and now this should've been fixed. Check the latest version,

**Comment by tutturen** [comment]
Checked version 1.6.0, and the bug seems to be fixed. Good work!

**Comment by arunoda** [comment]
Awesome. Kudos to @mnmtanish for this.
