### ISSUE TITLE
Highlight the URL in console output

### ISSUE THREAD

**Issue by gaearon** [kadirahq/react-storybook#531]
It took me a while to find it:

<img width="955" alt="screen shot 2016-10-05 at 11 32 29" src="https://cloud.githubusercontent.com/assets/810438/19109982/ba5bd002-8aef-11e6-897b-5c756e9fca21.png">

Highlighting it with cyan would solve the issue.

**Comment by arunoda** [comment]
Yep. I am on this.

**Comment by arunoda** [comment]
Fixed with `v2.22.0`
