### ISSUE TITLE
Error with missing regeneratorRuntime

### ISSUE THREAD

**Issue by akofman** [kadirahq/react-storybook#537]
With the actual version of `babel-preset-react-app`, we have two different versions of `babel-plugin-transform-regenerator` :

```
$npm ls babel-plugin-transform-regenerator 
babel-preset-react-app@0.2.1 
├── babel-plugin-transform-regenerator@6.14.0
└─┬ babel-preset-latest@6.14.0
  └─┬ babel-preset-es2015@6.16.0
    └── babel-plugin-transform-regenerator@6.16.1
```

This prevents to use storybook without `babel-polyfill`. I did a [PR](https://github.com/facebookincubator/create-react-app/pull/864) to `creat-react-app` to fix this issue. Once it will be released, we should update the version of `babel-preset-react-app`.

**Comment by arunoda** [comment]
I'll bump the version when it's published.
We we use semvar, you could simply do a clean node_modules and install deps again to fix this issue on the Storybook side.
