### ISSUE TITLE
NODE_ENV no longer appears to be set to "development" locally

### ISSUE THREAD

**Issue by kevinSuttle** [kadirahq/react-storybook#539]
https://getstorybook.io/docs/configurations/env-vars

**Comment by arunoda** [comment]
Hmm.
I am seeing it.

~~~
console.log('ENV', process.env.NODE_ENV)
~~~

**Comment by arunoda** [comment]
Do you mean something else?

**Comment by kevinSuttle** [comment]
I saw this only occurs in the older setup. Apologies for the false alarm.

**Comment by arunoda** [comment]
Okay.

**Comment by pimlottc-gov** [comment]
> https://getstorybook.io/docs/configurations/env-vars

Updated link: https://storybook.js.org/docs/configurations/env-vars/
