### ISSUE TITLE
`getstorybook` is destructive

### ISSUE THREAD

**Issue by leebenson** [kadirahq/react-storybook#549]
Running `getstorybook` inside an existing Storybook'd folder will destructively overwrite `.stories`.

I learned that the hard way when a custom webpack config I spent 3 hours working on wound up getting killed 👍 

If this is intentional, it might be worth adding an 'Are you sure?' prompt.

**Comment by arunoda** [comment]
By default, getstorybook won't allow you to run inside already initiated project.
You only can do it by adding the `-f` flag.
Even if you do so, `git diff` is your friend.

Is this happening without the `-f` flag?

**Comment by leebenson** [comment]
I didn't commit the prior version, so `git diff` unfortunately didn't save the day...

Yes, it happened without the `-f` flag.

This might be because I moved the `stories` folder to `src/stories` (to fit better with my code layout), but I left `.stories` intact.

**Comment by arunoda** [comment]
It detect that using `package.json` and looking for `@kadira/storybook`. 
It's pretty hard to happen this without `-f`

**Comment by leebenson** [comment]
I'll close this since I don't recall the exact steps that led to this error. If it comes up again, I'll try to be more explicit in reproducing it.
