### ISSUE TITLE
Center the story within the iFrame ?

### ISSUE THREAD

**Issue by antoinerey** [kadirahq/react-storybook#55]
Do you consider centering the story inside the iFrame ? I currently work on a 27-inch screen and my Button component is pretty much lost in all this space :D

![image](https://cloud.githubusercontent.com/assets/3336873/14287536/47ae6c1c-fb53-11e5-9420-9ef5e18f87c5.png)

One solution could be to simply center the story on the screen. And of course, let the story scroll if it overflows the viewport.

**Comment by arunoda** [comment]
I get it. But, the component run inside a pure isolated environment where we don't inject any code. So, we shoudn't inject anystuff to change it.

That's how I view about this. Thanks for the request.

**Comment by tlrobinson** [comment]
@antoinerey You could create a simple component to center the content, something like this:

```
const Centered = ({ children }) =>
    <div style={{ height: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>
        {children}
    </div>
```

Then just do:

```
storiesOf("MyComponent", module)
  .add("defaults", () => {
    return <Centered><MyComponent /></Centered>
  })
```

**Comment by antoinerey** [comment]
Yep. That's what I did too. That's why I proposed this idea to be included
into the final solution. :)
Le mer. 6 avr. 2016 à 19:55, Tom Robinson <notifications@github.com> a
écrit :

**Comment by zimt28** [comment]
I like the idea, this would be great to have! It should be an optional solution though.

**Comment by immuzov** [comment]
@antoinerey You can use [decorator](https://github.com/kadirahq/react-storybook/blob/master/docs%2Fwriting_stories.md#using-decorators).
