### ISSUE TITLE
getstorybook spelling issue on error

### ISSUE THREAD

**Issue by Sawtaytoes** [kadirahq/react-storybook#550]
When you get the error ``An error occured while installing dependencies`.``, this error has a few issues.

1. `occured` should be spelled `occurred`.
2. There's a random grave accent at the end before the period.
3. The ✓ and ✖ icons are showing up as boxes in windows using cmd and git bash.

**Comment by arunoda** [comment]
Thanks for the bug report.
I fixed the typos.
For windows, I assume it's about related to unicode support. 
So, I created an issue related to this here: https://github.com/kadirahq/getstorybook/issues/22
