### ISSUE TITLE
fatal: No such remote 'origin'

### ISSUE THREAD

**Issue by UsulPro** [kadirahq/react-storybook#552]
```
> start-storybook -p 9001

fatal: No such remote 'origin'
master
=> Loading custom .babelrc
=> Loading custom addons config.
=> Using default webpack setup based on "Create React App".
=> Loading custom webpack config (full-control mode).

React Storybook started on => http://localhost:9001/

webpack built 908e1d66c95413c0cf13 in 5551ms
```
yes, I don't have `remote origin`. Everything works fine! So it's not so 'fatal' :satisfied:
@kadira/storybook@2.24.0

**Comment by arunoda** [comment]
I think I know what's going here.
@mnmtanish I assume this is related to the origin lookup.
We should try to do a fix for this.

**Comment by arunoda** [comment]
Note to self: 

* It's possible projects to not to use git
* It's possible projects to not to use the origin remote

**Comment by mnmtanish** [comment]
Opened a pull-request which hides the command output.

**Comment by eddiemonge** [comment]
This seems to have regressed:

```
info @storybook/react v3.4.11
info
exec: fatal: No such remote 'origin'
```
