### ISSUE TITLE
display  @kadira/storybook version

### ISSUE THREAD

**Issue by UsulPro** [kadirahq/react-storybook#553]
It's just an idea. Since occasionally there are questions related to the version of @kadira/storybook
(like #544, [this](https://github.com/sm-react/storybook-addon-material-ui/issues/5), [this](https://github.com/sm-react/storybook-addon-material-ui/issues/16) and so on)
would that be a good approach to show ver number in start-storybook cli?

(the idea is shamelessly stolen from yarnpkg)
![image](https://cloud.githubusercontent.com/assets/14885189/19481347/cf687a58-9577-11e6-8056-c958a7ceecbe.png)

**Comment by arunoda** [comment]
Yep. This is a good one.
It's PR time :D

**Comment by UsulPro** [comment]
Hi, 
I start to read the CONTRIBUTING.md and there is a ref to `docs/how_storybook_works.md` which actually contains a lot of useful information for the development, but it was removed from docs since d42f4eb906bb6e02a6292a7895bd5c3bf531ad48 and now is missing in the current version of repo.
I'm just wondering if it is still relevant it might be worth to return it?

**Comment by arunoda** [comment]
Yep. We need to get it back.
But you just need to look at here: https://github.com/kadirahq/react-storybook/tree/master/src/server
