### ISSUE TITLE
Recursive reference between functions cause "maximum call stack size exceeded"

### ISSUE THREAD

**Issue by guy-kdm** [kadirahq/react-storybook#558]
tl;dr - I suppose it's the hot reloading, is there a way to turn it off? 
If I include the following function: 

> function Hi() {
>     function Yo() {
>         return Hi()
>     }
>     return null
> }

I get "maximum call stack size exceeded" on build. 
Is there any way around it?

**Comment by DimitryKislichenko** [comment]
Since the last update I've made today to version 2.25.0, start getting same error message for component which worked fine before.

**Comment by arunoda** [comment]
It's a bug and on it.

**Comment by arunoda** [comment]
@DimitryKislichenko could you send me a sample code as well.

**Comment by arunoda** [comment]
Guys, could you check the latest version of storybook where I did a fix.

**Comment by DimitryKislichenko** [comment]
Thanks @arunoda, I can confirm that version 2.25.1 works.

**Comment by guy-kdm** [comment]
Joining the confirmation just to thank @arunoda for his lightning fast fix.

**Comment by arunoda** [comment]
Awesome. So, I'm gonna close this.
