### ISSUE TITLE
Unable to resolve jsx files

### ISSUE THREAD

**Issue by rcoedo** [kadirahq/react-storybook#562]
I am using storybook v2.25.1 and my webpack does not resolve jsx files. I tried adding `resolve: { extensions: ['', '.js', '.jsx']  }` to my `.storybook/webpack.config.js` file but it doesn't work.

I've seen some old issues like this one (#35), is this a regression?

thanks!

**Comment by arunoda** [comment]
Is this only came after you upgrade to `v2.25.1`?

**Comment by arunoda** [comment]
I just checked, there's no regression. I assume you've a custom webpack setup.
May be you could provide us a way to reproduce it locally. So, we could try it out.

**Comment by rcoedo** [comment]
I am using a clean create-react-app application. I installed react-storybook and renamed the Welcome and Button example components to jsx.

**Comment by arunoda** [comment]
@rcoedo Let me try that.

**Comment by arunoda** [comment]
Yep you are right.
Now we need to import it as `Button.jsx`.
I'll add a fix to that.

**Comment by arunoda** [comment]
@rcoedo I released a new version (v2.26.0).
Could you try that out?

**Comment by rcoedo** [comment]
It works now. 

Thanks! 🍻
