### ISSUE TITLE
Disable babel

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/react-storybook#567]
Hi, I can compile to pure ES5 with typescript with source-maps and I was wondering how can I disable  the babel transpilation in storybook? In regular webpack you simply ignore loader, but here loader is already defined. Thanks.

**Comment by arunoda** [comment]
Check this: https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config#full-control-mode

**Comment by arunoda** [comment]
If you do this, you'll loose some other features based on [react-docgen](https://voice.kadira.io/component-metadata-react-storybook-ac0b218a2203).
