### ISSUE TITLE
Add-on API: add navigation events

### ISSUE THREAD

**Issue by joscha** [kadirahq/react-storybook#568]
I wrote an add-on which relies on state in the stories:
https://github.com/joscha/storybook-addon-i18n-tools

Right now, there is no way for an add-on to find out whether the story was switched by the user (or at least I couldn't find out how). In order to react to navigation events, this would need to be part of the Add-on API.

**Comment by arunoda** [comment]
Hey check [this](https://github.com/kadirahq/storybook-addon-comments/blob/2563d1a7d0f902dc0663c833c9f5447566c8ec6b/src/manager/containers/CommentsPanel/index.js#L28): We've an API called onStory.

We should document that.

**Comment by joscha** [comment]
Thanks @arunoda - I created a PR for it here: https://github.com/kadirahq/getstorybook.io/pull/48

**Comment by arunoda** [comment]
I think we could close this now :)
