### ISSUE TITLE
Atom plugin

### ISSUE THREAD

**Issue by vadirn** [kadirahq/react-storybook#57]
Hi! I've set up a plugin here: https://github.com/vadirn/atom-storybook, but not yet succeeded with rendering url into the pane.

It seems like webview tag (https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md) should be used in order to render the storybook.

Any help is highly appreciated)

**Comment by arunoda** [comment]
I have no experience in Atom as well. Seems like webview is the thing we need. What was the problem you got?

**Comment by antoinerey** [comment]
What does your plugin do ? I can't find any informations about it :)

**Comment by vadirn** [comment]
Plugin is not ready yet, don't really know how to make that. It seems like webview should be added to a pane, but I didn't find any information on that yet.

The idea is to open a pane with storybook rendered in it, so that you can edit your files and see the changes without switching windows.

**Comment by vadirn** [comment]
Here is the package: https://atom.io/packages/atom-storybook

I messed up with package version number though.

**Comment by arunoda** [comment]
@vadirn superb.

**Comment by arunoda** [comment]
I think we can close this now.
