### ISSUE TITLE
Static directory doesn't follow the same path once build

### ISSUE THREAD

**Issue by mthuret** [kadirahq/react-storybook#570]
I have a static `public` directory with css files that are being referenced inside the head.html.

```html
<link rel="stylesheet" type="text/css" href="public/util.css">
```

When I build the storybook, the css files are put directly under the root directory so the link doesn't work anymore.

In dev, I also try to use this syntax but It doesn't work: 

```html
<link rel="stylesheet" type="text/css" href="util.css">
```

I currently use a workaround by declaring both path for dev and prod, but that's not very clean.

**Comment by arunoda** [comment]
@mnmtanish could you check on this as well.

**Comment by arunoda** [comment]
@mthuret I think we've fixed a relative bug and try using the latest version of storybook.
Also if you specified your `public` directory with `-s` flag, simply link css like this:

```
<link rel="stylesheet" type="text/css" href="util.css">
```

It should works everywhere.

**Comment by mthuret** [comment]
Yes, I get the issue with the -s flag. Works fine.
