### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by PDXIII** [kadirahq/react-storybook#572]
Hello, folks!

I just wanted to try out **storybook** in my react app, but got this error and can’t find any help with that. Maybe you can point me in the right direction. If you need more information about my setup, please tell me.

[npm-debug.log.txt](https://github.com/kadirahq/react-storybook/files/552970/npm-debug.log.txt)

**Comment by arunoda** [comment]
Check this: https://github.com/kadirahq/react-storybook/issues/15#issuecomment-249229434
