### ISSUE TITLE
Strange issue with Chrome 54.0.2840.71

### ISSUE THREAD

**Issue by wmonk** [kadirahq/react-storybook#573]
Chrome just updated today/yesterday to 54.0.2840.71. For some reason at various points of our component interactions, the main thread is blocked for ~5s. This is obviously painful to use, and from a bit of debugging I can see that webpack is trying to parse/fetch sourcemaps - although I'm not sure why.

I was able to change the webpack config to 
```diff
- devtool: '#cheap-module-eval-source-map',
+ devtool: 'eval',
```

which has alleviated the problem. I have a feeling it's semi related to this issue http://github.com/devtool/issues/74, or the source mapper used in webpack.

**Comment by arunoda** [comment]
Yep. I we should try to do something about the devtool.

**Comment by arunoda** [comment]
Fixed with https://github.com/kadirahq/react-storybook/pull/577
