### ISSUE TITLE
react-native peer dependency warning

### ISSUE THREAD

**Issue by maxg7** [kadirahq/react-storybook#589]
Currently react-native-storybook@2.1.4 requires a peer of react-native@0.27.0-0.34.x.
React-native is currently at 0.36.0.
Every time a new npm dependency is installed or updated this warning pops up again. 

Are there a suite of tests that can be run to verify react-native-storybook works for react-native 0.36.0 and then we can bump up the peer dependency version?

```
├── UNMET PEER DEPENDENCY react-native@0.36.0

npm WARN @kadira/react-native-storybook@2.1.4 requires a peer of react-native@0.27.0 - 0.34.x but none was installed.
```

**Comment by arunoda** [comment]
Could you move your issue here: https://github.com/kadirahq/react-native-storybook
CC @mnmtanish we may need to bump the RN version here.
