### ISSUE TITLE
High CPU Load

### ISSUE THREAD

**Issue by HashDot** [kadirahq/react-storybook#595]
Hi folks,

why does react-storybook consume so much cpu load? I have an other project with react, hmr and the fancy stuff. If the Webpack process done, I have 0-1% cpu load. react-storybook consumed over 80%, all the time.

Is it possible to fix this?

**Comment by arunoda** [comment]
@HashDot that's something to investigate. Let's check.

**Comment by arunoda** [comment]
That's pretty weird.
I can't see something that with the latest storybook.
Are you using a custom webpack config?

Can we have a way to reproduce this locally.

**Comment by HashDot** [comment]
I use storybook in a meteor project. I doesn't have a custom webpack config but I use some babel modules. For testing I removed all my components and custom stuff, the CPU load decreases slightly to ~50/60%.

I try to create a new project without meteor and check the cpu load.

Btw. I use macOS El Capitan 10.11.6 and react-storybook 2.27.0

**Comment by arunoda** [comment]
I think this CPU load is due to Meteor's devtool. Not something related Storybook.
Are you 100% sure, is that storybook node process causing the issue?

Check it with Activity Monitor or top/ps

**Comment by HashDot** [comment]
Meteor isn't running. I created a new meteor project with the same dependencies. Now, the CPU is at 0-1%. I don't know why. I try to provide a CPU Profile, if I find some time for it. It is not a Storybook bug. Thanks for your help and patience.
