### ISSUE TITLE
Customizing the layout

### ISSUE THREAD

**Issue by jide** [kadirahq/react-storybook#62]
It would be great to be able to customize the layout / html / css. Something like adding a custom component in .storybook.

**Comment by arunoda** [comment]
Could you give us more information? What you are trying to achieve?

**Comment by jide** [comment]
I would like to be able to customize the layout, make the sidebar smaller... I tried to inject css in config.js and use global selectors, but it did not work, and seems hackish anyway.

I like to have my code and storybook side by side, and on my screen the current design takes a lot of space. I'm sure there could be many other use cases !

**Comment by jide** [comment]
I made a PR in case you find this useful.

**Comment by jide** [comment]
If someone is interested, this can already be done using a custom webpack config file : 
```js
module.exports = {
  //...
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/^\.\/layout$/, 'custom-layout'),
    new webpack.NormalModuleReplacementPlugin(/^\.\/controls$/, 'custom-controls')
  ],
  resolve: {
    alias: {
      'custom-layout': path.resolve('.storybook/layout.js'),
      'custom-controls': path.resolve('.storybook/controls.js')
    }
  }
}
```

**Comment by arunoda** [comment]
Great. I added a comment on this PR. https://github.com/kadirahq/react-storybook/pull/67
