### ISSUE TITLE
Cannot resolve modules 'stack-source-map' and 'webpack-hot-middleware'

### ISSUE THREAD

**Issue by davidxmoody** [kadirahq/react-storybook#65]
Hi, after installing react-storybook for the first time and trying to run it I always get the following errors:

```
ERROR in multi admin
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /home/dmoody/p/mhb
 @ multi admin

ERROR in multi preview
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /home/dmoody/p/mhb
 @ multi preview

ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /home/dmoody/p/mhb
 @ multi preview
```

Explicitly installing them (with `npm install --save-dev stack-source-map webpack-hot-middleware`) fixes the problem.

I'm not exactly sure where the problem is coming from as they are both listed as dependencies of react-storybook. My guess is that they are needed by webpack which is looking for them in the node_modules of the root of the project but they are actually in `node_modules/@kadira/storybook/node_modules`. I'm using npm v2 and I think maybe npm v3 would put them all in the main node_modules dir. 

Not sure if there is an easy fix or if you are just going to say I should upgrade to npm v3. I still thought I'd raise an issue though.

**Comment by arunoda** [comment]
Yes. That's true. It's because of NPM3. I think we should specifically mention this is only for NPM3. I'll try to do it. 

Thanks for informing. This is an known issue.
