### ISSUE TITLE
Update URL based on currently selected story

### ISSUE THREAD

**Issue by tlrobinson** [kadirahq/react-storybook#66]
It would be nice if the URL path (e.x. `localhost:9001/MyComponent/storyName`) or fragment (e.x. `localhost:9001/#MyComponent/storyName`) updated when switching states, and was used to select the initial state when loading storybook, so that you could share links to a specific component/state, or if you need to do a refresh for whatever reason (crash, etc) it goes back to the last state.

**Comment by arunoda** [comment]
Thanks. We are tracking it here - https://github.com/kadirahq/react-storybook/issues/6
