### ISSUE TITLE
Custom entry point

### ISSUE THREAD

**Issue by simonelp** [kadirahq/react-storybook#72]
Hi,
I'd like to load a global css file (Font icon) valid for all components.
Is there  a way to have an "entry point", common to all the components?

**Comment by simonelp** [comment]
I figured it out.
I imported `main.scss` (which in turn imports my font icon ) from inside `.storybook/config.js`
If there are no better solutions, feel free to close this.

**Comment by arunoda** [comment]
I think this is the way to do it.
