### ISSUE TITLE
Resizable Action Logger

### ISSUE THREAD

**Issue by RamonGebben** [kadirahq/react-storybook#74]
It would be really nice if I could resize the action logger.
Also it would be great if I could pick where it should be located,

- At the left of the screen next to the stories
- on the right of the screen next to the component view
- Botton like now

Like so for instance 

![image](https://cloud.githubusercontent.com/assets/5405406/14353447/65fabe6e-fcd9-11e5-8177-86e7cf0f1f57.png)

**Comment by arunoda** [comment]
If you update to the latest version, you can resize the Action Logger. But, switching it to a different location is not supported yet.

But, there's an adhoc way to do this. See: https://github.com/kadirahq/react-storybook/blob/master/docs/api.md#customizing-the-ui

**Comment by RamonGebben** [comment]
Then I would say the issue can be closed

**Comment by arunoda** [comment]
Cool.
