### ISSUE TITLE
Module not found: Error: Cannot resolve module 'meteor/meteor'

### ISSUE THREAD

**Issue by jhartma** [kadirahq/react-storybook#75]
Hi, I'm getting this error in storybook
```bash
Module not found: Error: Cannot resolve module 'meteor/meteor'
```
In the app itself everything works fine.
How do I tell storybook where to find meteor?

**Comment by arunoda** [comment]
This is not going to work. You should not use any Meteor specific code inside the Storybook. See whether you can do it or not.

If you follow the [Mantra](https://github.com/kadirahq/mantra), this is doable because of it's dependancy injection system.

**Comment by jhartma** [comment]
the 'meteor/meteor' import is not inside the storybook, it's in the app code. But somehow the storybook webpack server is processing the entire app, and that's where the error occurs. I'm also using the webpack:webpack package which may lead to conflicts?

**Comment by arunoda** [comment]
Storybook has nothing to do with any Meteor package. I assume, you are importing a module which uses a module that uses `meteor/meteor`.

**Comment by jhartma** [comment]
I got it working by stubbing the meteor api and exporting it into the global namespace. a bit tedious, but it works

**Comment by arunoda** [comment]
@jhartma Got it.
May be you use a project like this: https://github.com/meteor-velocity/meteor-stubs

**Comment by jhartma** [comment]
@arunoda thx for the hint.

**Comment by zeroasterisk** [comment]
I'm getting this bug, and my config is dead simple:

```js
// .storybook/config.js
import { configure } from '@kadira/storybook';
function loadStories() {
  require('../imports/ui/layouts/stories/Header');
}
configure(loadStories, module);
```

```js
// imports/ui/layouts/stories/Header.jsx
import React from 'react'; 
import { storiesOf, action } from '@kadira/storybook'; 
 
storiesOf('Button', module) 
  .add('with a text', () => ( 
    <button onClick={action('clicked')}>My First Button</button> 
  )) 
  .add('with no text', () => ( 
    <button></button> 
  )); 
```

and I get the bug:

```
er/~/stackframe/stackframe.js 3.48 kB {1} [built]
  [299] ./~/@kadira/storybook/~/redbox-react/~/object-assign/index.js 896 bytes {1} [built]

ERROR in multi admin
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /Users/alan/Code/testapp/webapp
 @ multi admin

ERROR in multi preview
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /Users/alan/Code/testapp/webapp
 @ multi preview

ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/alan/Code/testapp/webapp
 @ multi preview

ERROR in multi preview
Module not found: Error: Cannot resolve module 'babel' in /Users/alan/Code/testapp/webapp
 @ multi preview
```

**Comment by arunoda** [comment]
@zeroasterisk This is someother issue please see: https://github.com/kadirahq/react-storybook/blob/master/docs/known_issues.md#potential-issues-with-npm-2
(You need to use NPM3)

**Comment by zeroasterisk** [comment]
thank you @arunoda - you continue to rule!

**Comment by arunoda** [comment]
Okay. Removing your post since it's unrelated.

**Comment by arunoda** [comment]
Closing this since we've a kind a fix.

**Comment by alexofob** [comment]
@jhartma It would be great if you elaborate on how to export the meteor-stub into the global namespace.

I am also having the same issue with the meteor packages. However, I am not familiar with how to import meteor - stub in the global name space to prevent this  "Module not found: Error: Cannot resolve module 'meteor/meteor' " issue.

Thanks.
