### ISSUE TITLE
Deploy to GH Pages?

### ISSUE THREAD

**Issue by borisyankov** [kadirahq/react-storybook#82]
React Storybook works rally great for me!
So good, that I want to use it as the main thing illustrating one of my projects.

Is there any official process for the output the static files, so I can put them in a gh-pages branch?

**Comment by zimt28** [comment]
There's already a similar issue: https://github.com/kadirahq/react-storybook/issues/11

**Comment by arunoda** [comment]
Closing since we've added this now.
