### ISSUE TITLE
Add panel with component props

### ISSUE THREAD

**Issue by khmelevskii** [kadirahq/react-storybook#87]
<img width="441" alt="screen 2016-04-08 at 14 03 07" src="https://cloud.githubusercontent.com/assets/668591/14381955/c69cae4e-fd92-11e5-9d53-dfb26e146df4.png">

**Comment by arunoda** [comment]
Yeah! Something like this would be great. 
We are discussing something similar here: https://github.com/kadirahq/react-storybook/issues/19#issuecomment-206584563
