### ISSUE TITLE
Separate CSS files

### ISSUE THREAD

**Issue by ritz078** [kadirahq/react-storybook#93]
As the project starts getting bigger, it will make more sense to separate out CSS in different files. We are already using css-loader so that shouldn't be a problem. Also in future we will be able to use CSS feature like keyframe etc and at the same time make the project more modular.

**Comment by arunoda** [comment]
Got it. 
But, How that's relate to this project?
We allow to use any [kind of CSS](https://github.com/kadirahq/react-storybook/blob/master/docs/setting-up-for-css.md).

If this is related to this project, We use CSS in JS mostly. But, we need some cleanup for the use of CSS.

**Comment by ritz078** [comment]
when I was implementing transition n action, I couldn't use CSS's keyframe functionality as they can't be used with inline CSS. So instead I had to use `setTimeout` . Separating it will be better in the long run as it will remove any limitations.

**Comment by arunoda** [comment]
@ritz078 got it.

It is possible for you to use keyframe functionality with Radium.
See: https://github.com/FormidableLabs/radium

If so, I'm happy to use that instead of setTimeout.

**Comment by jeef3** [comment]
Keyframes in Radium: https://github.com/FormidableLabs/radium/tree/master/docs/api#keyframes

*Radium works really well, although I'm personally still undecided on the best CSS approach for use with React.*

**Comment by arunoda** [comment]
I agree with @jeef3 too. 
CSS area where no one agrees with one tech. 
I think, it will be like that.

**Comment by ritz078** [comment]
Thanks . I will go forward with the proposed solution.

**Comment by arunoda** [comment]
Awesome.
