### ISSUE TITLE
Static directory (-s) serves index.html instead of Storybook

### ISSUE THREAD

**Issue by jeef3** [kadirahq/react-storybook#99]
I have static images etc in a `public` directory, as well as my applications `index.html`. I want to make the images available to Storybook (as some are used in my components). However, when I supply the `-s` parameter to serve the static directory, my `index.html` is served up instead of the Storybook app.

**Repro**
 - Create a `public` directory in your app
 - Place a `index.html` in it
 - Start Storybook, providing `./public` as the static dir: `start-storybook -p 9001 -s ./public`
 - Browser to `http://localhost:9001`

Browser displays `index.html` content instead of Storybook app.

**Comment by arunoda** [comment]
Yes. This is valid. But, I'm not sure how to fix it. 

I think best way is to remove index.html from the static directory. 
Is it possible to make that file as something like `index.html.tmpl`.

Otherwise, I'm open some ways to fix this.

**Comment by jeef3** [comment]
Yeah, for now I have renamed my `index.html` :+1:
